In [1]:
pip install requests

Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.5.2-cp313-cp313-win_amd64.whl.metadata (47 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Collecting certifi>=2023.5.7 (from requests)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.2-cp313-cp313-win_amd64.whl (206 kB)
Using cached idna-3.20-py3-none-any.whl (69 kB)
Using cached urllib3-2.8.0-py3-none-any.whl (135 kB)
Using cached certifi-2026.7.22-py3-none-any.whl (136 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   ---------------------------------------- 0/5 [urllib3]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   -------- ------------------------------- 1/5 [idna]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ---------------- ----------------------- 2/5 [charset_normalizer]
   ------------------------ --------------- 3/5 [certifi]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   -------------------------------- ------- 4/5 [requests]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.7.22 charset_normalizer-3.5.2 idna-3.20 requests-2.34.2 urllib3-2.8.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Harish A\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.4-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.6-cp313-cp313-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.6 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.6 MB 1.0 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/9.6 MB 1.1 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.6 MB 1.0 MB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.6 MB 995.8 kB/s eta 0:00:09
   ----- ---------------------------------- 1.3/9.6 MB 995.8 kB/s eta 0:00:09
   ------ --------------------------------- 1.6/9.6 MB 946.2 kB/s eta 0:00:09
   ------- -------------------------------- 1.8/9.6 MB 999.2 kB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.6 MB 1.0 MB/s eta 0:00:08
   -------- ------------------------------- 2.1/9.6 MB 1.0 MB/s eta 0:00:08
   ---------- ----------------------------- 2.6/9.6 MB 994.4 kB/s eta 0:00:08
   ----------- ---------------------------- 2.9/9.6 MB 1.0 MB/s eta 0:00:07
   ------------- -------------------------- 3.1/9.6 MB 1.0 MB/s eta 0:00:07
   ------------- -------------------------- 3.1/9.6 MB 1.0 MB/s eta 0:00:07
   --------------- ------------------------ 3.7/9.6 MB 1.1 MB/s eta 0:00:06
   ---------------- ----------------------- 3.9/9.6 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.6 MB 1.1 MB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.6 MB 1.1 MB/s eta 0:00:05
   ------------------- -------------------- 4.7/9.6 MB 1.1 MB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.6 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.6 MB 1.1 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.6 MB 1.1 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.6 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 6.3/9.6 MB 1.1 MB/s eta 0:00:03
   --------------------------- ------------ 6.6/9.6 MB 1.2 MB/s eta 0:00:03
   ---------------------------- ----------- 6.8/9.6 MB 1.2 MB/s eta 0:00:03
   ----------------------------- ---------- 7.1/9.6 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 7.3/9.6 MB 1.2 MB/s eta 0:00:02
   ------------------------------ --------- 7.3/9.6 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 7.6/9.6 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.6 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 8.1/9.6 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.6 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.6 MB 1.2 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.6 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  9.4/9.6 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 1.1 MB/s  0:00:08
Downloading numpy-2.5.3-cp313-cp313-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 857.3 kB/s eta 0:00:15
   -- ------------------------------------- 0.8/12.6 MB 976.2 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/12.6 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.6 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.6/12.6 MB 1.2 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.1 MB/s eta 0:00:10
   ----- ---------------------------------- 1.8/12.6 MB 1.1 MB/s eta 0:00:10
   ------ --------------------------------- 2.1/12.6 MB 1.1 MB/s eta 0:00:10
   ------- -------------------------------- 2.4/12.6 MB 1.1 MB/s eta 0:00:10
   -------- ------------------------------- 2.6/12.6 MB 1.1 MB/s eta 0:00:10
   --------- ------------------------------ 2.9/12.6 MB 1.1 MB/s eta 0:00:10
   ---------- ----------------------------- 3.1/12.6 MB 1.1 MB/s eta 0:00:09
   ---------- ----------------------------- 3.1/12.6 MB 1.1 MB/s eta 0:00:09
   ---------- ----------------------------- 3.4/12.6 MB 1.1 MB/s eta 0:00:09
   ------------ --------------------------- 3.9/12.6 MB 1.1 MB/s eta 0:00:08
   ------------ --------------------------- 3.9/12.6 MB 1.1 MB/s eta 0:00:08
   ------------- -------------------------- 4.2/12.6 MB 1.1 MB/s eta 0:00:08
   -------------- ------------------------- 4.5/12.6 MB 1.1 MB/s eta 0:00:08
   --------------- ------------------------ 4.7/12.6 MB 1.1 MB/s eta 0:00:08
   --------------- ------------------------ 4.7/12.6 MB 1.1 MB/s eta 0:00:08
   --------------- ------------------------ 5.0/12.6 MB 1.1 MB/s eta 0:00:08
   ---------------- ----------------------- 5.2/12.6 MB 1.1 MB/s eta 0:00:07
   ----------------- ---------------------- 5.5/12.6 MB 1.1 MB/s eta 0:00:07
   ------------------ --------------------- 5.8/12.6 MB 1.1 MB/s eta 0:00:07
   ------------------- -------------------- 6.0/12.6 MB 1.1 MB/s eta 0:00:07
   -------------------- ------------------- 6.6/12.6 MB 1.1 MB/s eta 0:00:06
   --------------------- ------------------ 6.8/12.6 MB 1.1 MB/s eta 0:00:06
   ---------------------- ----------------- 7.1/12.6 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 7.3/12.6 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.6/12.6 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.9/12.6 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 8.1/12.6 MB 1.1 MB/s eta 0:00:04
   -------------------------- ------------- 8.4/12.6 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.7/12.6 MB 1.1 MB/s eta 0:00:04
   ---------------------------- ----------- 8.9/12.6 MB 1.1 MB/s eta 0:00:04
   ----------------------------- ---------- 9.2/12.6 MB 1.1 MB/s eta 0:00:03
   ------------------------------ --------- 9.4/12.6 MB 1.2 MB/s eta 0:00:03
   ------------------------------- -------- 10.0/12.6 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 10.2/12.6 MB 1.2 MB/s eta 0:00:03
   --------------------------------- ------ 10.5/12.6 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.6 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 11.0/12.6 MB 1.2 MB/s eta 0:00:02
   ----------------------------------- ---- 11.3/12.6 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 11.5/12.6 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 1.2 MB/s  0:00:10
Using cached tzdata-2026.4-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Harish A\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import requests
import pandas as pd

In [4]:
records = []

for page in range (1,7):

  url = (f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&{page}&sparkline=False")

  response = requests.get(url)

  if response.status_code == 200:

     data = response.json()

  records.extend(data)


  print(f"Page: {page} Records: {len(data)}")

Page: 1 Records: 250
Page: 2 Records: 250
Page: 3 Records: 250
Page: 4 Records: 250
Page: 5 Records: 250
Page: 6 Records: 250

In [5]:
df = pd.DataFrame(records)
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,8295633.00,166696360627599,1,166696360627599,3.783282e+12,8343988.00,...,2.009238e+07,2.100000e+07,11187013.00,-25.84586,2025-10-06T10:57:42.000Z,3993.420000,2.076326e+05,2013-07-04T16:00:00.000Z,None,2026-10-02T10:57:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,263705.00,32200380712378,2,32200380712378,1.511559e+12,266145.00,...,1.220987e+08,NaN,431946.00,-38.94954,2025-08-24T11:21:03.000Z,28.130000,9.373091e+05,2015-10-19T16:00:00.000Z,"{'times': 40.56836074849733, 'currency': 'btc'...",2026-10-02T10:57:20.000Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,96.11,17691123937520,3,18216591837114,6.981507e+12,96.12,...,1.895247e+11,NaN,105.52,-8.91147,2025-01-25T08:51:57.000Z,36.860000,1.607611e+02,2015-03-01T16:00:00.000Z,None,2026-10-02T10:57:20.000Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,74592.00,9932999719227,4,9932999317161,7.897108e+10,75229.00,...,1.331593e+08,2.000000e+08,121422.00,-38.56807,2025-10-13T00:41:24.000Z,2.580000,2.885758e+06,2017-10-18T16:00:00.000Z,None,2026-10-02T10:57:20.000Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,147.99,9336850458159,5,14796428580637,2.861249e+11,148.14,...,9.998561e+10,1.000000e+11,313.99,-52.86721,2025-07-21T07:02:00.000Z,0.159343,9.277569e+04,2013-08-15T16:00:00.000Z,None,2026-10-02T10:57:20.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,chutes,sn64,Chutes,https://coin-images.coingecko.com/coins/images...,2118.29,12862108416,246,12862108416,5.386983e+07,2121.16,...,6.071789e+06,2.100000e+07,8937.54,-76.29900,2025-06-10T03:46:43.000Z,32.350000,6.448277e+03,2026-03-26T15:23:00.000Z,None,2026-10-02T10:57:20.000Z
1496,zencash,zen,Horizen,https://coin-images.coingecko.com/coins/images...,690.22,12708565820,247,14499254292,1.179427e+09,704.77,...,2.100000e+07,2.100000e+07,12160.33,-94.32401,2021-05-07T22:00:30.000Z,216.390000,2.189756e+02,2017-07-30T16:00:00.000Z,None,2026-10-02T10:57:20.000Z
1497,cash-4,cash,CASH,https://coin-images.coingecko.com/coins/images...,96.09,12644883661,248,12644883661,1.051969e+09,96.11,...,1.315884e+08,NaN,96.92,-0.85151,2026-05-20T14:16:00.000Z,86.470000,1.113358e+01,2025-11-18T22:10:46.000Z,None,2026-10-02T10:57:20.000Z
1498,soon-2,soon,SOON,https://coin-images.coingecko.com/coins/images...,37.13,12622723198,249,409016620887,6.980451e+09,43.65,...,1.101034e+10,NaN,381.39,-90.26500,2025-11-14T12:10:58.000Z,9.330000,2.979715e+02,2026-04-10T01:07:00.000Z,None,2026-10-02T10:57:20.000Z
1499,golem,glm,Golem,https://coin-images.coingecko.com/coins/images...,12.54,12540741325,250,12540741325,1.670207e+08,12.52,...,1.000000e+09,NaN,86.40,-85.48454,2018-04-13T01:13:22.000Z,0.613205,1.945332e+03,2016-12-11T16:00:00.000Z,"{'times': 11.52482202802294, 'currency': 'usd'...",2026-10-02T10:57:20.000Z

In [6]:
df.shape

(1500, 26)

In [7]:
df.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='str')

In [8]:
df = df[["id", "symbol", "name", "current_price",
         "market_cap", "market_cap_rank","total_volume",
         "circulating_supply", "total_supply","ath", "atl","last_updated"]]
df["last_updated"]=pd.to_datetime(df["last_updated"]).dt.date

In [9]:
df

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,8295633.00,166696360627599,1,3.783282e+12,2.009238e+07,2.009238e+07,11187013.00,3993.420000,2026-10-02
1,ethereum,eth,Ethereum,263705.00,32200380712378,2,1.511559e+12,1.220987e+08,1.220987e+08,431946.00,28.130000,2026-10-02
2,tether,usdt,Tether,96.11,17691123937520,3,6.981507e+12,1.840577e+11,1.895247e+11,105.52,36.860000,2026-10-02
3,binancecoin,bnb,BNB,74592.00,9932999719227,4,7.897108e+10,1.331593e+08,1.331593e+08,121422.00,2.580000,2026-10-02
4,ripple,xrp,XRP,147.99,9336850458159,5,2.861249e+11,6.309298e+10,9.998561e+10,313.99,0.159343,2026-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,chutes,sn64,Chutes,2118.29,12862108416,246,5.386983e+07,6.071789e+06,6.071789e+06,8937.54,32.350000,2026-10-02
1496,zencash,zen,Horizen,690.22,12708565820,247,1.179427e+09,1.840646e+07,2.100000e+07,12160.33,216.390000,2026-10-02
1497,cash-4,cash,CASH,96.09,12644883661,248,1.051969e+09,1.315884e+08,1.315884e+08,96.92,86.470000,2026-10-02
1498,soon-2,soon,SOON,37.13,12622723198,249,6.980451e+09,3.397917e+08,1.101034e+10,381.39,9.330000,2026-10-02
1499,golem,glm,Golem,12.54,12540741325,250,1.670207e+08,1.000000e+09,1.000000e+09,86.40,0.613205,2026-10-02

In [10]:
df.columns

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'last_updated'],
      dtype='str')

In [11]:
df.rename(columns={"last_updated":"date"},inplace=True)

In [12]:
df.shape

(1500, 12)

In [13]:
df.columns

Index(['id', 'symbol', 'name', 'current_price', 'market_cap',
       'market_cap_rank', 'total_volume', 'circulating_supply', 'total_supply',
       'ath', 'atl', 'date'],
      dtype='str')

In [14]:
df.to_csv("crypto_data.csv", index=False)

Top 3 Coins – Historical Prices

In [15]:
coin_ids = ["bitcoin", "ethereum", "tether"]

history = []

for coin_id in coin_ids:

    url = f"https://api.coingecko.com/api/v3/coins/{coin_id}/market_chart?vs_currency=usd&days=365"

    response = requests.get(url)
    data = response.json()

    for timestamp, price in data["prices"]:
        history.append({
            "coin_id": coin_id,
            "date": pd.to_datetime(timestamp, unit="ms"),
            "price_usd": price
        })

history_df = pd.DataFrame(history)

history_df

      coin_id                date      price_usd
0     bitcoin 2025-10-03 00:00:00  120514.577856
1     bitcoin 2025-10-04 00:00:00  122294.924417
2     bitcoin 2025-10-05 00:00:00  122428.890634
3     bitcoin 2025-10-06 00:00:00  123488.730597
4     bitcoin 2025-10-07 00:00:00  124739.810888
...       ...                 ...            ...
1093   tether 2026-09-29 00:00:00       0.999677
1094   tether 2026-09-30 00:00:00       0.999692
1095   tether 2026-10-01 00:00:00       0.999543
1096   tether 2026-10-02 00:00:00       0.999723
1097   tether 2026-10-02 11:06:30       0.999801

[1098 rows x 3 columns]

In [16]:
history_df.to_csv("top 3 coin_history.csv", index=False)

In [17]:
history_df.shape

(1098, 3)

In [18]:
history_df.columns

Index(['coin_id', 'date', 'price_usd'], dtype='str')

In [19]:
history_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1098 entries, 0 to 1097
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   coin_id    1098 non-null   str
 1   date       1098 non-null   datetime64[ms]
 2   price_usd  1098 non-null   float64
dtypes: datetime64[ms](1), float64(1), str(1)
memory usage: 25.9 KB

In [20]:
history_df.describe()

                             date      price_usd
count                        1098    1098.000000
mean   2026-04-03 11:57:53.178000   27415.054154
min           2025-10-03 00:00:00       0.998360
25%           2026-01-02 00:00:00       0.999986
50%           2026-04-03 12:00:00    2326.486705
75%           2026-07-04 00:00:00   66798.730266
max           2026-10-02 11:06:30  124739.810888
std                           NaN   38036.199251

In [21]:
history_df["coin_id"].value_counts()

coin_id
bitcoin     366
ethereum    366
tether      366
Name: count, dtype: int64

Oil Prices (WTI Crude) bold text

In [22]:
data = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")

In [23]:
oil_df = pd.DataFrame(data)

In [24]:
oil_df

            Date  Price
0     1986-01-02  25.56
1     1986-01-03  26.00
2     1986-01-06  26.53
3     1986-01-07  25.85
4     1986-01-08  25.87
...          ...    ...
9507  2026-09-23  93.38
9508  2026-09-24  95.88
9509  2026-09-25  85.23
9510  2026-09-28  99.37
9511  2026-09-29  96.16

[9512 rows x 2 columns]

In [25]:
oil_df[oil_df["Date"].between("2020-01-01","2026-01-01")]

            Date  Price
7826  2020-01-02  61.17
7827  2020-01-03  63.00
7828  2020-01-06  63.27
7829  2020-01-07  62.70
7830  2020-01-08  59.65
...          ...    ...
9321  2025-12-24  58.72
9322  2025-12-26  56.60
9323  2025-12-29  57.89
9324  2025-12-30  57.79
9325  2025-12-31  57.26

[1500 rows x 2 columns]

In [26]:
oil_df.to_csv("oil_price.csv", index=False)

Stock Prices (Yahoo Finance API)

In [28]:
pip install yfinance

Defaulting to user installation because normal site-packages is not writeable
Collecting yfinance
  Downloading yfinance-1.7.0-py3-none-any.whl.metadata (6.7 kB)
Collecting beautifulsoup4>=4.11.1 (from yfinance)
  Using cached beautifulsoup4-4.15.0-py3-none-any.whl.metadata (3.8 kB)
Collecting curl_cffi>=0.15 (from yfinance)
  Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl.metadata (17 kB)
Collecting lxml>=4.9.0 (from yfinance)
  Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl.metadata (3.4 kB)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.13-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.16.5 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from yfinance) (2.5.3)
Requirement already satisfied: pandas>=1.3.0 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from yfinance) (3.0.6)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-4.5.2-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: platformdirs>=2.0.0 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from yfinance) (4.12.2)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pytz>=2022.5 (from yfinance)
  Downloading pytz-2026.4-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: requests>=2.31 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from yfinance) (2.34.2)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-17.1-cp313-cp313-win_amd64.whl.metadata (6.5 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4>=4.11.1->yfinance)
  Using cached soupsieve-2.10-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Collecting cffi>=2.0.0 (from curl_cffi>=0.15->yfinance)
  Downloading cffi-2.1.1-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Requirement already satisfied: certifi>=2024.2.2 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from curl_cffi>=0.15->yfinance) (2026.7.22)
Collecting pycparser (from cffi>=2.0.0->curl_cffi>=0.15->yfinance)
  Using cached pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas>=1.3.0->yfinance) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.31->yfinance) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\Harish A\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from requests>=2.31->yfinance) (2.8.0)
Downloading yfinance-1.7.0-py3-none-any.whl (149 kB)
Using cached beautifulsoup4-4.15.0-py3-none-any.whl (109 kB)
Downloading curl_cffi-0.16.3-cp310-abi3-win_amd64.whl (2.0 MB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.0 MB 2.2 MB/s eta 0:00:01
   -------------------------- ------------- 1.3/2.0 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 1.8/2.0 MB 3.0 MB/s eta 0:00:01
   ---------------------------------------- 2.0/2.0 MB 2.8 MB/s  0:00:00
Downloading cffi-2.1.1-cp313-cp313-win_amd64.whl (185 kB)
Downloading lxml-6.1.3-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 3.2 MB/s eta 0:00:02
   ---------- ----------------------------- 1.0/4.0 MB 3.1 MB/s eta 0:00:01
   --------------- ------------------------ 1.6/4.0 MB 2.7 MB/s eta 0:00:01
   ----------------------- ---------------- 2.4/4.0 MB 2.8 MB/s eta 0:00:01
   -------------------------- ------------- 2.6/4.0 MB 2.8 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 2.3 MB/s  0:00:01
Downloading multitasking-0.0.13-py3-none-any.whl (16 kB)
Downloading peewee-4.5.2-py3-none-any.whl (194 kB)
Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl (456 kB)
Downloading pytz-2026.4-py2.py3-none-any.whl (506 kB)
Using cached soupsieve-2.10-py3-none-any.whl (38 kB)
Downloading websockets-17.1-cp313-cp313-win_amd64.whl (217 kB)
Using cached pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: pytz, multitasking, websockets, soupsieve, pycparser, protobuf, peewee, lxml, cffi, beautifulsoup4, curl_cffi, yfinance

   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   ----------------------------------------  0/12 [pytz]
   --- ------------------------------------  1/12 [multitasking]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ------ ---------------------------------  2/12 [websockets]
   ---------- -----------------------------  3/12 [soupsieve]
   ---------- -----------------------------  3/12 [soupsieve]
   ---------- -----------------------------  3/12 [soupsieve]
   ------------- --------------------------  4/12 [pycparser]
   ------------- --------------------------  4/12 [pycparser]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   ---------------- -----------------------  5/12 [protobuf]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   -------------------- -------------------  6/12 [peewee]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   ----------------------- ----------------  7/12 [lxml]
   -------------------------- -------------  8/12 [cffi]
   -------------------------- -------------  8/12 [cffi]
   -------------------------- -------------  8/12 [cffi]
   -------------------------- -------------  8/12 [cffi]
   -------------------------- -------------  8/12 [cffi]
   -------------------------- -------------  8/12 [cffi]
   -------------------------- -------------  8/12 [cffi]
   ------------------------------ ---------  9/12 [beautifulsoup4]
   ------------------------------ ---------  9/12 [beautifulsoup4]
   ------------------------------ ---------  9/12 [beautifulsoup4]
   ------------------------------ ---------  9/12 [beautifulsoup4]
   ------------------------------ ---------  9/12 [beautifulsoup4]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   --------------------------------- ------ 10/12 [curl_cffi]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ------------------------------------ --- 11/12 [yfinance]
   ---------------------------------------- 12/12 [yfinance]

Successfully installed beautifulsoup4-4.15.0 cffi-2.1.1 curl_cffi-0.16.3 lxml-6.1.3 multitasking-0.0.13 peewee-4.5.2 protobuf-7.36.2 pycparser-3.0 pytz-2026.4 soupsieve-2.10 websockets-17.1 yfinance-1.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Harish A\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [29]:
import yfinance as yf
import pandas as pd

# Choose indices
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-08-25"

# Download historical data
stocks_df = yf.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

[*********************100%***********************]  3 of 3 completed

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

Ticker             ^NSEI
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

In [30]:
stocks_1 = stocks_df["^NSEI"].reset_index()
stocks_1["Ticker"] = "^NSEI"

stocks_2 = stocks_df["^IXIC"].reset_index()
stocks_2["Ticker"] = "^IXIC"

stocks_3 = stocks_df["^GSPC"].reset_index()
stocks_3["Ticker"] = "^GSPC"

In [31]:
stocks_final = pd.concat([stocks_1, stocks_2, stocks_3],ignore_index=True)

In [32]:
stocks_final.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Ticker'], dtype='str', name='Price')

In [33]:
pd.DataFrame(stocks_final)

Price,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05,^NSEI
...,...,...,...,...,...,...,...
5164,2026-08-18,7700.040039,7713.950195,7688.629883,7691.759766,4.602700e+09,^GSPC
5165,2026-08-19,7716.740234,7743.930176,7700.069824,7707.979980,5.184100e+09,^GSPC
5166,2026-08-20,7690.490234,7699.959961,7639.009766,7641.160156,4.759610e+09,^GSPC
5167,2026-08-21,7665.680176,7697.109863,7660.060059,7674.370117,4.497270e+09,^GSPC
5168,2026-08-24,7663.379883,7670.299805,7638.169922,7652.859863,4.400800e+09,^GSPC

In [34]:
stocks_final.shape

(5169, 7)

In [35]:
stocks_final.to_csv("stocks_price.csv", index=False)

In [36]:
pip install mysql-connector

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     -- ------------------------------------- 0.8/11.9 MB 2.3 MB/s eta 0:00:05
     ---- ----------------------------------- 1.3/11.9 MB 2.3 MB/s eta 0:00:05
     ----- ---------------------------------- 1.6/11.9 MB 2.1 MB/s eta 0:00:05
     ------- -------------------------------- 2.1/11.9 MB 2.0 MB/s eta 0:00:05
     ------- -------------------------------- 2.4/11.9 MB 2.0 MB/s eta 0:00:05
     -------- ------------------------------- 2.6/11.9 MB 2.0 MB/s eta 0:00:05
     --------- ------------------------------ 2.9/11.9 MB 1.9 MB/s eta 0:00:05
     ----------- ---------------------------- 3.4/11.9 MB 1.8 MB/s eta 0:00:05
     ------------ --------------------------- 3.7/11.9 MB 1.8 MB/s eta 0:00:05
     ------------- -------------------------- 3.9/11.9 MB 1.8 MB/s eta 0:00:05
     -------------- ------------------------- 4.2/11.9 MB 1.7 MB/s eta 0:00:05
     --------------- ------------------------ 4.7/11.9 MB 1.8 MB/s eta 0:00:05
     ----------------- ---------------------- 5.2/11.9 MB 1.8 MB/s eta 0:00:04
     ------------------ --------------------- 5.5/11.9 MB 1.8 MB/s eta 0:00:04
     ------------------- -------------------- 5.8/11.9 MB 1.7 MB/s eta 0:00:04
     -------------------- ------------------- 6.0/11.9 MB 1.7 MB/s eta 0:00:04
     ---------------------- ----------------- 6.6/11.9 MB 1.7 MB/s eta 0:00:04
     ----------------------- ---------------- 7.1/11.9 MB 1.8 MB/s eta 0:00:03
     ------------------------- -------------- 7.6/11.9 MB 1.8 MB/s eta 0:00:03
     --------------------------- ------------ 8.1/11.9 MB 1.8 MB/s eta 0:00:03
     ----------------------------- ---------- 8.7/11.9 MB 1.9 MB/s eta 0:00:02
     ------------------------------ --------- 9.2/11.9 MB 1.9 MB/s eta 0:00:02
     -------------------------------- ------- 9.7/11.9 MB 1.9 MB/s eta 0:00:02
     ---------------------------------- ----- 10.2/11.9 MB 1.9 MB/s eta 0:00:01
     ------------------------------------ --- 10.7/11.9 MB 1.9 MB/s eta 0:00:01
     ------------------------------------- -- 11.0/11.9 MB 1.9 MB/s eta 0:00:01
     -------------------------------------- - 11.5/11.9 MB 2.0 MB/s eta 0:00:01
     ---------------------------------------- 11.9/11.9 MB 1.9 MB/s  0:00:06
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql-connector
  Building wheel for mysql-connector (pyproject.toml): started
  Building wheel for mysql-connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql-connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=248050 sha256=7cb3b8eb96317ea3c390ed8710ed3c36d27ecec1004302a39096c4333369dab4
  Stored in directory: c:\users\harish a\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql-connector
Installing collected packages: mysql-connector
Successfully installed mysql-connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\Harish A\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [51]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="Skpharish@15",
    database="market_analysis"
)

cursor = conn.cursor()

print("Connected successfully!")

Connected successfully!

In [3]:
cursor.execute("use market_analysis")

In [4]:
cursor.execute("""create table Cryptocurrencies(
    id VARCHAR(100) PRIMARY KEY,
    symbol VARCHAR(10),
    name VARCHAR(100),
    current_price DECIMAL(18,6),
    market_cap BIGINT,
    market_cap_rank INT,
    total_volume BIGINT,
    circulating_supply DECIMAL(30,8),
    total_supply DECIMAL(30,8),
    ath DECIMAL(18,6),
    atl DECIMAL(18,6),
    date DATE)
    """)
conn.commit()

In [5]:
cursor.execute("""create table crypto_prices(
    coin_id VARCHAR(50),
    date DATE,
    price_usd DECIMAL(18,6),
    FOREIGN KEY (coin_id) REFERENCES Cryptocurrencies(id)
    )
    """)
conn.commit()

In [6]:
cursor.execute("""create table oil_prices(
date DATE PRIMARY KEY,
    price_usd DECIMAL(18,6)
    )
    """)
conn.commit()

In [7]:
cursor.execute("""create table Stock_prices(
    date DATE,
    open DECIMAL(18,6),
    high DECIMAL(18,6),
    low DECIMAL(18,6),
    close DECIMAL(18,6),
    volume BIGINT,
    ticker VARCHAR(20)
    )
    """)
conn.commit()

In [8]:
import pandas as pd

In [9]:
df1 = pd.read_csv("D:\project1\crypto_data.csv")
df1

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Harish A\AppData\Local\Temp\ipykernel_1492\171768848.py:1: SyntaxWarning: invalid escape sequence '\p'
  df1 = pd.read_csv("D:\project1\crypto_data.csv")

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,date
0,bitcoin,btc,Bitcoin,8295633.00,166696360627599,1,3.783282e+12,2.009238e+07,2.009238e+07,11187013.00,3993.420000,2026-10-02
1,ethereum,eth,Ethereum,263705.00,32200380712378,2,1.511559e+12,1.220987e+08,1.220987e+08,431946.00,28.130000,2026-10-02
2,tether,usdt,Tether,96.11,17691123937520,3,6.981507e+12,1.840577e+11,1.895247e+11,105.52,36.860000,2026-10-02
3,binancecoin,bnb,BNB,74592.00,9932999719227,4,7.897108e+10,1.331593e+08,1.331593e+08,121422.00,2.580000,2026-10-02
4,ripple,xrp,XRP,147.99,9336850458159,5,2.861249e+11,6.309298e+10,9.998561e+10,313.99,0.159343,2026-10-02
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,chutes,sn64,Chutes,2118.29,12862108416,246,5.386983e+07,6.071789e+06,6.071789e+06,8937.54,32.350000,2026-10-02
1496,zencash,zen,Horizen,690.22,12708565820,247,1.179427e+09,1.840646e+07,2.100000e+07,12160.33,216.390000,2026-10-02
1497,cash-4,cash,CASH,96.09,12644883661,248,1.051969e+09,1.315884e+08,1.315884e+08,96.92,86.470000,2026-10-02
1498,soon-2,soon,SOON,37.13,12622723198,249,6.980451e+09,3.397917e+08,1.101034e+10,381.39,9.330000,2026-10-02
1499,golem,glm,Golem,12.54,12540741325,250,1.670207e+08,1.000000e+09,1.000000e+09,86.40,0.613205,2026-10-02

In [10]:
df1 = df1.drop_duplicates(subset=["id"])

In [12]:
cursor.executemany("""insert into Cryptocurrencies
    (id, symbol, name, current_price, market_cap, market_cap_rank, total_volume, circulating_supply, total_supply, ath, atl, date)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
    """,df1.values.tolist())
conn.commit()

In [16]:
df2 = pd.read_csv("D:/project1/top 3 coin_history.csv")
df2

      coin_id                 date      price_usd
0     bitcoin  2025-10-03 00:00:00  120514.577856
1     bitcoin  2025-10-04 00:00:00  122294.924417
2     bitcoin  2025-10-05 00:00:00  122428.890634
3     bitcoin  2025-10-06 00:00:00  123488.730597
4     bitcoin  2025-10-07 00:00:00  124739.810888
...       ...                  ...            ...
1093   tether  2026-09-29 00:00:00       0.999677
1094   tether  2026-09-30 00:00:00       0.999692
1095   tether  2026-10-01 00:00:00       0.999543
1096   tether  2026-10-02 00:00:00       0.999723
1097   tether  2026-10-02 11:06:30       0.999801

[1098 rows x 3 columns]

In [17]:
df2["coin_id"].unique()

<StringArray>
['bitcoin', 'ethereum', 'tether']
Length: 3, dtype: str

In [18]:
cursor.executemany("""INSERT INTO crypto_prices
    (coin_id, date, price_usd)
    VALUES (%s, %s, %s)
    """,df2.values.tolist())
conn.commit()

In [19]:
df3 = pd.read_csv("D:\project1\oil_price.csv")
df3

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Harish A\AppData\Local\Temp\ipykernel_1492\3994135470.py:1: SyntaxWarning: invalid escape sequence '\p'
  df3 = pd.read_csv("D:\project1\oil_price.csv")

            Date  Price
0     1986-01-02  25.56
1     1986-01-03  26.00
2     1986-01-06  26.53
3     1986-01-07  25.85
4     1986-01-08  25.87
...          ...    ...
9507  2026-09-23  93.38
9508  2026-09-24  95.88
9509  2026-09-25  85.23
9510  2026-09-28  99.37
9511  2026-09-29  96.16

[9512 rows x 2 columns]

In [20]:
cursor.executemany("""INSERT INTO oil_prices
    (date, price_usd)
    VALUES (%s, %s)
    """,df3.values.tolist())
conn.commit()

In [22]:
df4 = pd.read_csv("D:\project1\stocks_price.csv")
df4

<>:1: SyntaxWarning: invalid escape sequence '\p'
<>:1: SyntaxWarning: invalid escape sequence '\p'
C:\Users\Harish A\AppData\Local\Temp\ipykernel_1492\3867140547.py:1: SyntaxWarning: invalid escape sequence '\p'
  df4 = pd.read_csv("D:\project1\stocks_price.csv")

,Date,Open,High,Low,Close,Volume,Ticker
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05,^NSEI
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05,^NSEI
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05,^NSEI
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05,^NSEI
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05,^NSEI
...,...,...,...,...,...,...,...
5164,2026-08-18,7700.040039,7713.950195,7688.629883,7691.759766,4.602700e+09,^GSPC
5165,2026-08-19,7716.740234,7743.930176,7700.069824,7707.979980,5.184100e+09,^GSPC
5166,2026-08-20,7690.490234,7699.959961,7639.009766,7641.160156,4.759610e+09,^GSPC
5167,2026-08-21,7665.680176,7697.109863,7660.060059,7674.370117,4.497270e+09,^GSPC
5168,2026-08-24,7663.379883,7670.299805,7638.169922,7652.859863,4.400800e+09,^GSPC

In [23]:
cursor.executemany("""INSERT INTO Stock_prices
    (date, open, high, low, close, volume, ticker)
    VALUES (%s, %s, %s, %s, %s, %s, %s)
    """,df4.values.tolist())
conn.commit()

In [24]:
cursor.execute("""
SELECT id, symbol, name, market_cap, market_cap_rank
FROM cryptocurrencies
ORDER BY market_cap DESC
LIMIT 3
""")

result = cursor.fetchall()
result

[('bitcoin', 'btc', 'Bitcoin', 166696360627599, 1),
 ('ethereum', 'eth', 'Ethereum', 32200380712378, 2),
 ('tether', 'usdt', 'Tether', 17691123937520, 3)]

In [25]:
cursor.execute("""
SELECT id, symbol, name, circulating_supply, total_supply
FROM cryptocurrencies
WHERE total_supply IS NOT NULL
AND circulating_supply > 0.90 * total_supply
""")

result = cursor.fetchall()
result

[('1inch',
  '1inch',
  '1INCH',
  Decimal('1405573965.72750330'),
  Decimal('1499999999.99700000')),
 ('a7a5',
  'a7a5',
  'A7A5',
  Decimal('39237341548.10074000'),
  Decimal('39237548476.40073000')),
 ('aave',
  'aave',
  'Aave',
  Decimal('15434997.59618672'),
  Decimal('16000000.00000000')),
 ('agora-dollar',
  'ausd',
  'AUSD',
  Decimal('218148511.71990800'),
  Decimal('220176012.68623600')),
 ('aioz-network',
  'aioz',
  'AIOZ Network',
  Decimal('1281464390.68438120'),
  Decimal('1281747105.53341000')),
 ('akash-network',
  'akt',
  'Akash Network',
  Decimal('298333532.53828500'),
  Decimal('298407950.36224400')),
 ('algorand',
  'algo',
  'Algorand',
  Decimal('9058106367.93640000'),
  Decimal('9062251796.44487400')),
 ('ape-and-pepe',
  'apepe',
  'Ape and Pepe',
  Decimal('210000000000000.00000000'),
  Decimal('210000000000000.00000000')),
 ('apecoin',
  'ape',
  'ApeCoin',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('apenft',
  'nft',
  'AINFT',
  Decimal('990105592982874.80000000'),
  Decimal('990105592982874.80000000')),
 ('apxusd',
  'apxusd',
  'apxUSD',
  Decimal('320698767.65945330'),
  Decimal('320698767.65945330')),
 ('apyusd',
  'apyusd',
  'apyUSD',
  Decimal('120969184.20119695'),
  Decimal('120969184.20119690')),
 ('artificial-inu-3',
  'ai',
  'Artificial Inu',
  Decimal('991203789.84095530'),
  Decimal('991203789.84095530')),
 ('arweave',
  'ar',
  'Arweave',
  Decimal('65652466.00000000'),
  Decimal('65652466.00000000')),
 ('avalanche-2',
  'avax',
  'Avalanche',
  Decimal('443176938.90073370'),
  Decimal('469845805.72890450')),
 ('basic-attention-token',
  'bat',
  'Basic Attention',
  Decimal('1495724656.95260550'),
  Decimal('1500000000.00000000')),
 ('bfusd',
  'bfusd',
  'BFUSD',
  Decimal('1320000000.00000000'),
  Decimal('1320000000.00000000')),
 ('bianrensheng',
  '币安人生',
  '币安人生 (BinanceLife)',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('binancecoin',
  'bnb',
  'BNB',
  Decimal('133159312.52000000'),
  Decimal('133159303.71000000')),
 ('bitcoin',
  'btc',
  'Bitcoin',
  Decimal('20092375.00000000'),
  Decimal('20092384.00000000')),
 ('bitcoin-cash',
  'bch',
  'Bitcoin Cash',
  Decimal('20097324.89665076'),
  Decimal('20097340.52165076')),
 ('bitcoin-cash-sv',
  'bsv',
  'Bitcoin SV',
  Decimal('20091403.12500000'),
  Decimal('20091600.00000000')),
 ('bittorrent',
  'btt',
  'BitTorrent',
  Decimal('987037885840674.80000000'),
  Decimal('990000000000000.00000000')),
 ('blackrock-usd-institutional-digital-liquidity-fund',
  'buidl',
  'BlackRock USD Institutional Digital Liquidity Fund',
  Decimal('2262646716.18764900'),
  Decimal('2262646716.18764900')),
 ('blockchain-capital',
  'bcap',
  'Blockchain Capital',
  Decimal('9112111.00000000'),
  Decimal('9112111.00000000')),
 ('blockstack',
  'stx',
  'Stacks',
  Decimal('1871098180.30180900'),
  Decimal('1871108880.30180900')),
 ('bnb48-club-token',
  'koge',
  'KOGE',
  Decimal('3379997.60000000'),
  Decimal('3379997.60000000')),
 ('bonk',
  'bonk',
  'Bonk',
  Decimal('87994374942476.20000000'),
  Decimal('87994374942476.20000000')),
 ('build-on',
  'b',
  'BUILDon',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('canton-network',
  'cc',
  'Canton',
  Decimal('39740505152.82366000'),
  Decimal('39741422195.69073000')),
 ('cash-4',
  'cash',
  'CASH',
  Decimal('131588435.78477600'),
  Decimal('131588435.78477600')),
 ('cash-cat',
  'cashcat',
  'Cash Cat',
  Decimal('987874689.08362140'),
  Decimal('987874689.08362140')),
 ('celium',
  'sn51',
  'lium',
  Decimal('4808160.98918866'),
  Decimal('4808160.98918866')),
 ('chiliz',
  'chz',
  'Chiliz',
  Decimal('10544199836.00000000'),
  Decimal('10544199836.00000000')),
 ('chutes',
  'sn64',
  'Chutes',
  Decimal('6071789.11632048'),
  Decimal('6071789.11632048')),
 ('circle-internet-group-bstock',
  'crclb',
  'Circle Internet Group (bStocks Tokenized Stock)',
  Decimal('1607301.13533291'),
  Decimal('1608067.80784469')),
 ('coco-2',
  'coco',
  'coco',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('compound-governance-token',
  'comp',
  'Compound',
  Decimal('10000000.00000000'),
  Decimal('10000000.00000000')),
 ('conflux-token',
  'cfx',
  'Conflux',
  Decimal('5243556444.14000000'),
  Decimal('5244138873.06000000')),
 ('convex-finance',
  'cvx',
  'Convex Finance',
  Decimal('93194518.49512772'),
  Decimal('99993015.87972511')),
 ('cosmos',
  'atom',
  'Cosmos Hub',
  Decimal('533769512.35881700'),
  Decimal('533791855.24177200')),
 ('crvusd',
  'crvusd',
  'crvUSD',
  Decimal('231229495.45449080'),
  Decimal('231578327.87970280')),
 ('dai',
  'dai',
  'Dai',
  Decimal('4587545593.36784300'),
  Decimal('4619754252.04067400')),
 ('dash',
  'dash',
  'Dash',
  Decimal('12850774.70616871'),
  Decimal('12851086.78132121')),
 ('decred',
  'dcr',
  'Decred',
  Decimal('17629199.78156046'),
  Decimal('17629388.49731432')),
 ('dogecoin',
  'doge',
  'Dogecoin',
  Decimal('156154276383.70520000'),
  Decimal('156156346383.70520000')),
 ('dogwifcoin',
  'wif',
  'dogwifhat',
  Decimal('998926392.00000000'),
  Decimal('998926392.00000000')),
 ('ecash',
  'xec',
  'eCash',
  Decimal('20091376547580.00000000'),
  Decimal('20091448422580.00000000')),
 ('elrond-erd-2',
  'egld',
  'MultiversX',
  Decimal('30870098.00000000'),
  Decimal('30870098.00000000')),
 ('ethena-usde',
  'usde',
  'Ethena USDe',
  Decimal('4904466489.66296700'),
  Decimal('4904560353.72066500')),
 ('ether-fi',
  'ethfi',
  'Ether.fi',
  Decimal('965350000.00000000'),
  Decimal('965350000.00000000')),
 ('ethereum',
  'eth',
  'Ethereum',
  Decimal('122098689.50213154'),
  Decimal('122098689.50213150')),
 ('ethereum-classic',
  'etc',
  'Ethereum Classic',
  Decimal('158350715.60090342'),
  Decimal('158351899.33175480')),
 ('euro-coin',
  'eurc',
  'EURC',
  Decimal('421327668.57399020'),
  Decimal('423422760.89257120')),
 ('eutbl',
  'eutbl',
  'Spiko EU T-Bills Money Market Fund',
  Decimal('576412363.55825000'),
  Decimal('555742361.39701000')),
 ('falcon-finance',
  'usdf',
  'Falcon USD',
  Decimal('1561607327.26523970'),
  Decimal('1609990603.51503300')),
 ('fartcoin',
  'fartcoin',
  'Fartcoin',
  Decimal('999917449.66027700'),
  Decimal('999917448.81187200')),
 ('figure-heloc',
  'figr_heloc',
  'Figure Heloc',
  Decimal('23399762227.81800000'),
  Decimal('23399762227.81800000')),
 ('first-digital-usd',
  'fdusd',
  'First Digital USD',
  Decimal('325042596.91049600'),
  Decimal('325042596.91049600')),
 ('floki',
  'floki',
  'FLOKI',
  Decimal('9643112692798.45100000'),
  Decimal('9643112692798.45100000')),
 ('frax',
  'frax',
  'Legacy Frax Dollar',
  Decimal('219310245.87260040'),
  Decimal('219310245.87260030')),
 ('gho',
  'gho',
  'GHO',
  Decimal('699000000.00000000'),
  Decimal('699000000.00000000')),
 ('global-dollar',
  'usdg',
  'Global Dollar',
  Decimal('3173645165.51703700'),
  Decimal('3173745134.33611600')),
 ('gmt-token',
  'gomining',
  'GoMining Token',
  Decimal('402942408.63247010'),
  Decimal('402942408.63247010')),
 ('golem',
  'glm',
  'Golem',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('grx-chain',
  'grx',
  'GRX Chain',
  Decimal('9512395.00000000'),
  Decimal('9998039.00000000')),
 ('hashnote-usyc',
  'usyc',
  'Circle USYC',
  Decimal('2111916940.47775500'),
  Decimal('2111916940.47775500')),
 ('havven',
  'snx',
  'Synthetix',
  Decimal('580980590.45728810'),
  Decimal('581404223.55566310')),
 ('htx-dao',
  'htx',
  'HTX DAO',
  Decimal('898232728634017.20000000'),
  Decimal('898232728634017.20000000')),
 ('injective-protocol',
  'inj',
  'Injective',
  Decimal('100000000.00000000'),
  Decimal('100000000.00000000')),
 ('internet-computer',
  'icp',
  'Internet Computer',
  Decimal('557007092.91533760'),
  Decimal('557007382.80451110')),
 ('iota',
  'iota',
  'IOTA',
  Decimal('4673291998.00000000'),
  Decimal('4994922684.00000000')),
 ('janus-henderson-anemoy-aaa-clo-fund',
  'jaaa',
  'Janus Henderson Anemoy AAA CLO Fund',
  Decimal('556927498.37885300'),
  Decimal('556927498.37885300')),
 ('janus-henderson-anemoy-treasury-fund',
  'jtrsy',
  'Janus Henderson Anemoy Treasury Fund',
  Decimal('291807107.73009400'),
  Decimal('291807107.73009400')),
 ('jasmycoin',
  'jasmy',
  'JasmyCoin',
  Decimal('49444999677.59027000'),
  Decimal('50000000000.00000000')),
 ('jpycoin',
  'jpyc',
  'JPY Coin',
  Decimal('21285482436.95474000'),
  Decimal('21285482436.95474000')),
 ('just',
  'jst',
  'JUST',
  Decimal('8188743036.34173700'),
  Decimal('8188743036.34173700')),
 ('kaia',
  'kaia',
  'Kaia',
  Decimal('6433861143.84397800'),
  Decimal('6434031770.97470600')),
 ('kaspa',
  'kas',
  'Kaspa',
  Decimal('27732249762.74345000'),
  Decimal('27733651623.79915000')),
 ('kinesis-gold',
  'kau',
  'Kinesis Gold',
  Decimal('3986181.45920000'),
  Decimal('2386227.83420000')),
 ('kinesis-silver',
  'kag',
  'Kinesis Silver',
  Decimal('3664037.12860000'),
  Decimal('3777096.93360000')),
 ('kucoin-shares',
  'kcs',
  'KuCoin',
  Decimal('139655021.27739550'),
  Decimal('142155021.27739550')),
 ('leo-token',
  'leo',
  'LEO Token',
  Decimal('919857851.90000000'),
  Decimal('985239504.00000000')),
 ('litecoin',
  'ltc',
  'Litecoin',
  Decimal('77670260.82174040'),
  Decimal('77673160.82963460')),
 ('meta-2-2',
  'meta',
  'MetaDAO',
  Decimal('22684686.32487100'),
  Decimal('22684686.32487100')),
 ('mina-protocol',
  'mina',
  'Mina Protocol',
  Decimal('1293631019.84003900'),
  Decimal('1293631019.84003900')),
 ('monero',
  'xmr',
  'Monero',
  Decimal('18812242.25036509'),
  Decimal('18812287.84977191')),
 ('near',
  'near',
  'NEAR Protocol',
  Decimal('1307873756.00000000'),
  Decimal('1307873762.00000000')),
 ('nexo',
  'nexo',
  'NEXO',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('non-playable-coin',
  'npc',
  'Non-Playable Coin',
  Decimal('8050126520.00000000'),
  Decimal('8050126520.00000000')),
 ('okb',
  'okb',
  'OKB',
  Decimal('21000000.00000000'),
  Decimal('21000000.00000000')),
 ('ondo-us-dollar-yield',
  'usdy',
  'Ondo US Dollar Yield',
  Decimal('1986442681.75723120'),
  Decimal('1989145747.75810100')),
 ('open-usd',
  'ousd',
  'Open USD',
  Decimal('668499643.93000000'),
  Decimal('668499643.93000000')),
 ('ousg',
  'ousg',
  'Ondo Short-Term U.S. Government Bond Fund',
  Decimal('2738455.14476738'),
  Decimal('2738455.14476738')),
 ('pancakeswap-token',
  'cake',
  'PancakeSwap',
  Decimal('330679794.05459136'),
  Decimal('342286106.38207420')),
 ('pax-gold',
  'paxg',
  'PAX Gold',
  Decimal('435070.59053900'),
  Decimal('435070.59053900')),
 ('paypal-usd',
  'pyusd',
  'PayPal USD',
  Decimal('2865863495.48764320'),
  Decimal('2865863495.48764300')),
 ('pepe',
  'pepe',
  'Pepe',
  Decimal('420690000000000.00000000'),
  Decimal('420690000000000.00000000')),
 ('polkadot',
  'dot',
  'Polkadot',
  Decimal('1705455554.89480140'),
  Decimal('1705473292.61870100')),
 ('polygon-ecosystem-token',
  'pol',
  'POL (ex-MATIC)',
  Decimal('10624572016.54051400'),
  Decimal('10624572016.54051200')),
 ('pons',
  'pons',
  'Pons',
  Decimal('681724299.15971740'),
  Decimal('681752147.76285740')),
 ('quant-network',
  'qnt',
  'Quant',
  Decimal('14544176.16408118'),
  Decimal('14612493.00000000')),
 ('railgun',
  'rail',
  'Railgun',
  Decimal('60000000.00000000'),
  Decimal('60000000.00000000')),
 ('re-protocol-reusd',
  'reusd',
  'Re Protocol reUSD',
  Decimal('269640569.92454750'),
  Decimal('269440016.92454750')),
 ('render-token',
  'render',
  'Render',
  Decimal('518776241.28269154'),
  Decimal('533536414.56269150')),
 ('ripple-usd',
  'rlusd',
  'Ripple USD',
  Decimal('2509774082.01720900'),
  Decimal('2508918019.01720600')),
 ('safepal',
  'sfp',
  'SafePal',
  Decimal('500000000.00000000'),
  Decimal('500000000.00000000')),
 ('safo',
  'safo',
  'Spiko Amundi Overnight Swap Fund',
  Decimal('206105815.48266000'),
  Decimal('206105815.48266000')),
 ('shiba-inu',
  'shib',
  'Shiba Inu',
  Decimal('589238865672620.00000000'),
  Decimal('589496063961009.60000000')),
 ('sky',
  'sky',
  'Sky',
  Decimal('23422717430.57867000'),
  Decimal('23459804203.60596000')),
 ('societe-generale-forge-eurcv',
  'eurcv',
  'EUR CoinVertible',
  Decimal('167780470.33000000'),
  Decimal('167780470.33000000')),
 ('sofiusd',
  'sofid',
  'SoFiUSD',
  Decimal('330808795.21000000'),
  Decimal('330808795.21000000')),
 ('solana',
  'sol',
  'Solana',
  Decimal('588075337.52850480'),
  Decimal('635073002.66009330')),
 ('sonic-3',
  's',
  'Sonic',
  Decimal('3885497663.00000000'),
  Decimal('3885497663.00000000')),
 ('spiko-amundi-overnight-swap-fund-eur',
  'eursafo',
  'Spiko Amundi Overnight Swap Fund (EUR)',
  Decimal('1308054511.71820000'),
  Decimal('1308054511.71820000')),
 ('spiko-us-t-bills-money-market-fund',
  'ustbl',
  'Spiko US T-Bills Money Market Fund',
  Decimal('151136231.35884000'),
  Decimal('151136231.35884000')),
 ('spx6900',
  'spx',
  'SPX6900',
  Decimal('930987187.32991340'),
  Decimal('930987187.32991340')),
 ('stonk-3',
  'stonk',
  'STONK',
  Decimal('805851858.97752870'),
  Decimal('805809476.27568080')),
 ('stp-network',
  'awe',
  'AWE Network',
  Decimal('1942420282.52039050'),
  Decimal('1942420282.52039050')),
 ('sun-token',
  'sun',
  'Sun Token',
  Decimal('19222181989.37517000'),
  Decimal('19900730000.00000000')),
 ('superstate-short-duration-us-government-securities-fund-ustb',
  'ustb',
  'Invesco Short Duration US Government Securities Fund',
  Decimal('66776370.81341900'),
  Decimal('66670756.86998900')),
 ('swissborg',
  'borg',
  'SwissBorg',
  Decimal('981352443.44200000'),
  Decimal('981352443.44200000')),
 ('syrup',
  'syrup',
  'Maple Finance',
  Decimal('1167271959.18106770'),
  Decimal('1244677492.51109900')),
 ('tether',
  'usdt',
  'Tether',
  Decimal('184057713983.93323000'),
  Decimal('189524660047.55620000')),
 ('tether-gold',
  'xaut',
  'Tether Gold',
  Decimal('808994.63000000'),
  Decimal('827417.63000000')),
 ('tezos',
  'xtz',
  'Tezos',
  Decimal('1097687388.67757000'),
  Decimal('1117657821.68575400')),
 ('the-graph',
  'grt',
  'The Graph',
  Decimal('10941320353.04391700'),
  Decimal('11612995353.04370000')),
 ('the-sandbox',
  'sand',
  'The Sandbox',
  Decimal('2937639702.37332250'),
  Decimal('3000000000.00000000')),
 ('theta-token',
  'theta',
  'Theta Network',
  Decimal('1000000000.00000000'),
  Decimal('1000000000.00000000')),
 ('thorchain',
  'rune',
  'THORChain',
  Decimal('328591411.00000000'),
  Decimal('353908486.00000000')),
 ('tradable-apac-diversified-finance-provider-sstn',
  'pc0000033',
  'Tradable APAC Diversified Finance Provider SSTN',
  Decimal('162500000.00000000'),
  Decimal('162500000.00000000')),
 ('tradable-na-rent-financing-platform-sstn',
  'pc0000031',
  'Tradable NA Rent Financing Platform SSTN',
  Decimal('202500000.00000000'),
  Decimal('202500000.00000000')),
 ('tron',
  'trx',
  'TRON',
  Decimal('94976612551.82000000'),
  Decimal('94977910377.95780000')),
 ('true-usd',
  'tusd',
  'TrueUSD',
  Decimal('494515083.00000000'),
  Decimal('494515083.00000000')),
 ('united-stables',
  'u',
  'United Stables',
  Decimal('1501671534.63000000'),
  Decimal('1525661534.63000000')),
 ('usa',
  'usat',
  'USAT',
  Decimal('183317585.50000000'),
  Decimal('183317585.50000000')),
 ('usd-coin',
  'usdc',
  'USDC',
  Decimal('74003236641.03654000'),
  Decimal('73996647926.85109000')),
 ('usd1-wlfi',
  'usd1',
  'USD1',
  Decimal('4418501460.43153500'),
  Decimal('4418501460.43153500')),
 ('usdai',
  'usdai',
  'USDai',
  Decimal('345955902.66272795'),
  Decimal('346405645.45521360')),
 ('usdd',
  'usdd',
  'USDD',
  Decimal('1515152604.00000000'),
  Decimal('1514900269.00000000')),
 ('usdgo',
  'usdgo',
  'USDGO',
  Decimal('1194633292.97000000'),
  Decimal('1194633292.97000000')),
 ('usds',
  'usds',
  'USDS',
  Decimal('9946471845.61818900'),
  Decimal('9952236860.55243700')),
 ('usdtb',
  'usdtb',
  'USDtb',
  Decimal('492725712.65618260'),
  Decimal('492725712.65618260')),
 ('useless-3',
  'useless',
  'Useless Coin',
  Decimal('999940362.02000000'),
  Decimal('999940362.02000000')),
 ('usual-usd',
  'usd0',
  'Usual USD',
  Decimal('546721152.88820580'),
  Decimal('546721152.88820580')),
 ('usx',
  'usx',
  'USX',
  Decimal('212858794.54646400'),
  Decimal('212858794.54646400')),
 ('vechain',
  'vet',
  'VeChain',
  Decimal('85985041177.00000000'),
  Decimal('85985041177.00000000')),
 ('vision-3',
  'vsn',
  'Vision',
  Decimal('3795329717.88449400'),
  Decimal('4200000000.00000000')),
 ('ylds',
  'ylds',
  'YLDS',
  Decimal('518877158.33000000'),
  Decimal('518877158.33000000')),
 ('zcash',
  'zec',
  'Zcash',
  Decimal('16960081.41554480'),
  Decimal('16964023.60304480')),
 ('zebec-network',
  'zbcn',
  'Zebec Network',
  Decimal('99998768825.39133000'),
  Decimal('99998768825.39133000'))]

In [26]:
cursor.execute("""
SELECT id, symbol, name, current_price, ath
FROM cryptocurrencies
WHERE current_price >= 0.90 * ath
""")

result = cursor.fetchall()
result

[('agora-dollar', 'ausd', 'AUSD', Decimal('96.110000'), Decimal('96.960000')),
 ('apxusd', 'apxusd', 'apxUSD', Decimal('95.340000'), Decimal('96.950000')),
 ('bfusd', 'bfusd', 'BFUSD', Decimal('96.070000'), Decimal('96.890000')),
 ('bitway', 'btw', 'Bitway', Decimal('138.500000'), Decimal('142.760000')),
 ('blackrock-usd-institutional-digital-liquidity-fund',
  'buidl',
  'BlackRock USD Institutional Digital Liquidity Fund',
  Decimal('96.140000'),
  Decimal('96.900000')),
 ('blockchain-capital',
  'bcap',
  'Blockchain Capital',
  Decimal('10337.420000'),
  Decimal('10360.960000')),
 ('cash-4', 'cash', 'CASH', Decimal('96.090000'), Decimal('96.920000')),
 ('crvusd', 'crvusd', 'crvUSD', Decimal('96.070000'), Decimal('97.040000')),
 ('dai', 'dai', 'Dai', Decimal('96.130000'), Decimal('104.440000')),
 ('ethena-usde',
  'usde',
  'Ethena USDe',
  Decimal('96.110000'),
  Decimal('96.980000')),
 ('euro-coin', 'eurc', 'EURC', Decimal('108.020000'), Decimal('112.720000')),
 ('eutbl',
  'eutbl',
  'Spiko EU T-Bills Money Market Fund',
  Decimal('114.510000'),
  Decimal('118.610000')),
 ('falcon-finance',
  'usdf',
  'Falcon USD',
  Decimal('95.750000'),
  Decimal('96.820000')),
 ('figure-heloc',
  'figr_heloc',
  'Figure Heloc',
  Decimal('98.270000'),
  Decimal('101.840000')),
 ('first-digital-usd',
  'fdusd',
  'First Digital USD',
  Decimal('96.050000'),
  Decimal('100.070000')),
 ('gho', 'gho', 'GHO', Decimal('96.060000'), Decimal('96.870000')),
 ('grx-chain',
  'grx',
  'GRX Chain',
  Decimal('2034.670000'),
  Decimal('2054.340000')),
 ('gusd', 'gusd', 'GUSD', Decimal('95.960000'), Decimal('96.840000')),
 ('hashnote-usyc',
  'usyc',
  'Circle USYC',
  Decimal('109.500000'),
  Decimal('109.750000')),
 ('hyperliquid',
  'hype',
  'Hyperliquid',
  Decimal('8742.110000'),
  Decimal('9368.500000')),
 ('janus-henderson-anemoy-aaa-clo-fund',
  'jaaa',
  'Janus Henderson Anemoy AAA CLO Fund',
  Decimal('100.990000'),
  Decimal('101.200000')),
 ('janus-henderson-anemoy-treasury-fund',
  'jtrsy',
  'Janus Henderson Anemoy Treasury Fund',
  Decimal('107.470000'),
  Decimal('107.700000')),
 ('ondo-us-dollar-yield',
  'usdy',
  'Ondo US Dollar Yield',
  Decimal('110.140000'),
  Decimal('110.700000')),
 ('open-usd', 'ousd', 'Open USD', Decimal('96.110000'), Decimal('96.330000')),
 ('ousg',
  'ousg',
  'Ondo Short-Term U.S. Government Bond Fund',
  Decimal('11224.280000'),
  Decimal('11248.650000')),
 ('paypal-usd',
  'pyusd',
  'PayPal USD',
  Decimal('96.140000'),
  Decimal('96.970000')),
 ('re-protocol-reusd',
  'reusd',
  'Re Protocol reUSD',
  Decimal('106.160000'),
  Decimal('106.430000')),
 ('ripple-usd',
  'rlusd',
  'Ripple USD',
  Decimal('96.140000'),
  Decimal('97.010000')),
 ('safo',
  'safo',
  'Spiko Amundi Overnight Swap Fund',
  Decimal('98.320000'),
  Decimal('98.530000')),
 ('sky', 'sky', 'Sky', Decimal('8.530000'), Decimal('8.760000')),
 ('societe-generale-forge-eurcv',
  'eurcv',
  'EUR CoinVertible',
  Decimal('108.020000'),
  Decimal('112.960000')),
 ('sofiusd', 'sofid', 'SoFiUSD', Decimal('95.980000'), Decimal('96.820000')),
 ('spiko-amundi-overnight-swap-fund-eur',
  'eursafo',
  'Spiko Amundi Overnight Swap Fund (EUR)',
  Decimal('109.530000'),
  Decimal('113.390000')),
 ('spiko-us-t-bills-money-market-fund',
  'ustbl',
  'Spiko US T-Bills Money Market Fund',
  Decimal('105.530000'),
  Decimal('105.780000')),
 ('superstate-short-duration-us-government-securities-fund-ustb',
  'ustb',
  'Invesco Short Duration US Government Securities Fund',
  Decimal('1079.590000'),
  Decimal('1082.050000')),
 ('tether', 'usdt', 'Tether', Decimal('96.110000'), Decimal('105.520000')),
 ('tradable-apac-diversified-finance-provider-sstn',
  'pc0000033',
  'Tradable APAC Diversified Finance Provider SSTN',
  Decimal('96.140000'),
  Decimal('96.900000')),
 ('united-stables',
  'u',
  'United Stables',
  Decimal('96.060000'),
  Decimal('96.990000')),
 ('usa', 'usat', 'USAT', Decimal('96.070000'), Decimal('96.940000')),
 ('usd-coin', 'usdc', 'USDC', Decimal('96.120000'), Decimal('96.990000')),
 ('usd1-wlfi', 'usd1', 'USD1', Decimal('96.090000'), Decimal('100.020000')),
 ('usdai', 'usdai', 'USDai', Decimal('96.180000'), Decimal('104.920000')),
 ('usdgo', 'usdgo', 'USDGO', Decimal('96.140000'), Decimal('97.010000')),
 ('usds', 'usds', 'USDS', Decimal('96.110000'), Decimal('96.980000')),
 ('usdtb', 'usdtb', 'USDtb', Decimal('96.130000'), Decimal('96.910000')),
 ('whitebit',
  'wbt',
  'WhiteBIT Coin',
  Decimal('8268.660000'),
  Decimal('8421.200000')),
 ('ylds', 'ylds', 'YLDS', Decimal('96.120000'), Decimal('96.990000'))]

In [27]:
cursor.execute("""
SELECT AVG(market_cap_rank) AS average_market_cap_rank
FROM cryptocurrencies
WHERE total_volume > 1000000000
""")

result = cursor.fetchall()
result

[(Decimal('102.3816'),)]

In [28]:
cursor.execute("""
SELECT id, symbol, name, date
FROM cryptocurrencies
ORDER BY date DESC
LIMIT 1
""")

result = cursor.fetchall()
result

[('1inch', '1inch', '1INCH', datetime.date(2026, 10, 2))]

Crypto Prices

In [29]:
cursor.execute("""
SELECT MAX(price_usd) AS highest_bitcoin_price
FROM crypto_prices
WHERE coin_id = 'bitcoin'
AND date >= CURDATE() - INTERVAL 365 DAY
""")

result = cursor.fetchall()
result

[(Decimal('124739.810888'),)]

In [30]:
cursor.execute("""
SELECT AVG(price_usd) AS average_ethereum_price
FROM crypto_prices
WHERE coin_id = 'ethereum'
AND date >= CURDATE() - INTERVAL 1 YEAR
""")

result = cursor.fetchall()
result

[(Decimal('2513.8916251148'),)]

In [32]:
cursor.execute("""
SELECT date, price_usd
FROM crypto_prices
WHERE coin_id = 'bitcoin'
AND date BETWEEN '2025-01-01' AND '2025-01-31'
ORDER BY date
""")

result = cursor.fetchall()
result

[]

In [33]:
cursor.execute("""
SELECT coin_id, AVG(price_usd) AS average_price
FROM crypto_prices
WHERE date >= CURDATE() - INTERVAL 1 YEAR
GROUP BY coin_id
ORDER BY average_price DESC
LIMIT 1
""")

result = cursor.fetchall()
result

[('bitcoin', Decimal('79730.2711809399'))]

In [34]:
cursor.execute("""
SELECT
(
    (
        AVG(CASE
            WHEN date BETWEEN '2025-09-01' AND '2025-09-30'
            THEN price_usd
        END)
        -
        AVG(CASE
            WHEN date BETWEEN '2024-09-01' AND '2024-09-30'
            THEN price_usd
        END)
    )
    /
    AVG(CASE
        WHEN date BETWEEN '2024-09-01' AND '2024-09-30'
        THEN price_usd
    END)
) * 100 AS percentage_change
FROM crypto_prices
WHERE coin_id = 'bitcoin'
AND date BETWEEN '2024-09-01' AND '2025-09-30'
""")

result = cursor.fetchall()
result

[(None,)]

Oil Prices

In [35]:
cursor.execute("""
SELECT MAX(price_usd) AS highest_oil_price
FROM oil_prices
WHERE date >= CURDATE() - INTERVAL 5 YEAR
""")

result = cursor.fetchall()
result

[(Decimal('123.640000'),)]

In [36]:
cursor.execute("""
SELECT
    YEAR(date) AS year,
    AVG(price_usd) AS average_oil_price
FROM oil_prices
GROUP BY YEAR(date)
ORDER BY year
""")

result = cursor.fetchall()
result

[(1986, Decimal('15.0837885463')),
 (1987, Decimal('19.2088655462')),
 (1988, Decimal('15.9740316206')),
 (1989, Decimal('19.6516393443')),
 (1990, Decimal('24.5337647059')),
 (1991, Decimal('21.5562698413')),
 (1992, Decimal('20.5913654618')),
 (1993, Decimal('18.4721338912')),
 (1994, Decimal('17.3053554502')),
 (1995, Decimal('18.4469955157')),
 (1996, Decimal('21.9293434343')),
 (1997, Decimal('20.5198522167')),
 (1998, Decimal('14.4320614035')),
 (1999, Decimal('18.8439393939')),
 (2000, Decimal('30.4536818182')),
 (2001, Decimal('26.1396052632')),
 (2002, Decimal('26.3847598253')),
 (2003, Decimal('31.3374820144')),
 (2004, Decimal('42.4611351351')),
 (2005, Decimal('56.4537254902')),
 (2006, Decimal('66.0491150442')),
 (2007, Decimal('72.5503629032')),
 (2008, Decimal('99.6715019763')),
 (2009, Decimal('62.0102000000')),
 (2010, Decimal('79.4757142857')),
 (2011, Decimal('93.9063207547')),
 (2012, Decimal('94.0533333333')),
 (2013, Decimal('97.9920000000')),
 (2014, Decimal('93.5218548387')),
 (2015, Decimal('48.7304098361')),
 (2016, Decimal('43.2936507937')),
 (2017, Decimal('50.8003200000')),
 (2018, Decimal('65.2274698795')),
 (2019, Decimal('56.9883200000')),
 (2020, Decimal('39.1604365079')),
 (2021, Decimal('68.1350996016')),
 (2022, Decimal('94.9028685259')),
 (2023, Decimal('77.5765322581')),
 (2024, Decimal('76.6322400000')),
 (2025, Decimal('65.3881048387')),
 (2026, Decimal('85.1897849462'))]

In [37]:
cursor.execute("""
SELECT date, price_usd
FROM oil_prices
WHERE date BETWEEN '2020-03-01' AND '2020-04-30'
ORDER BY date
""")

result = cursor.fetchall()
result

[(datetime.date(2020, 3, 2), Decimal('46.780000')),
 (datetime.date(2020, 3, 3), Decimal('47.270000')),
 (datetime.date(2020, 3, 4), Decimal('46.780000')),
 (datetime.date(2020, 3, 5), Decimal('45.900000')),
 (datetime.date(2020, 3, 6), Decimal('41.140000')),
 (datetime.date(2020, 3, 9), Decimal('31.050000')),
 (datetime.date(2020, 3, 10), Decimal('34.470000')),
 (datetime.date(2020, 3, 11), Decimal('33.130000')),
 (datetime.date(2020, 3, 12), Decimal('31.560000')),
 (datetime.date(2020, 3, 13), Decimal('31.720000')),
 (datetime.date(2020, 3, 16), Decimal('28.960000')),
 (datetime.date(2020, 3, 17), Decimal('26.960000')),
 (datetime.date(2020, 3, 18), Decimal('20.480000')),
 (datetime.date(2020, 3, 19), Decimal('25.090000')),
 (datetime.date(2020, 3, 20), Decimal('19.480000')),
 (datetime.date(2020, 3, 23), Decimal('23.330000')),
 (datetime.date(2020, 3, 24), Decimal('21.030000')),
 (datetime.date(2020, 3, 25), Decimal('20.750000')),
 (datetime.date(2020, 3, 26), Decimal('16.600000')),
 (datetime.date(2020, 3, 27), Decimal('15.480000')),
 (datetime.date(2020, 3, 30), Decimal('14.100000')),
 (datetime.date(2020, 3, 31), Decimal('20.510000')),
 (datetime.date(2020, 4, 1), Decimal('20.280000')),
 (datetime.date(2020, 4, 2), Decimal('25.180000')),
 (datetime.date(2020, 4, 3), Decimal('28.360000')),
 (datetime.date(2020, 4, 6), Decimal('26.210000')),
 (datetime.date(2020, 4, 7), Decimal('23.540000')),
 (datetime.date(2020, 4, 8), Decimal('24.970000')),
 (datetime.date(2020, 4, 9), Decimal('22.900000')),
 (datetime.date(2020, 4, 13), Decimal('22.360000')),
 (datetime.date(2020, 4, 14), Decimal('20.150000')),
 (datetime.date(2020, 4, 15), Decimal('19.960000')),
 (datetime.date(2020, 4, 16), Decimal('19.820000')),
 (datetime.date(2020, 4, 17), Decimal('18.310000')),
 (datetime.date(2020, 4, 20), Decimal('-36.980000')),
 (datetime.date(2020, 4, 21), Decimal('8.910000')),
 (datetime.date(2020, 4, 22), Decimal('13.640000')),
 (datetime.date(2020, 4, 23), Decimal('15.060000')),
 (datetime.date(2020, 4, 24), Decimal('15.990000')),
 (datetime.date(2020, 4, 27), Decimal('12.170000')),
 (datetime.date(2020, 4, 28), Decimal('12.400000')),
 (datetime.date(2020, 4, 29), Decimal('15.040000')),
 (datetime.date(2020, 4, 30), Decimal('19.230000'))]

In [38]:
cursor.execute("""
SELECT MIN(price_usd) AS lowest_oil_price
FROM oil_prices
WHERE date >= CURDATE() - INTERVAL 10 YEAR
""")

result = cursor.fetchall()
result

[(Decimal('-36.980000'),)]

In [39]:
cursor.execute("""
SELECT
    YEAR(date) AS year,
    MAX(price_usd) - MIN(price_usd) AS volatility
FROM oil_prices
GROUP BY YEAR(date)
ORDER BY year
""")

result = cursor.fetchall()
result

[(1986, Decimal('16.280000')),
 (1987, Decimal('7.320000')),
 (1988, Decimal('5.960000')),
 (1989, Decimal('7.630000')),
 (1990, Decimal('25.640000')),
 (1991, Decimal('14.820000')),
 (1992, Decimal('5.080000')),
 (1993, Decimal('6.760000')),
 (1994, Decimal('6.830000')),
 (1995, Decimal('3.670000')),
 (1996, Decimal('9.220000')),
 (1997, Decimal('8.950000')),
 (1998, Decimal('7.110000')),
 (1999, Decimal('16.650000')),
 (2000, Decimal('13.310000')),
 (2001, Decimal('14.710000')),
 (2002, Decimal('14.660000')),
 (2003, Decimal('12.640000')),
 (2004, Decimal('23.880000')),
 (2005, Decimal('27.340000')),
 (2006, Decimal('21.150000')),
 (2007, Decimal('48.650000')),
 (2008, Decimal('115.030000')),
 (2009, Decimal('47.000000')),
 (2010, Decimal('26.700000')),
 (2011, Decimal('37.630000')),
 (2012, Decimal('31.670000')),
 (2013, Decimal('23.970000')),
 (2014, Decimal('54.500000')),
 (2015, Decimal('26.810000')),
 (2016, Decimal('27.820000')),
 (2017, Decimal('17.980000')),
 (2018, Decimal('32.930000')),
 (2019, Decimal('19.930000')),
 (2020, Decimal('100.250000')),
 (2021, Decimal('38.170000')),
 (2022, Decimal('52.590000')),
 (2023, Decimal('27.060000')),
 (2024, Decimal('20.960000')),
 (2025, Decimal('25.290000')),
 (2026, Decimal('58.570000'))]

Stock Prices

In [40]:
cursor.execute("""
SELECT *
FROM stock_prices
WHERE ticker = '^GSPC'
ORDER BY date
""")

result = cursor.fetchall()
result

[(datetime.date(2020, 1, 1), None, None, None, None, None, '^GSPC'),
 (datetime.date(2020, 1, 2),
  Decimal('3244.669922'),
  Decimal('3258.139893'),
  Decimal('3235.530029'),
  Decimal('3257.850098'),
  3459930000,
  '^GSPC'),
 (datetime.date(2020, 1, 3),
  Decimal('3226.360107'),
  Decimal('3246.149902'),
  Decimal('3222.340088'),
  Decimal('3234.850098'),
  3484700000,
  '^GSPC'),
 (datetime.date(2020, 1, 6),
  Decimal('3217.550049'),
  Decimal('3246.840088'),
  Decimal('3214.639893'),
  Decimal('3246.280029'),
  3702460000,
  '^GSPC'),
 (datetime.date(2020, 1, 7),
  Decimal('3241.860107'),
  Decimal('3244.909912'),
  Decimal('3232.429932'),
  Decimal('3237.179932'),
  3435910000,
  '^GSPC'),
 (datetime.date(2020, 1, 8),
  Decimal('3238.590088'),
  Decimal('3267.070068'),
  Decimal('3236.669922'),
  Decimal('3253.050049'),
  3726840000,
  '^GSPC'),
 (datetime.date(2020, 1, 9),
  Decimal('3266.030029'),
  Decimal('3275.580078'),
  Decimal('3263.669922'),
  Decimal('3274.699951'),
  3641230000,
  '^GSPC'),
 (datetime.date(2020, 1, 10),
  Decimal('3281.810059'),
  Decimal('3282.989990'),
  Decimal('3260.860107'),
  Decimal('3265.350098'),
  3214580000,
  '^GSPC'),
 (datetime.date(2020, 1, 13),
  Decimal('3271.129883'),
  Decimal('3288.129883'),
  Decimal('3268.429932'),
  Decimal('3288.129883'),
  3459390000,
  '^GSPC'),
 (datetime.date(2020, 1, 14),
  Decimal('3285.350098'),
  Decimal('3294.250000'),
  Decimal('3277.189941'),
  Decimal('3283.149902'),
  3687620000,
  '^GSPC'),
 (datetime.date(2020, 1, 15),
  Decimal('3282.270020'),
  Decimal('3298.659912'),
  Decimal('3280.689941'),
  Decimal('3289.290039'),
  3721490000,
  '^GSPC'),
 (datetime.date(2020, 1, 16),
  Decimal('3302.969971'),
  Decimal('3317.110107'),
  Decimal('3302.820068'),
  Decimal('3316.810059'),
  3540580000,
  '^GSPC'),
 (datetime.date(2020, 1, 17),
  Decimal('3323.659912'),
  Decimal('3329.879883'),
  Decimal('3318.860107'),
  Decimal('3329.620117'),
  3726220000,
  '^GSPC'),
 (datetime.date(2020, 1, 20), None, None, None, None, None, '^GSPC'),
 (datetime.date(2020, 1, 21),
  Decimal('3321.030029'),
  Decimal('3329.790039'),
  Decimal('3316.610107'),
  Decimal('3320.790039'),
  4104840000,
  '^GSPC'),
 (datetime.date(2020, 1, 22),
  Decimal('3330.020020'),
  Decimal('3337.770020'),
  Decimal('3320.040039'),
  Decimal('3321.750000'),
  3623780000,
  '^GSPC'),
 (datetime.date(2020, 1, 23),
  Decimal('3315.770020'),
  Decimal('3326.879883'),
  Decimal('3301.870117'),
  Decimal('3325.540039'),
  3766710000,
  '^GSPC'),
 (datetime.date(2020, 1, 24),
  Decimal('3333.100098'),
  Decimal('3333.179932'),
  Decimal('3281.530029'),
  Decimal('3295.469971'),
  3708780000,
  '^GSPC'),
 (datetime.date(2020, 1, 27),
  Decimal('3247.159912'),
  Decimal('3258.850098'),
  Decimal('3234.500000'),
  Decimal('3243.629883'),
  3831050000,
  '^GSPC'),
 (datetime.date(2020, 1, 28),
  Decimal('3255.350098'),
  Decimal('3285.780029'),
  Decimal('3253.219971'),
  Decimal('3276.239990'),
  3531570000,
  '^GSPC'),
 (datetime.date(2020, 1, 29),
  Decimal('3289.459961'),
  Decimal('3293.469971'),
  Decimal('3271.889893'),
  Decimal('3273.399902'),
  3600250000,
  '^GSPC'),
 (datetime.date(2020, 1, 30),
  Decimal('3256.449951'),
  Decimal('3285.909912'),
  Decimal('3242.800049'),
  Decimal('3283.659912'),
  3790350000,
  '^GSPC'),
 (datetime.date(2020, 1, 31),
  Decimal('3282.330078'),
  Decimal('3282.330078'),
  Decimal('3214.679932'),
  Decimal('3225.520020'),
  4529700000,
  '^GSPC'),
 (datetime.date(2020, 2, 3),
  Decimal('3235.659912'),
  Decimal('3268.439941'),
  Decimal('3235.659912'),
  Decimal('3248.919922'),
  3760460000,
  '^GSPC'),
 (datetime.date(2020, 2, 4),
  Decimal('3280.610107'),
  Decimal('3306.919922'),
  Decimal('3280.610107'),
  Decimal('3297.590088'),
  3996900000,
  '^GSPC'),
 (datetime.date(2020, 2, 5),
  Decimal('3324.909912'),
  Decimal('3337.580078'),
  Decimal('3313.750000'),
  Decimal('3334.689941'),
  4121480000,
  '^GSPC'),
 (datetime.date(2020, 2, 6),
  Decimal('3344.919922'),
  Decimal('3347.959961'),
  Decimal('3334.389893'),
  Decimal('3345.780029'),
  3887250000,
  '^GSPC'),
 (datetime.date(2020, 2, 7),
  Decimal('3335.540039'),
  Decimal('3341.419922'),
  Decimal('3322.120117'),
  Decimal('3327.709961'),
  3733920000,
  '^GSPC'),
 (datetime.date(2020, 2, 10),
  Decimal('3318.280029'),
  Decimal('3352.260010'),
  Decimal('3317.770020'),
  Decimal('3352.090088'),
  3462730000,
  '^GSPC'),
 (datetime.date(2020, 2, 11),
  Decimal('3365.870117'),
  Decimal('3375.629883'),
  Decimal('3352.719971'),
  Decimal('3357.750000'),
  3762940000,
  '^GSPC'),
 (datetime.date(2020, 2, 12),
  Decimal('3370.500000'),
  Decimal('3381.469971'),
  Decimal('3369.719971'),
  Decimal('3379.449951'),
  3930910000,
  '^GSPC'),
 (datetime.date(2020, 2, 13),
  Decimal('3365.899902'),
  Decimal('3385.090088'),
  Decimal('3360.520020'),
  Decimal('3373.939941'),
  3500890000,
  '^GSPC'),
 (datetime.date(2020, 2, 14),
  Decimal('3378.080078'),
  Decimal('3380.689941'),
  Decimal('3366.149902'),
  Decimal('3380.159912'),
  3419700000,
  '^GSPC'),
 (datetime.date(2020, 2, 17), None, None, None, None, None, '^GSPC'),
 (datetime.date(2020, 2, 18),
  Decimal('3369.040039'),
  Decimal('3375.010010'),
  Decimal('3355.610107'),
  Decimal('3370.290039'),
  3750400000,
  '^GSPC'),
 (datetime.date(2020, 2, 19),
  Decimal('3380.389893'),
  Decimal('3393.520020'),
  Decimal('3378.830078'),
  Decimal('3386.149902'),
  3614200000,
  '^GSPC'),
 (datetime.date(2020, 2, 20),
  Decimal('3380.449951'),
  Decimal('3389.149902'),
  Decimal('3341.020020'),
  Decimal('3373.229980'),
  4019180000,
  '^GSPC'),
 (datetime.date(2020, 2, 21),
  Decimal('3360.500000'),
  Decimal('3360.760010'),
  Decimal('3328.449951'),
  Decimal('3337.750000'),
  3908780000,
  '^GSPC'),
 (datetime.date(2020, 2, 24),
  Decimal('3257.610107'),
  Decimal('3259.810059'),
  Decimal('3214.649902'),
  Decimal('3225.889893'),
  4851160000,
  '^GSPC'),
 (datetime.date(2020, 2, 25),
  Decimal('3238.939941'),
  Decimal('3246.989990'),
  Decimal('3118.770020'),
  Decimal('3128.209961'),
  5596760000,
  '^GSPC'),
 (datetime.date(2020, 2, 26),
  Decimal('3139.899902'),
  Decimal('3182.510010'),
  Decimal('3108.989990'),
  Decimal('3116.389893'),
  5484650000,
  '^GSPC'),
 (datetime.date(2020, 2, 27),
  Decimal('3062.540039'),
  Decimal('3097.070068'),
  Decimal('2977.389893'),
  Decimal('2978.760010'),
  7064710000,
  '^GSPC'),
 (datetime.date(2020, 2, 28),
  Decimal('2916.899902'),
  Decimal('2959.719971'),
  Decimal('2855.840088'),
  Decimal('2954.219971'),
  8569570000,
  '^GSPC'),
 (datetime.date(2020, 3, 2),
  Decimal('2974.280029'),
  Decimal('3090.959961'),
  Decimal('2945.189941'),
  Decimal('3090.229980'),
  6381330000,
  '^GSPC'),
 (datetime.date(2020, 3, 3),
  Decimal('3096.459961'),
  Decimal('3136.719971'),
  Decimal('2976.629883'),
  Decimal('3003.370117'),
  6376510000,
  '^GSPC'),
 (datetime.date(2020, 3, 4),
  Decimal('3045.750000'),
  Decimal('3130.969971'),
  Decimal('3034.379883'),
  Decimal('3130.120117'),
  5073020000,
  '^GSPC'),
 (datetime.date(2020, 3, 5),
  Decimal('3075.699951'),
  Decimal('3083.040039'),
  Decimal('2999.830078'),
  Decimal('3023.939941'),
  5579290000,
  '^GSPC'),
 (datetime.date(2020, 3, 6),
  Decimal('2954.199951'),
  Decimal('2985.929932'),
  Decimal('2901.540039'),
  Decimal('2972.370117'),
  6555240000,
  '^GSPC'),
 (datetime.date(2020, 3, 9),
  Decimal('2863.889893'),
  Decimal('2863.889893'),
  Decimal('2734.429932'),
  Decimal('2746.560059'),
  8441290000,
  '^GSPC'),
 (datetime.date(2020, 3, 10),
  Decimal('2813.479980'),
  Decimal('2882.590088'),
  Decimal('2734.000000'),
  Decimal('2882.229980'),
  7642040000,
  '^GSPC'),
 (datetime.date(2020, 3, 11),
  Decimal('2825.600098'),
  Decimal('2825.600098'),
  Decimal('2707.219971'),
  Decimal('2741.379883'),
  7431200000,
  '^GSPC'),
 (datetime.date(2020, 3, 12),
  Decimal('2630.860107'),
  Decimal('2660.949951'),
  Decimal('2478.860107'),
  Decimal('2480.639893'),
  8850810000,
  '^GSPC'),
 (datetime.date(2020, 3, 13),
  Decimal('2569.989990'),
  Decimal('2711.330078'),
  Decimal('2492.370117'),
  Decimal('2711.020020'),
  8299070000,
  '^GSPC'),
 (datetime.date(2020, 3, 16),
  Decimal('2508.590088'),
  Decimal('2562.979980'),
  Decimal('2380.939941'),
  Decimal('2386.129883'),
  7805450000,
  '^GSPC'),
 (datetime.date(2020, 3, 17),
  Decimal('2425.659912'),
  Decimal('2553.929932'),
  Decimal('2367.040039'),
  Decimal('2529.189941'),
  8370250000,
  '^GSPC'),
 (datetime.date(2020, 3, 18),
  Decimal('2436.500000'),
  Decimal('2453.570068'),
  Decimal('2280.520020'),
  Decimal('2398.100098'),
  8799300000,
  '^GSPC'),
 (datetime.date(2020, 3, 19),
  Decimal('2393.479980'),
  Decimal('2466.969971'),
  Decimal('2319.780029'),
  Decimal('2409.389893'),
  7956100000,
  '^GSPC'),
 (datetime.date(2020, 3, 20),
  Decimal('2431.939941'),
  Decimal('2453.010010'),
  Decimal('2295.560059'),
  Decimal('2304.919922'),
  9053950000,
  '^GSPC'),
 (datetime.date(2020, 3, 23),
  Decimal('2290.709961'),
  Decimal('2300.729980'),
  Decimal('2191.860107'),
  Decimal('2237.399902'),
  7411380000,
  '^GSPC'),
 (datetime.date(2020, 3, 24),
  Decimal('2344.439941'),
  Decimal('2449.709961'),
  Decimal('2344.439941'),
  Decimal('2447.330078'),
  7563150000,
  '^GSPC'),
 (datetime.date(2020, 3, 25),
  Decimal('2457.770020'),
  Decimal('2571.419922'),
  Decimal('2407.530029'),
  Decimal('2475.560059'),
  8300010000,
  '^GSPC'),
 (datetime.date(2020, 3, 26),
  Decimal('2501.290039'),
  Decimal('2637.010010'),
  Decimal('2500.719971'),
  Decimal('2630.070068'),
  7766990000,
  '^GSPC'),
 (datetime.date(2020, 3, 27),
  Decimal('2555.870117'),
  Decimal('2615.909912'),
  Decimal('2520.020020'),
  Decimal('2541.469971'),
  6201670000,
  '^GSPC'),
 (datetime.date(2020, 3, 30),
  Decimal('2558.979980'),
  Decimal('2631.800049'),
  Decimal('2545.280029'),
  Decimal('2626.649902'),
  5751120000,
  '^GSPC'),
 (datetime.date(2020, 3, 31),
  Decimal('2614.689941'),
  Decimal('2641.389893'),
  Decimal('2571.149902'),
  Decimal('2584.590088'),
  6576210000,
  '^GSPC'),
 (datetime.date(2020, 4, 1),
  Decimal('2498.080078'),
  Decimal('2522.750000'),
  Decimal('2447.489990'),
  Decimal('2470.500000'),
  5964000000,
  '^GSPC'),
 (datetime.date(2020, 4, 2),
  Decimal('2458.540039'),
  Decimal('2533.219971'),
  Decimal('2455.790039'),
  Decimal('2526.899902'),
  6464190000,
  '^GSPC'),
 (datetime.date(2020, 4, 3),
  Decimal('2514.919922'),
  Decimal('2538.179932'),
  Decimal('2459.959961'),
  Decimal('2488.649902'),
  6096970000,
  '^GSPC'),
 (datetime.date(2020, 4, 6),
  Decimal('2578.280029'),
  Decimal('2676.850098'),
  Decimal('2574.570068'),
  Decimal('2663.679932'),
  6403840000,
  '^GSPC'),
 (datetime.date(2020, 4, 7),
  Decimal('2738.649902'),
  Decimal('2756.889893'),
  Decimal('2657.669922'),
  Decimal('2659.409912'),
  7050410000,
  '^GSPC'),
 (datetime.date(2020, 4, 8),
  Decimal('2685.000000'),
  Decimal('2760.750000'),
  Decimal('2663.300049'),
  Decimal('2749.979980'),
  5875710000,
  '^GSPC'),
 (datetime.date(2020, 4, 9),
  Decimal('2776.989990'),
  Decimal('2818.570068'),
  Decimal('2762.360107'),
  Decimal('2789.820068'),
  7899550000,
  '^GSPC'),
 (datetime.date(2020, 4, 13),
  Decimal('2782.459961'),
  Decimal('2782.459961'),
  Decimal('2721.169922'),
  Decimal('2761.629883'),
  5319530000,
  '^GSPC'),
 (datetime.date(2020, 4, 14),
  Decimal('2805.100098'),
  Decimal('2851.850098'),
  Decimal('2805.100098'),
  Decimal('2846.060059'),
  5615730000,
  '^GSPC'),
 (datetime.date(2020, 4, 15),
  Decimal('2795.639893'),
  Decimal('2801.879883'),
  Decimal('2761.540039'),
  Decimal('2783.360107'),
  5208000000,
  '^GSPC'),
 (datetime.date(2020, 4, 16),
  Decimal('2799.340088'),
  Decimal('2806.510010'),
  Decimal('2764.320068'),
  Decimal('2799.550049'),
  5228810000,
  '^GSPC'),
 (datetime.date(2020, 4, 17),
  Decimal('2842.429932'),
  Decimal('2879.219971'),
  Decimal('2830.879883'),
  Decimal('2874.560059'),
  5804810000,
  '^GSPC'),
 (datetime.date(2020, 4, 20),
  Decimal('2845.620117'),
  Decimal('2868.979980'),
  Decimal('2820.429932'),
  Decimal('2823.159912'),
  5228630000,
  '^GSPC'),
 (datetime.date(2020, 4, 21),
  Decimal('2784.810059'),
  Decimal('2785.540039'),
  Decimal('2727.100098'),
  Decimal('2736.560059'),
  5121010000,
  '^GSPC'),
 (datetime.date(2020, 4, 22),
  Decimal('2787.889893'),
  Decimal('2815.100098'),
  Decimal('2775.949951'),
  Decimal('2799.310059'),
  5084920000,
  '^GSPC'),
 (datetime.date(2020, 4, 23),
  Decimal('2810.419922'),
  Decimal('2844.899902'),
  Decimal('2794.260010'),
  Decimal('2797.800049'),
  5773530000,
  '^GSPC'),
 (datetime.date(2020, 4, 24),
  Decimal('2812.639893'),
  Decimal('2842.709961'),
  Decimal('2791.760010'),
  Decimal('2836.739990'),
  5382810000,
  '^GSPC'),
 (datetime.date(2020, 4, 27),
  Decimal('2854.649902'),
  Decimal('2887.719971'),
  Decimal('2852.889893'),
  Decimal('2878.479980'),
  5203930000,
  '^GSPC'),
 (datetime.date(2020, 4, 28),
  Decimal('2909.959961'),
  Decimal('2921.149902'),
  Decimal('2860.709961'),
  Decimal('2863.389893'),
  5691160000,
  '^GSPC'),
 (datetime.date(2020, 4, 29),
  Decimal('2918.459961'),
  Decimal('2954.860107'),
  Decimal('2912.159912'),
  Decimal('2939.510010'),
  6645640000,
  '^GSPC'),
 (datetime.date(2020, 4, 30),
  Decimal('2930.909912'),
  Decimal('2930.909912'),
  Decimal('2892.469971'),
  Decimal('2912.429932'),
  6544980000,
  '^GSPC'),
 (datetime.date(2020, 5, 1),
  Decimal('2869.090088'),
  Decimal('2869.090088'),
  Decimal('2821.610107'),
  Decimal('2830.709961'),
  4759810000,
  '^GSPC'),
 (datetime.date(2020, 5, 4),
  Decimal('2815.010010'),
  Decimal('2844.239990'),
  Decimal('2797.850098'),
  Decimal('2842.739990'),
  4735930000,
  '^GSPC'),
 (datetime.date(2020, 5, 5),
  Decimal('2868.879883'),
  Decimal('2898.229980'),
  Decimal('2863.550049'),
  Decimal('2868.439941'),
  5140290000,
  '^GSPC'),
 (datetime.date(2020, 5, 6),
  Decimal('2883.139893'),
  Decimal('2891.110107'),
  Decimal('2847.649902'),
  Decimal('2848.419922'),
  4892570000,
  '^GSPC'),
 (datetime.date(2020, 5, 7),
  Decimal('2878.260010'),
  Decimal('2901.919922'),
  Decimal('2876.479980'),
  Decimal('2881.189941'),
  5178790000,
  '^GSPC'),
 (datetime.date(2020, 5, 8),
  Decimal('2908.830078'),
  Decimal('2932.159912'),
  Decimal('2902.879883'),
  Decimal('2929.800049'),
  4876030000,
  '^GSPC'),
 (datetime.date(2020, 5, 11),
  Decimal('2915.459961'),
  Decimal('2944.250000'),
  Decimal('2903.439941'),
  Decimal('2930.189941'),
  4819730000,
  '^GSPC'),
 (datetime.date(2020, 5, 12),
  Decimal('2939.500000'),
  Decimal('2945.820068'),
  Decimal('2869.590088'),
  Decimal('2870.120117'),
  5119630000,
  '^GSPC'),
 (datetime.date(2020, 5, 13),
  Decimal('2865.860107'),
  Decimal('2874.139893'),
  Decimal('2793.149902'),
  Decimal('2820.000000'),
  6151650000,
  '^GSPC'),
 (datetime.date(2020, 5, 14),
  Decimal('2794.540039'),
  Decimal('2852.800049'),
  Decimal('2766.639893'),
  Decimal('2852.500000'),
  5651130000,
  '^GSPC'),
 (datetime.date(2020, 5, 15),
  Decimal('2829.949951'),
  Decimal('2865.010010'),
  Decimal('2816.780029'),
  Decimal('2863.699951'),
  5507700000,
  '^GSPC'),
 (datetime.date(2020, 5, 18),
  Decimal('2913.860107'),
  Decimal('2968.090088'),
  Decimal('2913.860107'),
  Decimal('2953.909912'),
  6373670000,
  '^GSPC'),
 (datetime.date(2020, 5, 19),
  Decimal('2948.590088'),
  Decimal('2964.209961'),
  Decimal('2922.350098'),
  Decimal('2922.939941'),
  4984330000,
  '^GSPC'),
 (datetime.date(2020, 5, 20),
  Decimal('2953.629883'),
  Decimal('2980.290039'),
  Decimal('2953.629883'),
  Decimal('2971.610107'),
  5005380000,
  '^GSPC'),
 (datetime.date(2020, 5, 21),
  Decimal('2969.949951'),
  Decimal('2978.500000'),
  Decimal('2938.570068'),
  Decimal('2948.510010'),
  4976620000,
  '^GSPC'),
 (datetime.date(2020, 5, 22),
  Decimal('2948.050049'),
  Decimal('2956.760010'),
  Decimal('2933.590088'),
  Decimal('2955.449951'),
  3970860000,
  '^GSPC'),
 (datetime.date(2020, 5, 26),
  Decimal('3004.080078'),
  Decimal('3021.719971'),
  Decimal('2988.169922'),
  Decimal('2991.770020'),
  5848500000,
  '^GSPC'),
 (datetime.date(2020, 5, 27),
  Decimal('3015.649902'),
  Decimal('3036.250000'),
  Decimal('2969.750000'),
  Decimal('3036.129883'),
  6398000000,
  '^GSPC'),
 (datetime.date(2020, 5, 28),
  Decimal('3046.610107'),
  Decimal('3068.669922'),
  Decimal('3023.399902'),
  Decimal('3029.729980'),
  5447020000,
  '^GSPC'),
 (datetime.date(2020, 5, 29),
  Decimal('3025.169922'),
  Decimal('3049.169922'),
  Decimal('2998.610107'),
  Decimal('3044.310059'),
  7297550000,
  '^GSPC'),
 (datetime.date(2020, 6, 1),
  Decimal('3038.780029'),
  Decimal('3062.179932'),
  Decimal('3031.540039'),
  Decimal('3055.729980'),
  4684170000,
  '^GSPC'),
 (datetime.date(2020, 6, 2),
  Decimal('3064.780029'),
  Decimal('3081.070068'),
  Decimal('3051.639893'),
  Decimal('3080.820068'),
  5197150000,
  '^GSPC'),
 (datetime.date(2020, 6, 3),
  Decimal('3098.899902'),
  Decimal('3130.939941'),
  Decimal('3098.899902'),
  Decimal('3122.870117'),
  6005560000,
  '^GSPC'),
 (datetime.date(2020, 6, 4),
  Decimal('3111.560059'),
  Decimal('3128.909912'),
  Decimal('3090.409912'),
  Decimal('3112.350098'),
  6451290000,
  '^GSPC'),
 (datetime.date(2020, 6, 5),
  Decimal('3163.840088'),
  Decimal('3211.719971'),
  Decimal('3163.840088'),
  Decimal('3193.929932'),
  8639300000,
  '^GSPC'),
 (datetime.date(2020, 6, 8),
  Decimal('3199.919922'),
  Decimal('3233.129883'),
  Decimal('3196.000000'),
  Decimal('3232.389893'),
  8498300000,
  '^GSPC'),
 (datetime.date(2020, 6, 9),
  Decimal('3213.320068'),
  Decimal('3222.709961'),
  Decimal('3193.110107'),
  Decimal('3207.179932'),
  6410930000,
  '^GSPC'),
 (datetime.date(2020, 6, 10),
  Decimal('3213.419922'),
  Decimal('3223.270020'),
  Decimal('3181.489990'),
  Decimal('3190.139893'),
  6598870000,
  '^GSPC'),
 (datetime.date(2020, 6, 11),
  Decimal('3123.530029'),
  Decimal('3123.530029'),
  Decimal('2999.489990'),
  Decimal('3002.100098'),
  7037320000,
  '^GSPC'),
 (datetime.date(2020, 6, 12),
  Decimal('3071.040039'),
  Decimal('3088.419922'),
  Decimal('2984.469971'),
  Decimal('3041.310059'),
  5845330000,
  '^GSPC'),
 (datetime.date(2020, 6, 15),
  Decimal('2993.760010'),
  Decimal('3079.760010'),
  Decimal('2965.659912'),
  Decimal('3066.590088'),
  5757480000,
  '^GSPC'),
 (datetime.date(2020, 6, 16),
  Decimal('3131.000000'),
  Decimal('3153.449951'),
  Decimal('3076.060059'),
  Decimal('3124.739990'),
  5845810000,
  '^GSPC'),
 (datetime.date(2020, 6, 17),
  Decimal('3136.129883'),
  Decimal('3141.159912'),
  Decimal('3108.030029'),
  Decimal('3113.489990'),
  4560450000,
  '^GSPC'),
 (datetime.date(2020, 6, 18),
  Decimal('3101.639893'),
  Decimal('3120.000000'),
  Decimal('3093.510010'),
  Decimal('3115.340088'),
  4448690000,
  '^GSPC'),
 (datetime.date(2020, 6, 19),
  Decimal('3140.290039'),
  Decimal('3155.530029'),
  Decimal('3083.110107'),
  Decimal('3097.739990'),
  8346650000,
  '^GSPC'),
 (datetime.date(2020, 6, 22),
  Decimal('3094.419922'),
  Decimal('3120.919922'),
  Decimal('3079.389893'),
  Decimal('3117.860107'),
  4686690000,
  '^GSPC'),
 (datetime.date(2020, 6, 23),
  Decimal('3138.699951'),
  Decimal('3154.899902'),
  Decimal('3127.120117'),
  Decimal('3131.290039'),
  4711850000,
  '^GSPC'),
 (datetime.date(2020, 6, 24),
  Decimal('3114.399902'),
  Decimal('3115.010010'),
  Decimal('3032.129883'),
  Decimal('3050.330078'),
  5597680000,
  '^GSPC'),
 (datetime.date(2020, 6, 25),
  Decimal('3046.600098'),
  Decimal('3086.250000'),
  Decimal('3024.010010'),
  Decimal('3083.760010'),
  4847690000,
  '^GSPC'),
 (datetime.date(2020, 6, 26),
  Decimal('3073.199951'),
  Decimal('3073.729980'),
  Decimal('3004.629883'),
  Decimal('3009.050049'),
  8107850000,
  '^GSPC'),
 (datetime.date(2020, 6, 29),
  Decimal('3018.590088'),
  Decimal('3053.889893'),
  Decimal('2999.739990'),
  Decimal('3053.239990'),
  4473970000,

In [41]:
cursor.execute("""
SELECT MAX(close) AS highest_nasdaq_closing_price
FROM stock_prices
WHERE ticker = '^IXIC'
""")

result = cursor.fetchall()
result

[(Decimal('27093.900391'),)]

In [42]:
cursor.execute("""
SELECT
    date,
    high,
    low,
    (high - low) AS price_difference
FROM stock_prices
WHERE ticker = '^GSPC'
ORDER BY price_difference DESC
LIMIT 5
""")

result = cursor.fetchall()
result

[(datetime.date(2025, 4, 9),
  Decimal('5481.339844'),
  Decimal('4948.430176'),
  Decimal('532.909668')),
 (datetime.date(2025, 4, 7),
  Decimal('5246.569824'),
  Decimal('4835.040039'),
  Decimal('411.529785')),
 (datetime.date(2025, 4, 8),
  Decimal('5267.470215'),
  Decimal('4910.419922'),
  Decimal('357.050293')),
 (datetime.date(2026, 6, 9),
  Decimal('7483.149902'),
  Decimal('7237.850098'),
  Decimal('245.299804')),
 (datetime.date(2025, 4, 10),
  Decimal('5353.149902'),
  Decimal('5115.270020'),
  Decimal('237.879882'))]

In [43]:
cursor.execute("""
SELECT
    ticker,
    YEAR(date) AS year,
    MONTH(date) AS month,
    AVG(close) AS average_closing_price
FROM stock_prices
GROUP BY ticker, YEAR(date), MONTH(date)
ORDER BY year, month, ticker
""")

result = cursor.fetchall()
result

[('^GSPC', 2020, 1, Decimal('3278.2028576667')),
 ('^IXIC', 2020, 1, Decimal('9233.3599796190')),
 ('^NSEI', 2020, 1, Decimal('12183.0651325217')),
 ('^GSPC', 2020, 2, Decimal('3277.3141832632')),
 ('^IXIC', 2020, 2, Decimal('9418.8500207368')),
 ('^NSEI', 2020, 2, Decimal('11948.8211863684')),
 ('^GSPC', 2020, 3, Decimal('2652.3936323636')),
 ('^IXIC', 2020, 3, Decimal('7772.2058328636')),
 ('^NSEI', 2020, 3, Decimal('9426.3119419524')),
 ('^GSPC', 2020, 4, Decimal('2761.9752255714')),
 ('^IXIC', 2020, 4, Decimal('8292.4071800952')),
 ('^NSEI', 2020, 4, Decimal('9063.5833334444')),
 ('^GSPC', 2020, 5, Decimal('2919.6084838000')),
 ('^IXIC', 2020, 5, Decimal('9105.6554687500')),
 ('^NSEI', 2020, 5, Decimal('9192.0130551053')),
 ('^GSPC', 2020, 6, Decimal('3104.6609330909')),
 ('^IXIC', 2020, 6, Decimal('9839.9713245455')),
 ('^NSEI', 2020, 6, Decimal('10116.4546787273')),
 ('^GSPC', 2020, 7, Decimal('3207.6190962273')),
 ('^IXIC', 2020, 7, Decimal('10499.8627042727')),
 ('^NSEI', 2020, 7, Decimal('10897.6956945652')),
 ('^GSPC', 2020, 8, Decimal('3391.7100190952')),
 ('^IXIC', 2020, 8, Decimal('11212.2905042857')),
 ('^NSEI', 2020, 8, Decimal('11318.5666852381')),
 ('^GSPC', 2020, 9, Decimal('3365.5166713810')),
 ('^IXIC', 2020, 9, Decimal('11088.6799665238')),
 ('^NSEI', 2020, 9, Decimal('11336.7021928636')),
 ('^GSPC', 2020, 10, Decimal('3418.6999956818')),
 ('^IXIC', 2020, 10, Decimal('11435.2341086818')),
 ('^NSEI', 2020, 10, Decimal('11789.7094958571')),
 ('^GSPC', 2020, 11, Decimal('3548.9924803500')),
 ('^IXIC', 2020, 11, Decimal('11794.4615235500')),
 ('^NSEI', 2020, 11, Decimal('12592.9579564737')),
 ('^GSPC', 2020, 12, Decimal('3695.3100141818')),
 ('^IXIC', 2020, 12, Decimal('12619.0509144091')),
 ('^NSEI', 2020, 12, Decimal('13550.4408735455')),
 ('^GSPC', 2021, 1, Decimal('3793.7484323158')),
 ('^IXIC', 2021, 1, Decimal('13186.6057771053')),
 ('^NSEI', 2021, 1, Decimal('14284.6024902000')),
 ('^GSPC', 2021, 2, Decimal('3883.4321160526')),
 ('^IXIC', 2021, 2, Decimal('13737.4036286316')),
 ('^NSEI', 2021, 2, Decimal('14956.8425293000')),
 ('^GSPC', 2021, 3, Decimal('3910.5082796522')),
 ('^IXIC', 2021, 3, Decimal('13168.8118206957')),
 ('^NSEI', 2021, 3, Decimal('14835.0999813810')),
 ('^GSPC', 2021, 4, Decimal('4141.1761997619')),
 ('^IXIC', 2021, 4, Decimal('13900.4379650952')),
 ('^NSEI', 2021, 4, Decimal('14613.8525391053')),
 ('^GSPC', 2021, 5, Decimal('4167.8495361500')),
 ('^IXIC', 2021, 5, Decimal('13520.2290527000')),
 ('^NSEI', 2021, 5, Decimal('14983.5250000500')),
 ('^GSPC', 2021, 6, Decimal('4238.4895463182')),
 ('^IXIC', 2021, 6, Decimal('14097.1690785000')),
 ('^NSEI', 2021, 6, Decimal('15733.6772015455')),
 ('^GSPC', 2021, 7, Decimal('4363.7127976190')),
 ('^IXIC', 2021, 7, Decimal('14639.0728700952')),
 ('^NSEI', 2021, 7, Decimal('15783.0976562381')),
 ('^GSPC', 2021, 8, Decimal('4453.9659312727')),
 ('^IXIC', 2021, 8, Decimal('14856.5177113636')),
 ('^NSEI', 2021, 8, Decimal('16470.4594493810')),
 ('^GSPC', 2021, 9, Decimal('4445.5433173810')),
 ('^IXIC', 2021, 9, Decimal('15023.5385510000')),
 ('^NSEI', 2021, 9, Decimal('17508.6143043333')),
 ('^GSPC', 2021, 10, Decimal('4460.7070777619')),
 ('^IXIC', 2021, 10, Decimal('14879.0123232381')),
 ('^NSEI', 2021, 10, Decimal('18020.2200195500')),
 ('^GSPC', 2021, 11, Decimal('4667.3866490000')),
 ('^IXIC', 2021, 11, Decimal('15814.9328962381')),
 ('^NSEI', 2021, 11, Decimal('17718.8923828500')),
 ('^GSPC', 2021, 12, Decimal('4674.7727717727')),
 ('^IXIC', 2021, 12, Decimal('15474.4317295000')),
 ('^NSEI', 2021, 12, Decimal('17174.2694463913')),
 ('^GSPC', 2022, 1, Decimal('4573.8154541500')),
 ('^IXIC', 2022, 1, Decimal('14531.3774903000')),
 ('^NSEI', 2022, 1, Decimal('17770.6224609500')),
 ('^GSPC', 2022, 2, Decimal('4435.9804944211')),
 ('^IXIC', 2022, 2, Decimal('13898.7284129474')),
 ('^NSEI', 2022, 2, Decimal('17225.9399902000')),
 ('^GSPC', 2022, 3, Decimal('4391.2652640870')),
 ('^IXIC', 2022, 3, Decimal('13623.2629501304')),
 ('^NSEI', 2022, 3, Decimal('16864.6738745714')),
 ('^GSPC', 2022, 4, Decimal('4391.2959960000')),
 ('^IXIC', 2022, 4, Decimal('13394.1630372000')),
 ('^NSEI', 2022, 4, Decimal('17419.3607114211')),
 ('^GSPC', 2022, 5, Decimal('4040.3600027619')),
 ('^IXIC', 2022, 5, Decimal('11829.7295386667')),
 ('^NSEI', 2022, 5, Decimal('16271.0191128095')),
 ('^GSPC', 2022, 6, Decimal('3898.9466842857')),
 ('^IXIC', 2022, 6, Decimal('11418.9190848095')),
 ('^NSEI', 2022, 6, Decimal('15933.1636630000')),
 ('^GSPC', 2022, 7, Decimal('3911.7294922000')),
 ('^IXIC', 2022, 7, Decimal('11622.6315430500')),
 ('^NSEI', 2022, 7, Decimal('16299.0213448571')),
 ('^GSPC', 2022, 8, Decimal('4158.5630836957')),
 ('^IXIC', 2022, 8, Decimal('12570.2604026087')),
 ('^NSEI', 2022, 8, Decimal('17579.0649415000')),
 ('^GSPC', 2022, 9, Decimal('3850.5204961905')),
 ('^IXIC', 2022, 9, Decimal('11402.8499815238')),
 ('^NSEI', 2022, 9, Decimal('17544.8773080909')),
 ('^GSPC', 2022, 10, Decimal('3726.0509556190')),
 ('^IXIC', 2022, 10, Decimal('10801.4942801905')),
 ('^NSEI', 2022, 10, Decimal('17406.8736635789')),
 ('^GSPC', 2022, 11, Decimal('3917.4885950952')),
 ('^IXIC', 2022, 11, Decimal('10973.6381138571')),
 ('^NSEI', 2022, 11, Decimal('18311.2832962381')),
 ('^GSPC', 2022, 12, Decimal('3912.3809523333')),
 ('^IXIC', 2022, 12, Decimal('10838.9958146667')),
 ('^NSEI', 2022, 12, Decimal('18385.1319245909')),
 ('^GSPC', 2023, 1, Decimal('3960.6565309000')),
 ('^IXIC', 2023, 1, Decimal('11013.9909668500')),
 ('^NSEI', 2023, 1, Decimal('17968.7450707143')),
 ('^GSPC', 2023, 2, Decimal('4079.6847244737')),
 ('^IXIC', 2023, 2, Decimal('11785.0743216316')),
 ('^NSEI', 2023, 2, Decimal('17739.2223632500')),
 ('^GSPC', 2023, 3, Decimal('3968.5591458261')),
 ('^IXIC', 2023, 3, Decimal('11637.0922215217')),
 ('^NSEI', 2023, 3, Decimal('17225.6429502381')),
 ('^GSPC', 2023, 4, Decimal('4121.4673623158')),
 ('^IXIC', 2023, 4, Decimal('12073.4647409474')),
 ('^NSEI', 2023, 4, Decimal('17710.6796874706')),
 ('^GSPC', 2023, 5, Decimal('4146.1731955455')),
 ('^IXIC', 2023, 5, Decimal('12446.5304955000')),
 ('^NSEI', 2023, 5, Decimal('18307.0545987727')),
 ('^GSPC', 2023, 6, Decimal('4345.3728376667')),
 ('^IXIC', 2023, 6, Decimal('13463.7781343810')),
 ('^NSEI', 2023, 6, Decimal('18726.7713913810')),
 ('^GSPC', 2023, 7, Decimal('4508.0754882500')),
 ('^IXIC', 2023, 7, Decimal('14033.0909667000')),
 ('^NSEI', 2023, 7, Decimal('19586.0002790000')),
 ('^GSPC', 2023, 8, Decimal('4457.3586744783')),
 ('^IXIC', 2023, 8, Decimal('13743.2130180435')),
 ('^NSEI', 2023, 8, Decimal('19438.2865766364')),
 ('^GSPC', 2023, 9, Decimal('4409.0949950500')),
 ('^IXIC', 2023, 9, Decimal('13585.8395508000')),
 ('^NSEI', 2023, 9, Decimal('19786.0451171000')),
 ('^GSPC', 2023, 10, Decimal('4269.4009454091')),
 ('^IXIC', 2023, 10, Decimal('13199.4276901364')),
 ('^NSEI', 2023, 10, Decimal('19481.6649413500')),
 ('^GSPC', 2023, 11, Decimal('4460.0633138095')),
 ('^IXIC', 2023, 11, Decimal('13913.1605748095')),
 ('^NSEI', 2023, 11, Decimal('19602.8499023500')),
 ('^GSPC', 2023, 12, Decimal('4685.0514893000')),
 ('^IXIC', 2023, 12, Decimal('14690.4739746000')),
 ('^NSEI', 2023, 12, Decimal('21165.9900391500')),
 ('^GSPC', 2024, 1, Decimal('4804.4915131905')),
 ('^IXIC', 2024, 1, Decimal('15081.3881605238')),
 ('^NSEI', 2024, 1, Decimal('21634.7546502381')),
 ('^GSPC', 2024, 2, Decimal('5011.9614258000')),
 ('^IXIC', 2024, 2, Decimal('15808.9350097500')),
 ('^NSEI', 2024, 2, Decimal('21947.2785528571')),
 ('^GSPC', 2024, 3, Decimal('5170.5724853000')),
 ('^IXIC', 2024, 3, Decimal('16216.2955078000')),
 ('^NSEI', 2024, 3, Decimal('22176.6943360000')),
 ('^GSPC', 2024, 4, Decimal('5112.4927424091')),
 ('^IXIC', 2024, 4, Decimal('15950.8635475909')),
 ('^NSEI', 2024, 4, Decimal('22443.4576172500')),
 ('^GSPC', 2024, 5, Decimal('5235.2254971818')),
 ('^IXIC', 2024, 5, Decimal('16536.3171609545')),
 ('^NSEI', 2024, 5, Decimal('22484.4332217143')),
 ('^GSPC', 2024, 6, Decimal('5415.1404963684')),
 ('^IXIC', 2024, 6, Decimal('17495.8916530000')),
 ('^NSEI', 2024, 6, Decimal('23364.0447162632')),
 ('^GSPC', 2024, 7, Decimal('5538.0045721364')),
 ('^IXIC', 2024, 7, Decimal('17963.2909269091')),
 ('^NSEI', 2024, 7, Decimal('24495.1521661818')),
 ('^GSPC', 2024, 8, Decimal('5478.2145775000')),
 ('^IXIC', 2024, 8, Decimal('17268.2688653636')),
 ('^NSEI', 2024, 8, Decimal('24613.0737537619')),
 ('^GSPC', 2024, 9, Decimal('5621.2604493500')),
 ('^IXIC', 2024, 9, Decimal('17599.2301758000')),
 ('^NSEI', 2024, 9, Decimal('25470.0904948095')),
 ('^GSPC', 2024, 10, Decimal('5792.3195482174')),
 ('^IXIC', 2024, 10, Decimal('18316.4046366087')),
 ('^NSEI', 2024, 10, Decimal('24781.6703656818')),
 ('^GSPC', 2024, 11, Decimal('5929.9159912000')),
 ('^IXIC', 2024, 11, Decimal('18961.3357423500')),
 ('^NSEI', 2024, 11, Decimal('23969.8474506316')),
 ('^GSPC', 2024, 12, Decimal('6010.9085518571')),
 ('^IXIC', 2024, 12, Decimal('19734.5417596667')),
 ('^NSEI', 2024, 12, Decimal('24231.0191592857')),
 ('^GSPC', 2025, 1, Decimal('5979.5155273000')),
 ('^IXIC', 2025, 1, Decimal('19565.0439454500')),
 ('^NSEI', 2025, 1, Decimal('23366.3956352609')),
 ('^GSPC', 2025, 2, Decimal('6038.6899670526')),
 ('^IXIC', 2025, 2, Decimal('19547.2814556842')),
 ('^NSEI', 2025, 2, Decimal('23060.9376953000')),
 ('^GSPC', 2025, 3, Decimal('5683.9833519524')),
 ('^IXIC', 2025, 3, Decimal('17828.0265067619')),
 ('^NSEI', 2025, 3, Decimal('22851.5369037895')),
 ('^GSPC', 2025, 4, Decimal('5369.4957217619')),
 ('^IXIC', 2025, 4, Decimal('16678.4597284762')),
 ('^NSEI', 2025, 4, Decimal('23531.6629317368')),
 ('^GSPC', 2025, 5, Decimal('5810.9194800952')),
 ('^IXIC', 2025, 5, Decimal('18642.3692336667')),
 ('^NSEI', 2025, 5, Decimal('24676.4402902857')),
 ('^GSPC', 2025, 6, Decimal('6029.9515137000')),
 ('^IXIC', 2025, 6, Decimal('19673.3011718500')),
 ('^NSEI', 2025, 6, Decimal('25003.3976934762')),
 ('^GSPC', 2025, 7, Decimal('6296.4981801364')),
 ('^IXIC', 2025, 7, Decimal('20784.8959517727')),
 ('^NSEI', 2025, 7, Decimal('25164.8914741304')),
 ('^GSPC', 2025, 8, Decimal('6408.9494744286')),
 ('^IXIC', 2025, 8, Decimal('21383.5871466190')),
 ('^NSEI', 2025, 8, Decimal('24698.1027960000')),
 ('^GSPC', 2025, 9, Decimal('6584.0180896667')),
 ('^IXIC', 2025, 9, Decimal('22188.5877977143')),
 ('^NSEI', 2025, 9, Decimal('24942.6749821364')),
 ('^GSPC', 2025, 10, Decimal('6735.6917247391')),
 ('^IXIC', 2025, 10, Decimal('23003.1257643478')),
 ('^NSEI', 2025, 10, Decimal('25494.0835192857')),
 ('^GSPC', 2025, 11, Decimal('6740.8857678421')),
 ('^IXIC', 2025, 11, Decimal('23023.6227385263')),
 ('^NSEI', 2025, 11, Decimal('25894.8343955789')),
 ('^GSPC', 2025, 12, Decimal('6853.0254572273')),
 ('^IXIC', 2025, 12, Decimal('23377.3268821364')),
 ('^NSEI', 2025, 12, Decimal('25997.7387250909')),
 ('^GSPC', 2026, 1, Decimal('6929.1219727000')),
 ('^IXIC', 2026, 1, Decimal('23520.7223633500')),
 ('^NSEI', 2026, 1, Decimal('25652.9626953000')),
 ('^GSPC', 2026, 2, Decimal('6893.8062809474')),
 ('^IXIC', 2026, 2, Decimal('22892.9234170000')),
 ('^NSEI', 2026, 2, Decimal('25625.5750976500')),
 ('^GSPC', 2026, 3, Decimal('6654.4191228182')),
 ('^IXIC', 2026, 3, Decimal('22130.0376420909')),
 ('^NSEI', 2026, 3, Decimal('23593.4842722632')),
 ('^GSPC', 2026, 4, Decimal('6957.0076264762')),
 ('^IXIC', 2026, 4, Decimal('23677.0529203810')),
 ('^NSEI', 2026, 4, Decimal('23879.2924804000')),
 ('^GSPC', 2026, 5, Decimal('7412.5515381000')),
 ('^IXIC', 2026, 5, Decimal('26155.7746094000')),
 ('^NSEI', 2026, 5, Decimal('23822.5368010000')),
 ('^GSPC', 2026, 6, Decimal('7450.0329008571')),
 ('^IXIC', 2026, 6, Decimal('26074.8471913333')),
 ('^NSEI', 2026, 6, Decimal('23683.1451822857')),
 ('^GSPC', 2026, 7, Decimal('7481.3390891364')),
 ('^IXIC', 2026, 7, Decimal('25623.6799539545')),
 ('^NSEI', 2026, 7, Decimal('24133.6324727826')),
 ('^GSPC', 2026, 8, Decimal('7715.9949951250')),
 ('^IXIC', 2026, 8, Decimal('26410.3948975000')),
 ('^NSEI', 2026, 8, Decimal('24418.5970459375'))]

In [44]:
cursor.execute("""
SELECT AVG(volume) AS average_nsei_volume
FROM stock_prices
WHERE ticker = '^NSEI'
AND date BETWEEN '2024-01-01' AND '2024-12-31'
""")

result = cursor.fetchall()
result

[(Decimal('313560.1626'),)]

Cross-Market JOIN Queries

In [45]:
cursor.execute("""
SELECT
    AVG(c.price_usd) AS bitcoin_average_price,
    AVG(o.price_usd) AS oil_average_price
FROM crypto_prices c
JOIN oil_prices o
ON c.date = o.date
WHERE c.coin_id = 'bitcoin'
AND c.date BETWEEN '2025-01-01' AND '2025-12-31'
""")

result = cursor.fetchall()
result

[(Decimal('99863.6747820667'), Decimal('59.5386666667'))]

In [46]:
cursor.execute("""
SELECT
    (
        COUNT(*) * SUM(c.price_usd * s.close)
        - SUM(c.price_usd) * SUM(s.close)
    )
    /
    SQRT(
        (
            COUNT(*) * SUM(c.price_usd * c.price_usd)
            - POW(SUM(c.price_usd), 2)
        )
        *
        (
            COUNT(*) * SUM(s.close * s.close)
            - POW(SUM(s.close), 2)
        )
    ) AS correlation
FROM crypto_prices c
JOIN stock_prices s
ON c.date = s.date
WHERE c.coin_id = 'bitcoin'
AND s.ticker = '^GSPC'
AND c.date BETWEEN '2025-01-01' AND '2025-12-31'
""")

result = cursor.fetchall()
result

[(0.06455489973623471,)]

In [47]:
cursor.execute("""
SELECT
    c.date,
    c.price_usd AS ethereum_price,
    s.close AS nasdaq_close
FROM crypto_prices c
JOIN stock_prices s
ON c.date = s.date
WHERE c.coin_id = 'ethereum'
AND s.ticker = '^IXIC'
AND c.date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY c.date
""")

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3), Decimal('4484.180377'), Decimal('22780.509766')),
 (datetime.date(2025, 10, 6), Decimal('4513.310148'), Decimal('22941.669922')),
 (datetime.date(2025, 10, 7), Decimal('4690.837856'), Decimal('22788.359375')),
 (datetime.date(2025, 10, 8), Decimal('4453.781266'), Decimal('23043.380859')),
 (datetime.date(2025, 10, 9), Decimal('4526.062095'), Decimal('23024.630859')),
 (datetime.date(2025, 10, 10),
  Decimal('4368.419617'),
  Decimal('22204.429688')),
 (datetime.date(2025, 10, 13),
  Decimal('4151.918863'),
  Decimal('22694.609375')),
 (datetime.date(2025, 10, 14),
  Decimal('4245.447077'),
  Decimal('22521.699219')),
 (datetime.date(2025, 10, 15),
  Decimal('4126.235353'),
  Decimal('22670.080078')),
 (datetime.date(2025, 10, 16),
  Decimal('3991.544236'),
  Decimal('22562.539063')),
 (datetime.date(2025, 10, 17),
  Decimal('3893.756038'),
  Decimal('22679.970703')),
 (datetime.date(2025, 10, 20),
  Decimal('3982.355861'),
  Decimal('22990.539063')),
 (datetime.date(2025, 10, 21),
  Decimal('3980.073280'),
  Decimal('22953.669922')),
 (datetime.date(2025, 10, 22),
  Decimal('3866.151783'),
  Decimal('22740.400391')),
 (datetime.date(2025, 10, 23),
  Decimal('3805.881864'),
  Decimal('22941.800781')),
 (datetime.date(2025, 10, 24),
  Decimal('3857.590009'),
  Decimal('23204.869141')),
 (datetime.date(2025, 10, 27),
  Decimal('4158.567622'),
  Decimal('23637.460938')),
 (datetime.date(2025, 10, 28),
  Decimal('4117.287078'),
  Decimal('23827.490234')),
 (datetime.date(2025, 10, 29),
  Decimal('3978.812010'),
  Decimal('23958.470703')),
 (datetime.date(2025, 10, 30),
  Decimal('3902.801947'),
  Decimal('23581.140625')),
 (datetime.date(2025, 10, 31),
  Decimal('3801.551505'),
  Decimal('23724.960938')),
 (datetime.date(2025, 11, 3), Decimal('3905.342930'), Decimal('23834.720703')),
 (datetime.date(2025, 11, 4), Decimal('3600.363768'), Decimal('23348.640625')),
 (datetime.date(2025, 11, 5), Decimal('3285.231840'), Decimal('23499.800781')),
 (datetime.date(2025, 11, 6), Decimal('3425.969806'), Decimal('23053.990234')),
 (datetime.date(2025, 11, 7), Decimal('3312.450307'), Decimal('23004.539063')),
 (datetime.date(2025, 11, 10),
  Decimal('3578.802306'),
  Decimal('23527.169922')),
 (datetime.date(2025, 11, 11),
  Decimal('3566.049867'),
  Decimal('23468.300781')),
 (datetime.date(2025, 11, 12),
  Decimal('3416.071509'),
  Decimal('23406.460938')),
 (datetime.date(2025, 11, 13),
  Decimal('3412.543237'),
  Decimal('22870.359375')),
 (datetime.date(2025, 11, 14),
  Decimal('3223.175779'),
  Decimal('22900.589844')),
 (datetime.date(2025, 11, 17),
  Decimal('3091.905046'),
  Decimal('22708.070313')),
 (datetime.date(2025, 11, 18),
  Decimal('3026.218255'),
  Decimal('22432.849609')),
 (datetime.date(2025, 11, 19),
  Decimal('3121.513848'),
  Decimal('22564.230469')),
 (datetime.date(2025, 11, 20),
  Decimal('3020.935788'),
  Decimal('22078.050781')),
 (datetime.date(2025, 11, 21),
  Decimal('2832.530798'),
  Decimal('22273.080078')),
 (datetime.date(2025, 11, 24),
  Decimal('2798.913101'),
  Decimal('22872.009766')),
 (datetime.date(2025, 11, 25),
  Decimal('2952.334907'),
  Decimal('23025.589844')),
 (datetime.date(2025, 11, 26),
  Decimal('2958.573218'),
  Decimal('23214.689453')),
 (datetime.date(2025, 11, 27), Decimal('3026.421535'), None),
 (datetime.date(2025, 11, 28),
  Decimal('3014.819850'),
  Decimal('23365.689453')),
 (datetime.date(2025, 12, 1), Decimal('2990.797383'), Decimal('23275.919922')),
 (datetime.date(2025, 12, 2), Decimal('2796.733869'), Decimal('23413.669922')),
 (datetime.date(2025, 12, 3), Decimal('2997.602427'), Decimal('23454.089844')),
 (datetime.date(2025, 12, 4), Decimal('3188.881945'), Decimal('23505.140625')),
 (datetime.date(2025, 12, 5), Decimal('3134.348641'), Decimal('23578.130859')),
 (datetime.date(2025, 12, 8), Decimal('3060.994832'), Decimal('23545.900391')),
 (datetime.date(2025, 12, 9), Decimal('3123.805252'), Decimal('23576.490234')),
 (datetime.date(2025, 12, 10),
  Decimal('3318.720945'),
  Decimal('23654.150391')),
 (datetime.date(2025, 12, 11),
  Decimal('3323.292013'),
  Decimal('23593.859375')),
 (datetime.date(2025, 12, 12),
  Decimal('3238.413615'),
  Decimal('23195.169922')),
 (datetime.date(2025, 12, 15),
  Decimal('3063.545453'),
  Decimal('23057.410156')),
 (datetime.date(2025, 12, 16),
  Decimal('2963.894557'),
  Decimal('23111.460938')),
 (datetime.date(2025, 12, 17),
  Decimal('2957.860249'),
  Decimal('22693.320313')),
 (datetime.date(2025, 12, 18),
  Decimal('2832.468327'),
  Decimal('23006.359375')),
 (datetime.date(2025, 12, 19),
  Decimal('2826.673248'),
  Decimal('23307.619141')),
 (datetime.date(2025, 12, 22),
  Decimal('3004.220492'),
  Decimal('23428.830078')),
 (datetime.date(2025, 12, 23),
  Decimal('3005.375558'),
  Decimal('23561.839844')),
 (datetime.date(2025, 12, 24),
  Decimal('2965.218785'),
  Decimal('23613.310547')),
 (datetime.date(2025, 12, 26),
  Decimal('2901.680790'),
  Decimal('23593.099609')),
 (datetime.date(2025, 12, 29),
  Decimal('2948.831769'),
  Decimal('23474.349609')),
 (datetime.date(2025, 12, 30),
  Decimal('2934.356281'),
  Decimal('23419.080078')),
 (datetime.date(2025, 12, 31),
  Decimal('2967.980414'),
  Decimal('23241.990234'))]

In [48]:
cursor.execute("""
SELECT
    o.date,
    o.price_usd AS oil_price,
    c.price_usd AS bitcoin_price,
    (
        (o.price_usd -
        LAG(o.price_usd) OVER (ORDER BY o.date))
        /
        LAG(o.price_usd) OVER (ORDER BY o.date)
    ) * 100 AS oil_change_percent
FROM oil_prices o
JOIN crypto_prices c
ON o.date = c.date
WHERE c.coin_id = 'bitcoin'
ORDER BY o.date
""")

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3),
  Decimal('61.650000'),
  Decimal('120514.577856'),
  None),
 (datetime.date(2025, 10, 6),
  Decimal('62.490000'),
  Decimal('123488.730597'),
  Decimal('1.3625304136')),
 (datetime.date(2025, 10, 7),
  Decimal('62.520000'),
  Decimal('124739.810888'),
  Decimal('0.0480076812')),
 (datetime.date(2025, 10, 8),
  Decimal('63.370000'),
  Decimal('121463.118082'),
  Decimal('1.3595649392')),
 (datetime.date(2025, 10, 9),
  Decimal('62.360000'),
  Decimal('123342.984698'),
  Decimal('-1.5938141076')),
 (datetime.date(2025, 10, 10),
  Decimal('59.750000'),
  Decimal('121718.667577'),
  Decimal('-4.1853752405')),
 (datetime.date(2025, 10, 14),
  Decimal('59.520000'),
  Decimal('115226.584290'),
  Decimal('-0.3849372385')),
 (datetime.date(2025, 10, 15),
  Decimal('59.080000'),
  Decimal('113066.350785'),
  Decimal('-0.7392473118')),
 (datetime.date(2025, 10, 16),
  Decimal('58.290000'),
  Decimal('110844.404172'),
  Decimal('-1.3371699391')),
 (datetime.date(2025, 10, 17),
  Decimal('58.300000'),
  Decimal('108168.173534'),
  Decimal('0.0171556013')),
 (datetime.date(2025, 10, 20),
  Decimal('58.340000'),
  Decimal('108655.505250'),
  Decimal('0.0686106346')),
 (datetime.date(2025, 10, 21),
  Decimal('58.660000'),
  Decimal('110535.863014'),
  Decimal('0.5485087419')),
 (datetime.date(2025, 10, 22),
  Decimal('59.300000'),
  Decimal('108301.754625'),
  Decimal('1.0910330719')),
 (datetime.date(2025, 10, 23),
  Decimal('62.440000'),
  Decimal('107591.460509'),
  Decimal('5.2951096121')),
 (datetime.date(2025, 10, 24),
  Decimal('62.270000'),
  Decimal('110109.305225'),
  Decimal('-0.2722613709')),
 (datetime.date(2025, 10, 27),
  Decimal('62.130000'),
  Decimal('114419.221697'),
  Decimal('-0.2248273647')),
 (datetime.date(2025, 10, 28),
  Decimal('60.970000'),
  Decimal('114085.331238'),
  Decimal('-1.8670529535')),
 (datetime.date(2025, 10, 29),
  Decimal('61.260000'),
  Decimal('112893.852036'),
  Decimal('0.4756437592')),
 (datetime.date(2025, 10, 30),
  Decimal('61.360000'),
  Decimal('110026.087620'),
  Decimal('0.1632386549')),
 (datetime.date(2025, 10, 31),
  Decimal('61.750000'),
  Decimal('108409.379925'),
  Decimal('0.6355932203')),
 (datetime.date(2025, 11, 3),
  Decimal('61.790000'),
  Decimal('110499.522383'),
  Decimal('0.0647773279')),
 (datetime.date(2025, 11, 4),
  Decimal('61.380000'),
  Decimal('106451.706533'),
  Decimal('-0.6635377893')),
 (datetime.date(2025, 11, 5),
  Decimal('60.400000'),
  Decimal('101480.766596'),
  Decimal('-1.5966112740')),
 (datetime.date(2025, 11, 6),
  Decimal('60.240000'),
  Decimal('103878.933600'),
  Decimal('-0.2649006623')),
 (datetime.date(2025, 11, 7),
  Decimal('60.540000'),
  Decimal('101261.645510'),
  Decimal('0.4980079681')),
 (datetime.date(2025, 11, 10),
  Decimal('60.940000'),
  Decimal('104610.228536'),
  Decimal('0.6607201850')),
 (datetime.date(2025, 11, 12),
  Decimal('59.300000'),
  Decimal('103112.210062'),
  Decimal('-2.6911716442')),
 (datetime.date(2025, 11, 13),
  Decimal('59.540000'),
  Decimal('101633.694316'),
  Decimal('0.4047217538')),
 (datetime.date(2025, 11, 14),
  Decimal('60.870000'),
  Decimal('99480.307091'),
  Decimal('2.2337924085')),
 (datetime.date(2025, 11, 17),
  Decimal('60.660000'),
  Decimal('94188.276689'),
  Decimal('-0.3449975357')),
 (datetime.date(2025, 11, 18),
  Decimal('61.510000'),
  Decimal('92100.364524'),
  Decimal('1.4012528849')),
 (datetime.date(2025, 11, 19),
  Decimal('60.270000'),
  Decimal('92903.180085'),
  Decimal('-2.0159323687')),
 (datetime.date(2025, 11, 20),
  Decimal('60.070000'),
  Decimal('91408.357334'),
  Decimal('-0.3318400531')),
 (datetime.date(2025, 11, 21),
  Decimal('58.860000'),
  Decimal('86618.471559'),
  Decimal('-2.0143166306')),
 (datetime.date(2025, 11, 24),
  Decimal('59.110000'),
  Decimal('86740.117739'),
  Decimal('0.4247366633')),
 (datetime.date(2025, 11, 25),
  Decimal('58.250000'),
  Decimal('88256.043956'),
  Decimal('-1.4549145661')),
 (datetime.date(2025, 11, 26),
  Decimal('58.810000'),
  Decimal('87317.004551'),
  Decimal('0.9613733906')),
 (datetime.date(2025, 11, 28),
  Decimal('58.580000'),
  Decimal('91323.628276'),
  Decimal('-0.3910899507')),
 (datetime.date(2025, 12, 1),
  Decimal('59.470000'),
  Decimal('90359.868732'),
  Decimal('1.5192898600')),
 (datetime.date(2025, 12, 2),
  Decimal('58.810000'),
  Decimal('86303.897664'),
  Decimal('-1.1098032621')),
 (datetime.date(2025, 12, 3),
  Decimal('59.090000'),
  Decimal('91320.079425'),
  Decimal('0.4761095052')),
 (datetime.date(2025, 12, 4),
  Decimal('59.820000'),
  Decimal('93428.594515'),
  Decimal('1.2354036216')),
 (datetime.date(2025, 12, 5),
  Decimal('60.230000'),
  Decimal('92119.190478'),
  Decimal('0.6853895018')),
 (datetime.date(2025, 12, 8),
  Decimal('59.040000'),
  Decimal('90398.448757'),
  Decimal('-1.9757595882')),
 (datetime.date(2025, 12, 9),
  Decimal('58.400000'),
  Decimal('90626.037343'),
  Decimal('-1.0840108401')),
 (datetime.date(2025, 12, 10),
  Decimal('58.670000'),
  Decimal('92686.104020'),
  Decimal('0.4623287671')),
 (datetime.date(2025, 12, 11),
  Decimal('57.760000'),
  Decimal('91986.581072'),
  Decimal('-1.5510482359')),
 (datetime.date(2025, 12, 12),
  Decimal('57.610000'),
  Decimal('92525.868003'),
  Decimal('-0.2596952909')),
 (datetime.date(2025, 12, 15),
  Decimal('56.970000'),
  Decimal('88184.410931'),
  Decimal('-1.1109182434')),
 (datetime.date(2025, 12, 16),
  Decimal('55.440000'),
  Decimal('86413.221381'),
  Decimal('-2.6856240126')),
 (datetime.date(2025, 12, 17),
  Decimal('56.070000'),
  Decimal('87719.681398'),
  Decimal('1.1363636364')),
 (datetime.date(2025, 12, 18),
  Decimal('56.220000'),
  Decimal('86196.821373'),
  Decimal('0.2675227394')),
 (datetime.date(2025, 12, 19),
  Decimal('56.800000'),
  Decimal('85450.179648'),
  Decimal('1.0316613305')),
 (datetime.date(2025, 12, 22),
  Decimal('58.180000'),
  Decimal('88672.329679'),
  Decimal('2.4295774648')),
 (datetime.date(2025, 12, 23),
  Decimal('58.550000'),
  Decimal('88489.724042'),
  Decimal('0.6359573737')),
 (datetime.date(2025, 12, 24),
  Decimal('58.720000'),
  Decimal('87496.146692'),
  Decimal('0.2903501281')),
 (datetime.date(2025, 12, 26),
  Decimal('56.600000'),
  Decimal('87192.234737'),
  Decimal('-3.6103542234')),
 (datetime.date(2025, 12, 29),
  Decimal('57.890000'),
  Decimal('87867.039434'),
  Decimal('2.2791519435')),
 (datetime.date(2025, 12, 30),
  Decimal('57.790000'),
  Decimal('87154.682406'),
  Decimal('-0.1727414061')),
 (datetime.date(2025, 12, 31),
  Decimal('57.260000'),
  Decimal('88363.722236'),
  Decimal('-0.9171136875')),
 (datetime.date(2026, 1, 2),
  Decimal('57.210000'),
  Decimal('88764.126241'),
  Decimal('-0.0873209920')),
 (datetime.date(2026, 1, 5),
  Decimal('58.100000'),
  Decimal('91879.577226'),
  Decimal('1.5556720853')),
 (datetime.date(2026, 1, 6),
  Decimal('56.970000'),
  Decimal('93879.947973'),
  Decimal('-1.9449225473')),
 (datetime.date(2026, 1, 7),
  Decimal('56.010000'),
  Decimal('93649.631976'),
  Decimal('-1.6850974197')),
 (datetime.date(2026, 1, 8),
  Decimal('57.740000'),
  Decimal('91286.033144'),
  Decimal('3.0887341546')),
 (datetime.date(2026, 1, 9),
  Decimal('58.960000'),
  Decimal('91027.666170'),
  Decimal('2.1129199861')),
 (datetime.date(2026, 1, 12),
  Decimal('59.390000'),
  Decimal('90856.559102'),
  Decimal('0.7293080054')),
 (datetime.date(2026, 1, 13),
  Decimal('60.850000'),
  Decimal('91200.627615'),
  Decimal('2.4583263176')),
 (datetime.date(2026, 1, 14),
  Decimal('61.840000'),
  Decimal('95429.157322'),
  Decimal('1.6269515201')),
 (datetime.date(2026, 1, 15),
  Decimal('59.130000'),
  Decimal('96898.760711'),
  Decimal('-4.3822768435')),
 (datetime.date(2026, 1, 16),
  Decimal('59.400000'),
  Decimal('95593.307837'),
  Decimal('0.4566210046')),
 (datetime.date(2026, 1, 20),
  Decimal('60.300000'),
  Decimal('92566.012780'),
  Decimal('1.5151515152')),
 (datetime.date(2026, 1, 21),
  Decimal('60.380000'),
  Decimal('88416.886862'),
  Decimal('0.1326699834')),
 (datetime.date(2026, 1, 22),
  Decimal('59.240000'),
  Decimal('89453.904737'),
  Decimal('-1.8880423981')),
 (datetime.date(2026, 1, 23),
  Decimal('60.700000'),
  Decimal('89483.651630'),
  Decimal('2.4645509791')),
 (datetime.date(2026, 1, 26),
  Decimal('60.460000'),
  Decimal('86625.331281'),
  Decimal('-0.3953871499')),
 (datetime.date(2026, 1, 27),
  Decimal('62.040000'),
  Decimal('88249.901418'),
  Decimal('2.6132980483')),
 (datetime.date(2026, 1, 28),
  Decimal('62.750000'),
  Decimal('89141.650360'),
  Decimal('1.1444229529')),
 (datetime.date(2026, 1, 29),
  Decimal('64.770000'),
  Decimal('89212.208242'),
  Decimal('3.2191235060')),
 (datetime.date(2026, 1, 30),
  Decimal('64.500000'),
  Decimal('84630.420667'),
  Decimal('-0.4168596572')),
 (datetime.date(2026, 2, 2),
  Decimal('61.600000'),
  Decimal('76895.586656'),
  Decimal('-4.4961240310')),
 (datetime.date(2026, 2, 3),
  Decimal('62.620000'),
  Decimal('78670.589228'),
  Decimal('1.6558441558')),
 (datetime.date(2026, 2, 4),
  Decimal('64.560000'),
  Decimal('75628.041733'),
  Decimal('3.0980517407')),
 (datetime.date(2026, 2, 5),
  Decimal('62.900000'),
  Decimal('73059.179867'),
  Decimal('-2.5712515489')),
 (datetime.date(2026, 2, 6),
  Decimal('63.770000'),
  Decimal('62778.217566'),
  Decimal('1.3831478537')),
 (datetime.date(2026, 2, 9),
  Decimal('64.530000'),
  Decimal('70398.085033'),
  Decimal('1.1917829700')),
 (datetime.date(2026, 2, 10),
  Decimal('64.200000'),
  Decimal('70175.147492'),
  Decimal('-0.5113900511')),
 (datetime.date(2026, 2, 11),
  Decimal('64.800000'),
  Decimal('68841.872376'),
  Decimal('0.9345794393')),
 (datetime.date(2026, 2, 12),
  Decimal('63.080000'),
  Decimal('67090.579340'),
  Decimal('-2.6543209877')),
 (datetime.date(2026, 2, 13),
  Decimal('63.050000'),
  Decimal('66258.529549'),
  Decimal('-0.0475586557')),
 (datetime.date(2026, 2, 17),
  Decimal('62.530000'),
  Decimal('68859.776187'),
  Decimal('-0.8247422680')),
 (datetime.date(2026, 2, 18),
  Decimal('65.330000'),
  Decimal('67559.295733'),
  Decimal('4.4778506317')),
 (datetime.date(2026, 2, 19),
  Decimal('66.660000'),
  Decimal('66426.619535'),
  Decimal('2.0358181540')),
 (datetime.date(2026, 2, 20),
  Decimal('66.690000'),
  Decimal('66976.029364'),
  Decimal('0.0450045005')),
 (datetime.date(2026, 2, 23),
  Decimal('66.360000'),
  Decimal('65192.188701'),
  Decimal('-0.4948268106')),
 (datetime.date(2026, 2, 24),
  Decimal('65.620000'),
  Decimal('64737.901970'),
  Decimal('-1.1151295961')),
 (datetime.date(2026, 2, 25),
  Decimal('65.300000'),
  Decimal('64073.548946'),
  Decimal('-0.4876562024')),
 (datetime.date(2026, 2, 26),
  Decimal('65.100000'),
  Decimal('67850.105213'),
  Decimal('-0.3062787136')),
 (datetime.date(2026, 2, 27),
  Decimal('66.960000'),
  Decimal('67496.841640'),
  Decimal('2.8571428571')),
 (datetime.date(2026, 3, 2),
  Decimal('71.130000'),
  Decimal('65824.421669'),
  Decimal('6.2275985663')),
 (datetime.date(2026, 3, 3),
  Decimal('74.480000'),
  Decimal('68815.936339'),
  Decimal('4.7096864895')),
 (datetime.date(2026, 3, 4),
  Decimal('74.580000'),
  Decimal('68287.463034'),
  Decimal('0.1342642320')),
 (datetime.date(2026, 3, 5),
  Decimal('80.880000'),
  Decimal('72752.301567'),
  Decimal('8.4473049075')),
 (datetime.date(2026, 3, 6),
  Decimal('90.770000'),
  Decimal('70868.218196'),
  Decimal('12.2279920870')),
 (datetime.date(2026, 3, 9),
  Decimal('94.650000'),
  Decimal('66042.751079'),
  Decimal('4.2745400463')),
 (datetime.date(2026, 3, 10),
  Decimal('83.710000'),
  Decimal('68430.609260'),
  Decimal('-11.5583729530')),
 (datetime.date(2026, 3, 11),
  Decimal('86.800000'),
  Decimal('69849.203531'),
  Decimal('3.6913152550')),
 (datetime.date(2026, 3, 12),
  Decimal('95.610000'),
  Decimal('70028.959876'),
  Decimal('10.1497695853')),
 (datetime.date(2026, 3, 13),
  Decimal('98.480000'),
  Decimal('70417.193886'),
  Decimal('3.0017780567')),
 (datetime.date(2026, 3, 16),
  Decimal('93.390000'),
  Decimal('72934.294072'),
  Decimal('-5.1685621446')),
 (datetime.date(2026, 3, 17),
  Decimal('96.010000'),
  Decimal('74679.370908'),
  Decimal('2.8054395546')),
 (datetime.date(2026, 3, 18),
  Decimal('96.120000'),
  Decimal('74004.690809'),
  Decimal('0.1145713988')),
 (datetime.date(2026, 3, 19),
  Decimal('96.110000'),
  Decimal('71220.047303'),
  Decimal('-0.0104036621')),
 (datetime.date(2026, 3, 20),
  Decimal('98.710000'),
  Decimal('69936.199321'),
  Decimal('2.7052335865')),
 (datetime.date(2026, 3, 23),
  Decimal('89.330000'),
  Decimal('67933.429481'),
  Decimal('-9.5025833249')),
 (datetime.date(2026, 3, 24),
  Decimal('93.180000'),
  Decimal('70987.251854'),
  Decimal('4.3098623083')),
 (datetime.date(2026, 3, 25),
  Decimal('91.510000'),
  Decimal('70528.863456'),
  Decimal('-1.7922300923')),
 (datetime.date(2026, 3, 26),
  Decimal('96.180000'),
  Decimal('71303.585451'),
  Decimal('5.1032674025')),
 (datetime.date(2026, 3, 27),
  Decimal('101.260000'),
  Decimal('68727.212290'),
  Decimal('5.2817633604')),
 (datetime.date(2026, 3, 30),
  Decimal('104.690000'),
  Decimal('65947.031926'),
  Decimal('3.3873197709')),
 (datetime.date(2026, 3, 31),
  Decimal('102.860000'),
  Decimal('66691.271478'),
  Decimal('-1.7480179578')),
 (datetime.date(2026, 4, 1),
  Decimal('101.900000'),
  Decimal('68107.474564'),
  Decimal('-0.9333074081')),
 (datetime.date(2026, 4, 2),
  Decimal('113.230000'),
  Decimal('67959.875247'),
  Decimal('11.1187438665')),
 (datetime.date(2026, 4, 6),
  Decimal('114.010000'),
  Decimal('69002.038479'),
  Decimal('0.6888633754')),
 (datetime.date(2026, 4, 7),
  Decimal('114.580000'),
  Decimal('68672.246575'),
  Decimal('0.4999561442')),
 (datetime.date(2026, 4, 8),
  Decimal('96.170000'),
  Decimal('71661.763724'),
  Decimal('-16.0673765055')),
 (datetime.date(2026, 4, 9),
  Decimal('99.620000'),
  Decimal('70644.794162'),
  Decimal('3.5873973173')),
 (datetime.date(2026, 4, 10),
  Decimal('98.340000'),
  Decimal('71367.802917'),
  Decimal('-1.2848825537')),
 (datetime.date(2026, 4, 13),
  Decimal('100.720000'),
  Decimal('70660.639612'),
  Decimal('2.4201749034')),
 (datetime.date(2026, 4, 14),
  Decimal('93.070000'),
  Decimal('74481.641429'),
  Decimal('-7.5953137411')),
 (datetime.date(2026, 4, 15),
  Decimal('93.040000'),
  Decimal('74297.347595'),
  Decimal('-0.0322338025')),
 (datetime.date(2026, 4, 16),
  Decimal('96.460000'),
  Decimal('74826.313088'),
  Decimal('3.6758383491')),
 (datetime.date(2026, 4, 17),
  Decimal('85.910000'),
  Decimal('75111.956745'),
  Decimal('-10.9371760315')),
 (datetime.date(2026, 4, 20),
  Decimal('91.060000'),
  Decimal('73841.021738'),
  Decimal('5.9946455593')),
 (datetime.date(2026, 4, 21),
  Decimal('93.640000'),
  Decimal('75858.035468'),
  Decimal('2.8332967274')),
 (datetime.date(2026, 4, 22),
  Decimal('94.760000'),
  Decimal('76326.191702'),
  Decimal('1.1960700555')),
 (datetime.date(2026, 4, 23),
  Decimal('99.270000'),
  Decimal('78238.816750'),
  Decimal('4.7593921486')),
 (datetime.date(2026, 4, 24),
  Decimal('98.420000'),
  Decimal('78275.325827'),
  Decimal('-0.8562506296')),
 (datetime.date(2026, 4, 27),
  Decimal('99.890000'),
  Decimal('78637.743562'),
  Decimal('1.4935988620')),
 (datetime.date(2026, 4, 28),
  Decimal('103.450000'),
  Decimal('77366.784422'),
  Decimal('3.5639203123')),
 (datetime.date(2026, 4, 29),
  Decimal('110.470000'),
  Decimal('76331.864435'),
  Decimal('6.7858869019')),
 (datetime.date(2026, 4, 30),
  Decimal('108.640000'),
  Decimal('75784.957436'),
  Decimal('-1.6565583416')),
 (datetime.date(2026, 5, 1),
  Decimal('105.380000'),
  Decimal('76296.796484'),
  Decimal('-3.0007363770')),
 (datetime.date(2026, 5, 4),
  Decimal('109.760000'),
  Decimal('78512.092465'),
  Decimal('4.1563864111')),
 (datetime.date(2026, 5, 5),
  Decimal('105.660000'),
  Decimal('79825.875113'),
  Decimal('-3.7354227405')),
 (datetime.date(2026, 5, 6),
  Decimal('98.750000'),
  Decimal('80913.961375'),
  Decimal('-6.5398447852')),
 (datetime.date(2026, 5, 7),
  Decimal('98.380000'),
  Decimal('81436.859368'),
  Decimal('-0.3746835443')),
 (datetime.date(2026, 5, 8),
  Decimal('98.870000'),
  Decimal('80024.907672'),
  Decimal('0.4980687132')),
 (datetime.date(2026, 5, 11),
  Decimal('101.560000'),
  Decimal('82018.371124'),
  Decimal('2.7207444119')),
 (datetime.date(2026, 5, 12),
  Decimal('105.780000'),
  Decimal('81627.566050'),
  Decimal('4.1551792044')),
 (datetime.date(2026, 5, 13),
  Decimal('104.520000'),
  Decimal('80482.143778'),
  Decimal('-1.1911514464')),
 (datetime.date(2026, 5, 14),
  Decimal('104.660000'),
  Decimal('79288.842087'),
  Decimal('0.1339456563')),
 (datetime.date(2026, 5, 15),
  Decimal('108.990000'),
  Decimal('81059.115954'),
  Decimal('4.1372061915')),
 (datetime.date(2026, 5, 18),
  Decimal('112.250000'),
  Decimal('77428.518661'),
  Decimal('2.9911001009')),
 (datetime.date(2026, 5, 19),
  Decimal('112.090000'),
  Decimal('76959.405715'),
  Decimal('-0.1425389755')),
 (datetime.date(2026, 5, 20),
  Decimal('101.690000'),
  Decimal('76758.731559'),
  Decimal('-9.2782585422')),
 (datetime.date(2026, 5, 21),
  Decimal('100.200000'),
  Decimal('77470.396149'),
  Decimal('-1.4652374865')),
 (datetime.date(2026, 5, 22),
  Decimal('100.350000'),
  Decimal('77550.383083'),
  Decimal('0.1497005988')),
 (datetime.date(2026, 5, 26),
  Decimal('97.630000'),
  Decimal('77258.399124'),
  Decimal('-2.7105132038')),
 (datetime.date(2026, 5, 27),
  Decimal('92.350000'),
  Decimal('75851.104096'),
  Decimal('-5.4081737171')),
 (datetime.date(2026, 5, 28),
  Decimal('92.650000'),
  Decimal('74339.616947'),
  Decimal('0.3248511099')),
 (datetime.date(2026, 5, 29),
  Decimal('91.160000'),
  Decimal('73651.642551'),
  Decimal('-1.6082029142')),
 (datetime.date(2026, 6, 1),
  Decimal('95.960000'),
  Decimal('73598.668124'),
  Decimal('5.2654673102')),
 (datetime.date(2026, 6, 2),
  Decimal('97.470000'),
  Decimal('71320.293065'),
  Decimal('1.5735723218')),
 (datetime.date(2026, 6, 3),
  Decimal('99.760000'),
  Decimal('66727.264155'),
  Decimal('2.3494408536')),
 (datetime.date(2026, 6, 4),
  Decimal('96.830000'),
  Decimal('64046.610646'),
  Decimal('-2.9370489174')),
 (datetime.date(2026, 6, 5),
  Decimal('94.320000'),
  Decimal('63810.659238'),
  Decimal('-2.5921718476')),
 (datetime.date(2026, 6, 8),
  Decimal('95.000000'),
  Decimal('63273.537431'),
  Decimal('0.7209499576')),
 (datetime.date(2026, 6, 9),
  Decimal('91.900000'),
  Decimal('63069.147793'),
  Decimal('-3.2631578947')),
 (datetime.date(2026, 6, 10),
  Decimal('93.680000'),
  Decimal('61669.763842'),
  Decimal('1.9368879217')),
 (datetime.date(2026, 6, 11),
  Decimal('91.580000'),
  Decimal('61480.144433'),
  Decimal('-2.2416737831')),
 (datetime.date(2026, 6, 12),
  Decimal('88.620000'),
  Decimal('63555.661811'),
  Decimal('-3.2321467569')),
 (datetime.date(2026, 6, 15),
  Decimal('84.650000'),
  Decimal('65709.310946'),
  Decimal('-4.4798013992')),
 (datetime.date(2026, 6, 16),
  Decimal('79.800000'),
  Decimal('66292.501179'),
  Decimal('-5.7294743060')),
 (datetime.date(2026, 6, 17),
  Decimal('80.650000'),
  Decimal('65619.280800'),
  Decimal('1.0651629073')),
 (datetime.date(2026, 6, 18),
  Decimal('80.350000'),
  Decimal('64444.545330'),
  Decimal('-0.3719776813')),
 (datetime.date(2026, 6, 22),
  Decimal('78.940000'),
  Decimal('63255.485253'),
  Decimal('-1.7548226509')),
 (datetime.date(2026, 6, 23),
  Decimal('74.620000'),
  Decimal('63937.285264'),
  Decimal('-5.4725107677')),
 (datetime.date(2026, 6, 24),
  Decimal('71.420000'),
  Decimal('62662.292019'),
  Decimal('-4.2883945323')),
 (datetime.date(2026, 6, 25),
  Decimal('72.670000'),
  Decimal('60989.573522'),
  Decimal('1.7502100252')),
 (datetime.date(2026, 6, 26),
  Decimal('70.300000'),
  Decimal('59726.736535'),
  Decimal('-3.2613182882')),
 (datetime.date(2026, 6, 29),
  Decimal('71.870000'),
  Decimal('59494.606386'),
  Decimal('2.2332859175')),
 (datetime.date(2026, 6, 30),

In [55]:
cursor.execute("""
SELECT
    c.date,
    c.coin_id,
    c.price_usd AS crypto_price,
    s.close AS nifty_close
FROM crypto_prices c
JOIN stock_prices s
    ON c.date = s.date
WHERE s.ticker = '^NSEI'
AND c.coin_id IN ('bitcoin', 'ethereum', 'tether')
AND c.date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY c.date, c.coin_id
""")

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3),
  'bitcoin',
  Decimal('120514.577856'),
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 3),
  'ethereum',
  Decimal('4484.180377'),
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 3),
  'tether',
  Decimal('1.000469'),
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 6),
  'bitcoin',
  Decimal('123488.730597'),
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 6),
  'ethereum',
  Decimal('4513.310148'),
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 6),
  'tether',
  Decimal('1.000227'),
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 7),
  'bitcoin',
  Decimal('124739.810888'),
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 7),
  'ethereum',
  Decimal('4690.837856'),
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 7),
  'tether',
  Decimal('1.000319'),
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 8),
  'bitcoin',
  Decimal('121463.118082'),
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 8),
  'ethereum',
  Decimal('4453.781266'),
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 8),
  'tether',
  Decimal('1.000349'),
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 9),
  'bitcoin',
  Decimal('123342.984698'),
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 9),
  'ethereum',
  Decimal('4526.062095'),
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 9),
  'tether',
  Decimal('1.000249'),
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 10),
  'bitcoin',
  Decimal('121718.667577'),
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 10),
  'ethereum',
  Decimal('4368.419617'),
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 10),
  'tether',
  Decimal('1.000497'),
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 13),
  'bitcoin',
  Decimal('115060.884178'),
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 13),
  'ethereum',
  Decimal('4151.918863'),
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 13),
  'tether',
  Decimal('1.001209'),
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 14),
  'bitcoin',
  Decimal('115226.584290'),
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 14),
  'ethereum',
  Decimal('4245.447077'),
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 14),
  'tether',
  Decimal('1.001022'),
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 15),
  'bitcoin',
  Decimal('113066.350785'),
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 15),
  'ethereum',
  Decimal('4126.235353'),
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 15),
  'tether',
  Decimal('1.000663'),
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 16),
  'bitcoin',
  Decimal('110844.404172'),
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 16),
  'ethereum',
  Decimal('3991.544236'),
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 16),
  'tether',
  Decimal('1.000762'),
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 17),
  'bitcoin',
  Decimal('108168.173534'),
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 17),
  'ethereum',
  Decimal('3893.756038'),
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 17),
  'tether',
  Decimal('1.000505'),
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 20),
  'bitcoin',
  Decimal('108655.505250'),
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 20),
  'ethereum',
  Decimal('3982.355861'),
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 20),
  'tether',
  Decimal('1.000593'),
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 21),
  'bitcoin',
  Decimal('110535.863014'),
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 21),
  'ethereum',
  Decimal('3980.073280'),
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 21),
  'tether',
  Decimal('1.000533'),
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 22), 'bitcoin', Decimal('108301.754625'), None),
 (datetime.date(2025, 10, 22), 'ethereum', Decimal('3866.151783'), None),
 (datetime.date(2025, 10, 22), 'tether', Decimal('1.000546'), None),
 (datetime.date(2025, 10, 23),
  'bitcoin',
  Decimal('107591.460509'),
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 23),
  'ethereum',
  Decimal('3805.881864'),
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 23),
  'tether',
  Decimal('1.000383'),
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 24),
  'bitcoin',
  Decimal('110109.305225'),
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 24),
  'ethereum',
  Decimal('3857.590009'),
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 24),
  'tether',
  Decimal('1.000449'),
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 27),
  'bitcoin',
  Decimal('114419.221697'),
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 27),
  'ethereum',
  Decimal('4158.567622'),
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 27),
  'tether',
  Decimal('1.000095'),
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 28),
  'bitcoin',
  Decimal('114085.331238'),
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 28),
  'ethereum',
  Decimal('4117.287078'),
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 28),
  'tether',
  Decimal('1.000133'),
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 29),
  'bitcoin',
  Decimal('112893.852036'),
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 29),
  'ethereum',
  Decimal('3978.812010'),
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 29),
  'tether',
  Decimal('1.000317'),
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 30),
  'bitcoin',
  Decimal('110026.087620'),
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 30),
  'ethereum',
  Decimal('3902.801947'),
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 30),
  'tether',
  Decimal('1.000329'),
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 31),
  'bitcoin',
  Decimal('108409.379925'),
  Decimal('25722.099609')),
 (datetime.date(2025, 10, 31),
  'ethereum',
  Decimal('3801.551505'),
  Decimal('25722.099609')),
 (datetime.date(2025, 10, 31),
  'tether',
  Decimal('1.000251'),
  Decimal('25722.099609')),
 (datetime.date(2025, 11, 3),
  'bitcoin',
  Decimal('110499.522383'),
  Decimal('25763.349609')),
 (datetime.date(2025, 11, 3),
  'ethereum',
  Decimal('3905.342930'),
  Decimal('25763.349609')),
 (datetime.date(2025, 11, 3),
  'tether',
  Decimal('0.999994'),
  Decimal('25763.349609')),
 (datetime.date(2025, 11, 4),
  'bitcoin',
  Decimal('106451.706533'),
  Decimal('25597.650391')),
 (datetime.date(2025, 11, 4),
  'ethereum',
  Decimal('3600.363768'),
  Decimal('25597.650391')),
 (datetime.date(2025, 11, 4),
  'tether',
  Decimal('0.999908'),
  Decimal('25597.650391')),
 (datetime.date(2025, 11, 5), 'bitcoin', Decimal('101480.766596'), None),
 (datetime.date(2025, 11, 5), 'ethereum', Decimal('3285.231840'), None),
 (datetime.date(2025, 11, 5), 'tether', Decimal('1.000017'), None),
 (datetime.date(2025, 11, 6),
  'bitcoin',
  Decimal('103878.933600'),
  Decimal('25509.699219')),
 (datetime.date(2025, 11, 6),
  'ethereum',
  Decimal('3425.969806'),
  Decimal('25509.699219')),
 (datetime.date(2025, 11, 6),
  'tether',
  Decimal('1.000051'),
  Decimal('25509.699219')),
 (datetime.date(2025, 11, 7),
  'bitcoin',
  Decimal('101261.645510'),
  Decimal('25492.300781')),
 (datetime.date(2025, 11, 7),
  'ethereum',
  Decimal('3312.450307'),
  Decimal('25492.300781')),
 (datetime.date(2025, 11, 7),
  'tether',
  Decimal('0.999615'),
  Decimal('25492.300781')),
 (datetime.date(2025, 11, 10),
  'bitcoin',
  Decimal('104610.228536'),
  Decimal('25574.349609')),
 (datetime.date(2025, 11, 10),
  'ethereum',
  Decimal('3578.802306'),
  Decimal('25574.349609')),
 (datetime.date(2025, 11, 10),
  'tether',
  Decimal('0.999934'),
  Decimal('25574.349609')),
 (datetime.date(2025, 11, 11),
  'bitcoin',
  Decimal('105951.496000'),
  Decimal('25694.949219')),
 (datetime.date(2025, 11, 11),
  'ethereum',
  Decimal('3566.049867'),
  Decimal('25694.949219')),
 (datetime.date(2025, 11, 11),
  'tether',
  Decimal('0.999649'),
  Decimal('25694.949219')),
 (datetime.date(2025, 11, 12),
  'bitcoin',
  Decimal('103112.210062'),
  Decimal('25875.800781')),
 (datetime.date(2025, 11, 12),
  'ethereum',
  Decimal('3416.071509'),
  Decimal('25875.800781')),
 (datetime.date(2025, 11, 12),
  'tether',
  Decimal('0.999437'),
  Decimal('25875.800781')),
 (datetime.date(2025, 11, 13),
  'bitcoin',
  Decimal('101633.694316'),
  Decimal('25879.150391')),
 (datetime.date(2025, 11, 13),
  'ethereum',
  Decimal('3412.543237'),
  Decimal('25879.150391')),
 (datetime.date(2025, 11, 13),
  'tether',
  Decimal('0.999850'),
  Decimal('25879.150391')),
 (datetime.date(2025, 11, 14),
  'bitcoin',
  Decimal('99480.307091'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 14),
  'ethereum',
  Decimal('3223.175779'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 14),
  'tether',
  Decimal('0.999556'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 17),
  'bitcoin',
  Decimal('94188.276689'),
  Decimal('26013.449219')),
 (datetime.date(2025, 11, 17),
  'ethereum',
  Decimal('3091.905046'),
  Decimal('26013.449219')),
 (datetime.date(2025, 11, 17),
  'tether',
  Decimal('0.999466'),
  Decimal('26013.449219')),
 (datetime.date(2025, 11, 18),
  'bitcoin',
  Decimal('92100.364524'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 18),
  'ethereum',
  Decimal('3026.218255'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 18),
  'tether',
  Decimal('0.999013'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 19),
  'bitcoin',
  Decimal('92903.180085'),
  Decimal('26052.650391')),
 (datetime.date(2025, 11, 19),
  'ethereum',
  Decimal('3121.513848'),
  Decimal('26052.650391')),
 (datetime.date(2025, 11, 19),
  'tether',
  Decimal('0.999514'),
  Decimal('26052.650391')),
 (datetime.date(2025, 11, 20),
  'bitcoin',
  Decimal('91408.357334'),
  Decimal('26192.150391')),
 (datetime.date(2025, 11, 20),
  'ethereum',
  Decimal('3020.935788'),
  Decimal('26192.150391')),
 (datetime.date(2025, 11, 20),
  'tether',
  Decimal('0.999185'),
  Decimal('26192.150391')),
 (datetime.date(2025, 11, 21),
  'bitcoin',
  Decimal('86618.471559'),
  Decimal('26068.150391')),
 (datetime.date(2025, 11, 21),
  'ethereum',
  Decimal('2832.530798'),
  Decimal('26068.150391')),
 (datetime.date(2025, 11, 21),
  'tether',
  Decimal('0.998945'),
  Decimal('26068.150391')),
 (datetime.date(2025, 11, 24),
  'bitcoin',
  Decimal('86740.117739'),
  Decimal('25959.500000')),
 (datetime.date(2025, 11, 24),
  'ethereum',
  Decimal('2798.913101'),
  Decimal('25959.500000')),
 (datetime.date(2025, 11, 24),
  'tether',
  Decimal('0.999823'),
  Decimal('25959.500000')),
 (datetime.date(2025, 11, 25),
  'bitcoin',
  Decimal('88256.043956'),
  Decimal('25884.800781')),
 (datetime.date(2025, 11, 25),
  'ethereum',
  Decimal('2952.334907'),
  Decimal('25884.800781')),
 (datetime.date(2025, 11, 25),
  'tether',
  Decimal('0.999850'),
  Decimal('25884.800781')),
 (datetime.date(2025, 11, 26),
  'bitcoin',
  Decimal('87317.004551'),
  Decimal('26205.300781')),
 (datetime.date(2025, 11, 26),
  'ethereum',
  Decimal('2958.573218'),
  Decimal('26205.300781')),
 (datetime.date(2025, 11, 26),
  'tether',
  Decimal('0.999733'),
  Decimal('26205.300781')),
 (datetime.date(2025, 11, 27),
  'bitcoin',
  Decimal('90515.943578'),
  Decimal('26215.550781')),
 (datetime.date(2025, 11, 27),
  'ethereum',
  Decimal('3026.421535'),
  Decimal('26215.550781')),
 (datetime.date(2025, 11, 27),
  'tether',
  Decimal('0.999971'),
  Decimal('26215.550781')),
 (datetime.date(2025, 11, 28),
  'bitcoin',
  Decimal('91323.628276'),
  Decimal('26202.949219')),
 (datetime.date(2025, 11, 28),
  'ethereum',
  Decimal('3014.819850'),
  Decimal('26202.949219')),
 (datetime.date(2025, 11, 28),
  'tether',
  Decimal('0.999985'),
  Decimal('26202.949219')),
 (datetime.date(2025, 12, 1),
  'bitcoin',
  Decimal('90359.868732'),
  Decimal('26175.750000')),
 (datetime.date(2025, 12, 1),
  'ethereum',
  Decimal('2990.797383'),
  Decimal('26175.750000')),
 (datetime.date(2025, 12, 1),
  'tether',
  Decimal('1.000193'),
  Decimal('26175.750000')),
 (datetime.date(2025, 12, 2),
  'bitcoin',
  Decimal('86303.897664'),
  Decimal('26032.199219')),
 (datetime.date(2025, 12, 2),
  'ethereum',
  Decimal('2796.733869'),
  Decimal('26032.199219')),
 (datetime.date(2025, 12, 2),
  'tether',
  Decimal('1.000077'),
  Decimal('26032.199219')),
 (datetime.date(2025, 12, 3),
  'bitcoin',
  Decimal('91320.079425'),
  Decimal('25986.000000')),
 (datetime.date(2025, 12, 3),
  'ethereum',
  Decimal('2997.602427'),
  Decimal('25986.000000')),
 (datetime.date(2025, 12, 3),
  'tether',
  Decimal('1.000359'),
  Decimal('25986.000000')),
 (datetime.date(2025, 12, 4),
  'bitcoin',
  Decimal('93428.594515'),
  Decimal('26033.750000')),
 (datetime.date(2025, 12, 4),
  'ethereum',
  Decimal('3188.881945'),
  Decimal('26033.750000')),
 (datetime.date(2025, 12, 4),
  'tether',
  Decimal('1.000287'),
  Decimal('26033.750000')),
 (datetime.date(2025, 12, 5),
  'bitcoin',
  Decimal('92119.190478'),
  Decimal('26186.449219')),
 (datetime.date(2025, 12, 5),
  'ethereum',
  Decimal('3134.348641'),
  Decimal('26186.449219')),
 (datetime.date(2025, 12, 5),
  'tether',
  Decimal('1.000194'),
  Decimal('26186.449219')),
 (datetime.date(2025, 12, 8),
  'bitcoin',
  Decimal('90398.448757'),
  Decimal('25960.550781')),
 (datetime.date(2025, 12, 8),
  'ethereum',
  Decimal('3060.994832'),
  Decimal('25960.550781')),
 (datetime.date(2025, 12, 8),
  'tether',
  Decimal('1.000217'),
  Decimal('25960.550781')),
 (datetime.date(2025, 12, 9),
  'bitcoin',
  Decimal('90626.037343'),
  Decimal('25839.650391')),
 (datetime.date(2025, 12, 9),
  'ethereum',
  Decimal('3123.805252'),
  Decimal('25839.650391')),
 (datetime.date(2025, 12, 9),
  'tether',
  Decimal('1.000116'),
  Decimal('25839.650391')),
 (datetime.date(2025, 12, 10),
  'bitcoin',
  Decimal('92686.104020'),
  Decimal('25758.000000')),
 (datetime.date(2025, 12, 10),
  'ethereum',
  Decimal('3318.720945'),
  Decimal('25758.000000')),
 (datetime.date(2025, 12, 10),
  'tether',
  Decimal('1.000103'),
  Decimal('25758.000000')),
 (datetime.date(2025, 12, 11),
  'bitcoin',
  Decimal('91986.581072'),
  Decimal('25898.550781')),
 (datetime.date(2025, 12, 11),
  'ethereum',
  Decimal('3323.292013'),
  Decimal('25898.550781')),
 (datetime.date(2025, 12, 11),
  'tether',
  Decimal('1.000220'),
  Decimal('25898.550781')),
 (datetime.date(2025, 12, 12),
  'bitcoin',
  Decimal('92525.868003'),
  Decimal('26046.949219')),
 (datetime.date(2025, 12, 12),
  'ethereum',
  Decimal('3238.413615'),
  Decimal('26046.949219')),
 (datetime.date(2025, 12, 12),
  'tether',
  Decimal('1.000198'),
  Decimal('26046.949219')),
 (datetime.date(2025, 12, 15),
  'bitcoin',
  Decimal('88184.410931'),
  Decimal('26027.300781')),
 (datetime.date(2025, 12, 15),
  'ethereum',
  Decimal('3063.545453'),
  Decimal('26027.300781')),
 (datetime.date(2025, 12, 15),
  'tether',
  Decimal('1.000190'),
  Decimal('26027.300781')),
 (datetime.date(2025, 12, 16),
  'bitcoin',
  Decimal('86413.221381'),
  Decimal('25860.099609')),
 (datetime.date(2025, 12, 16),
  'ethereum',
  Decimal('2963.894557'),
  Decimal('25860.099609')),
 (datetime.date(2025, 12, 16),
  'tether',
  Decimal('1.000036'),
  Decimal('25860.099609')),
 (datetime.date(2025, 12, 17),
  'bitcoin',
  Decimal('87719.681398'),
  Decimal('25818.550781')),
 (datetime.date(2025, 12, 17),
  'ethereum',
  Decimal('2957.860249'),
  Decimal('25818.550781')),
 (datetime.date(2025, 12, 17),
  'tether',
  Decimal('0.999913'),
  Decimal('25818.550781')),
 (datetime.date(2025, 12, 18),
  'bitcoin',
  Decimal('86196.821373'),
  Decimal('25815.550781')),
 (datetime.date(2025, 12, 18),
  'ethereum',
  Decimal('2832.468327'),
  Decimal('25815.550781')),
 (datetime.date(2025, 12, 18),
  'tether',
  Decimal('0.999820'),
  Decimal('25815.550781')),
 (datetime.date(2025, 12, 19),
  'bitcoin',
  Decimal('85450.179648'),
  Decimal('25966.400391')),
 (datetime.date(2025, 12, 19),
  'ethereum',
  Decimal('2826.673248'),
  Decimal('25966.400391')),
 (datetime.date(2025, 12, 19),
  'tether',
  Decimal('0.999559'),
  Decimal('25966.400391')),
 (datetime.date(2025, 12, 22),
  'bitcoin',
  Decimal('88672.329679'),
  Decimal('26172.400391')),
 (datetime.date(2025, 12, 22),
  'ethereum',
  Decimal('3004.220492'),
  Decimal('26172.400391')),
 (datetime.date(2025, 12, 22),
  'tether',
  Decimal('0.999783'),
  Decimal('26172.400391')),
 (datetime.date(2025, 12, 23),
  'bitcoin',
  Decimal('88489.724042'),
  Decimal('26177.150391')),
 (datetime.date(2025, 12, 23),
  'ethereum',
  Decimal('3005.375558'),
  Decimal('26177.150391')),
 (datetime.date(2025, 12, 23),
  'tether',
  Decimal('0.999527'),
  Decimal('26177.150391')),
 (datetime.date(2025, 12, 24),
  'bitcoin',
  Decimal('87496.146692'),
  Decimal('26142.099609')),
 (datetime.date(2025, 12, 24),
  'ethereum',
  Decimal('2965.218785'),
  Decimal('26142.099609')),
 (datetime.date(2025, 12, 24),
  'tether',
  Decimal('0.999476'),
  Decimal('26142.099609')),
 (datetime.date(2025, 12, 26),
  'bitcoin',
  Decimal('87192.234737'),
  Decimal('26042.300781')),
 (datetime.date(2025, 12, 26),
  'ethereum',
  Decimal('2901.680790'),
  Decimal('26042.300781')),
 (datetime.date(2025, 12, 26),
  'tether',
  Decimal('0.999512'),
  Decimal('26042.300781')),
 (datetime.date(2025, 12, 29),
  'bitcoin',
  Decimal('87867.039434'),
  Decimal('25942.099609')),
 (datetime.date(2025, 12, 29),
  'ethereum',
  Decimal('2948.831769'),
  Decimal('25942.099609')),
 (datetime.date(2025, 12, 29),
  'tether',
  Decimal('0.999355'),
  Decimal('25942.099609')),
 (datetime.date(2025, 12, 30),
  'bitcoin',
  Decimal('87154.682406'),
  Decimal('25938.849609')),
 (datetime.date(2025, 12, 30),
  'ethereum',
  Decimal('2934.356281'),
  Decimal('25938.849609')),
 (datetime.date(2025, 12, 30),
  'tether',
  Decimal('0.998910'),
  Decimal('25938.849609')),
 (datetime.date(2025, 12, 31),
  'bitcoin',
  Decimal('88363.722236'),
  Decimal('26129.599609')),
 (datetime.date(2025, 12, 31),
  'ethereum',
  Decimal('2967.980414'),
  Decimal('26129.599609')),
 (datetime.date(2025, 12, 31),
  'tether',
  Decimal('0.999032'),
  Decimal('26129.599609'))]

In [63]:
top3_ids = [row[0] for row in top3]

placeholders = ', '.join(['%s'] * len(top3_ids))

query25 = f"""
SELECT
    c.date,
    c.coin_id,
    c.price_usd AS crypto_price,
    s.close AS nifty_close
FROM crypto_prices c
JOIN stock_prices s
    ON c.date = s.date
WHERE s.ticker = '^NSEI'
AND c.coin_id IN ({placeholders})
AND c.date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY c.date, c.coin_id
"""

cursor.execute(query25, top3_ids)

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3),
  'bitcoin',
  Decimal('120514.577856'),
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 3),
  'ethereum',
  Decimal('4484.180377'),
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 3),
  'tether',
  Decimal('1.000469'),
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 6),
  'bitcoin',
  Decimal('123488.730597'),
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 6),
  'ethereum',
  Decimal('4513.310148'),
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 6),
  'tether',
  Decimal('1.000227'),
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 7),
  'bitcoin',
  Decimal('124739.810888'),
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 7),
  'ethereum',
  Decimal('4690.837856'),
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 7),
  'tether',
  Decimal('1.000319'),
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 8),
  'bitcoin',
  Decimal('121463.118082'),
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 8),
  'ethereum',
  Decimal('4453.781266'),
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 8),
  'tether',
  Decimal('1.000349'),
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 9),
  'bitcoin',
  Decimal('123342.984698'),
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 9),
  'ethereum',
  Decimal('4526.062095'),
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 9),
  'tether',
  Decimal('1.000249'),
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 10),
  'bitcoin',
  Decimal('121718.667577'),
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 10),
  'ethereum',
  Decimal('4368.419617'),
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 10),
  'tether',
  Decimal('1.000497'),
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 13),
  'bitcoin',
  Decimal('115060.884178'),
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 13),
  'ethereum',
  Decimal('4151.918863'),
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 13),
  'tether',
  Decimal('1.001209'),
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 14),
  'bitcoin',
  Decimal('115226.584290'),
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 14),
  'ethereum',
  Decimal('4245.447077'),
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 14),
  'tether',
  Decimal('1.001022'),
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 15),
  'bitcoin',
  Decimal('113066.350785'),
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 15),
  'ethereum',
  Decimal('4126.235353'),
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 15),
  'tether',
  Decimal('1.000663'),
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 16),
  'bitcoin',
  Decimal('110844.404172'),
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 16),
  'ethereum',
  Decimal('3991.544236'),
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 16),
  'tether',
  Decimal('1.000762'),
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 17),
  'bitcoin',
  Decimal('108168.173534'),
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 17),
  'ethereum',
  Decimal('3893.756038'),
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 17),
  'tether',
  Decimal('1.000505'),
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 20),
  'bitcoin',
  Decimal('108655.505250'),
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 20),
  'ethereum',
  Decimal('3982.355861'),
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 20),
  'tether',
  Decimal('1.000593'),
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 21),
  'bitcoin',
  Decimal('110535.863014'),
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 21),
  'ethereum',
  Decimal('3980.073280'),
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 21),
  'tether',
  Decimal('1.000533'),
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 22), 'bitcoin', Decimal('108301.754625'), None),
 (datetime.date(2025, 10, 22), 'ethereum', Decimal('3866.151783'), None),
 (datetime.date(2025, 10, 22), 'tether', Decimal('1.000546'), None),
 (datetime.date(2025, 10, 23),
  'bitcoin',
  Decimal('107591.460509'),
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 23),
  'ethereum',
  Decimal('3805.881864'),
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 23),
  'tether',
  Decimal('1.000383'),
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 24),
  'bitcoin',
  Decimal('110109.305225'),
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 24),
  'ethereum',
  Decimal('3857.590009'),
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 24),
  'tether',
  Decimal('1.000449'),
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 27),
  'bitcoin',
  Decimal('114419.221697'),
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 27),
  'ethereum',
  Decimal('4158.567622'),
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 27),
  'tether',
  Decimal('1.000095'),
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 28),
  'bitcoin',
  Decimal('114085.331238'),
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 28),
  'ethereum',
  Decimal('4117.287078'),
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 28),
  'tether',
  Decimal('1.000133'),
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 29),
  'bitcoin',
  Decimal('112893.852036'),
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 29),
  'ethereum',
  Decimal('3978.812010'),
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 29),
  'tether',
  Decimal('1.000317'),
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 30),
  'bitcoin',
  Decimal('110026.087620'),
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 30),
  'ethereum',
  Decimal('3902.801947'),
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 30),
  'tether',
  Decimal('1.000329'),
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 31),
  'bitcoin',
  Decimal('108409.379925'),
  Decimal('25722.099609')),
 (datetime.date(2025, 10, 31),
  'ethereum',
  Decimal('3801.551505'),
  Decimal('25722.099609')),
 (datetime.date(2025, 10, 31),
  'tether',
  Decimal('1.000251'),
  Decimal('25722.099609')),
 (datetime.date(2025, 11, 3),
  'bitcoin',
  Decimal('110499.522383'),
  Decimal('25763.349609')),
 (datetime.date(2025, 11, 3),
  'ethereum',
  Decimal('3905.342930'),
  Decimal('25763.349609')),
 (datetime.date(2025, 11, 3),
  'tether',
  Decimal('0.999994'),
  Decimal('25763.349609')),
 (datetime.date(2025, 11, 4),
  'bitcoin',
  Decimal('106451.706533'),
  Decimal('25597.650391')),
 (datetime.date(2025, 11, 4),
  'ethereum',
  Decimal('3600.363768'),
  Decimal('25597.650391')),
 (datetime.date(2025, 11, 4),
  'tether',
  Decimal('0.999908'),
  Decimal('25597.650391')),
 (datetime.date(2025, 11, 5), 'bitcoin', Decimal('101480.766596'), None),
 (datetime.date(2025, 11, 5), 'ethereum', Decimal('3285.231840'), None),
 (datetime.date(2025, 11, 5), 'tether', Decimal('1.000017'), None),
 (datetime.date(2025, 11, 6),
  'bitcoin',
  Decimal('103878.933600'),
  Decimal('25509.699219')),
 (datetime.date(2025, 11, 6),
  'ethereum',
  Decimal('3425.969806'),
  Decimal('25509.699219')),
 (datetime.date(2025, 11, 6),
  'tether',
  Decimal('1.000051'),
  Decimal('25509.699219')),
 (datetime.date(2025, 11, 7),
  'bitcoin',
  Decimal('101261.645510'),
  Decimal('25492.300781')),
 (datetime.date(2025, 11, 7),
  'ethereum',
  Decimal('3312.450307'),
  Decimal('25492.300781')),
 (datetime.date(2025, 11, 7),
  'tether',
  Decimal('0.999615'),
  Decimal('25492.300781')),
 (datetime.date(2025, 11, 10),
  'bitcoin',
  Decimal('104610.228536'),
  Decimal('25574.349609')),
 (datetime.date(2025, 11, 10),
  'ethereum',
  Decimal('3578.802306'),
  Decimal('25574.349609')),
 (datetime.date(2025, 11, 10),
  'tether',
  Decimal('0.999934'),
  Decimal('25574.349609')),
 (datetime.date(2025, 11, 11),
  'bitcoin',
  Decimal('105951.496000'),
  Decimal('25694.949219')),
 (datetime.date(2025, 11, 11),
  'ethereum',
  Decimal('3566.049867'),
  Decimal('25694.949219')),
 (datetime.date(2025, 11, 11),
  'tether',
  Decimal('0.999649'),
  Decimal('25694.949219')),
 (datetime.date(2025, 11, 12),
  'bitcoin',
  Decimal('103112.210062'),
  Decimal('25875.800781')),
 (datetime.date(2025, 11, 12),
  'ethereum',
  Decimal('3416.071509'),
  Decimal('25875.800781')),
 (datetime.date(2025, 11, 12),
  'tether',
  Decimal('0.999437'),
  Decimal('25875.800781')),
 (datetime.date(2025, 11, 13),
  'bitcoin',
  Decimal('101633.694316'),
  Decimal('25879.150391')),
 (datetime.date(2025, 11, 13),
  'ethereum',
  Decimal('3412.543237'),
  Decimal('25879.150391')),
 (datetime.date(2025, 11, 13),
  'tether',
  Decimal('0.999850'),
  Decimal('25879.150391')),
 (datetime.date(2025, 11, 14),
  'bitcoin',
  Decimal('99480.307091'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 14),
  'ethereum',
  Decimal('3223.175779'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 14),
  'tether',
  Decimal('0.999556'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 17),
  'bitcoin',
  Decimal('94188.276689'),
  Decimal('26013.449219')),
 (datetime.date(2025, 11, 17),
  'ethereum',
  Decimal('3091.905046'),
  Decimal('26013.449219')),
 (datetime.date(2025, 11, 17),
  'tether',
  Decimal('0.999466'),
  Decimal('26013.449219')),
 (datetime.date(2025, 11, 18),
  'bitcoin',
  Decimal('92100.364524'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 18),
  'ethereum',
  Decimal('3026.218255'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 18),
  'tether',
  Decimal('0.999013'),
  Decimal('25910.050781')),
 (datetime.date(2025, 11, 19),
  'bitcoin',
  Decimal('92903.180085'),
  Decimal('26052.650391')),
 (datetime.date(2025, 11, 19),
  'ethereum',
  Decimal('3121.513848'),
  Decimal('26052.650391')),
 (datetime.date(2025, 11, 19),
  'tether',
  Decimal('0.999514'),
  Decimal('26052.650391')),
 (datetime.date(2025, 11, 20),
  'bitcoin',
  Decimal('91408.357334'),
  Decimal('26192.150391')),
 (datetime.date(2025, 11, 20),
  'ethereum',
  Decimal('3020.935788'),
  Decimal('26192.150391')),
 (datetime.date(2025, 11, 20),
  'tether',
  Decimal('0.999185'),
  Decimal('26192.150391')),
 (datetime.date(2025, 11, 21),
  'bitcoin',
  Decimal('86618.471559'),
  Decimal('26068.150391')),
 (datetime.date(2025, 11, 21),
  'ethereum',
  Decimal('2832.530798'),
  Decimal('26068.150391')),
 (datetime.date(2025, 11, 21),
  'tether',
  Decimal('0.998945'),
  Decimal('26068.150391')),
 (datetime.date(2025, 11, 24),
  'bitcoin',
  Decimal('86740.117739'),
  Decimal('25959.500000')),
 (datetime.date(2025, 11, 24),
  'ethereum',
  Decimal('2798.913101'),
  Decimal('25959.500000')),
 (datetime.date(2025, 11, 24),
  'tether',
  Decimal('0.999823'),
  Decimal('25959.500000')),
 (datetime.date(2025, 11, 25),
  'bitcoin',
  Decimal('88256.043956'),
  Decimal('25884.800781')),
 (datetime.date(2025, 11, 25),
  'ethereum',
  Decimal('2952.334907'),
  Decimal('25884.800781')),
 (datetime.date(2025, 11, 25),
  'tether',
  Decimal('0.999850'),
  Decimal('25884.800781')),
 (datetime.date(2025, 11, 26),
  'bitcoin',
  Decimal('87317.004551'),
  Decimal('26205.300781')),
 (datetime.date(2025, 11, 26),
  'ethereum',
  Decimal('2958.573218'),
  Decimal('26205.300781')),
 (datetime.date(2025, 11, 26),
  'tether',
  Decimal('0.999733'),
  Decimal('26205.300781')),
 (datetime.date(2025, 11, 27),
  'bitcoin',
  Decimal('90515.943578'),
  Decimal('26215.550781')),
 (datetime.date(2025, 11, 27),
  'ethereum',
  Decimal('3026.421535'),
  Decimal('26215.550781')),
 (datetime.date(2025, 11, 27),
  'tether',
  Decimal('0.999971'),
  Decimal('26215.550781')),
 (datetime.date(2025, 11, 28),
  'bitcoin',
  Decimal('91323.628276'),
  Decimal('26202.949219')),
 (datetime.date(2025, 11, 28),
  'ethereum',
  Decimal('3014.819850'),
  Decimal('26202.949219')),
 (datetime.date(2025, 11, 28),
  'tether',
  Decimal('0.999985'),
  Decimal('26202.949219')),
 (datetime.date(2025, 12, 1),
  'bitcoin',
  Decimal('90359.868732'),
  Decimal('26175.750000')),
 (datetime.date(2025, 12, 1),
  'ethereum',
  Decimal('2990.797383'),
  Decimal('26175.750000')),
 (datetime.date(2025, 12, 1),
  'tether',
  Decimal('1.000193'),
  Decimal('26175.750000')),
 (datetime.date(2025, 12, 2),
  'bitcoin',
  Decimal('86303.897664'),
  Decimal('26032.199219')),
 (datetime.date(2025, 12, 2),
  'ethereum',
  Decimal('2796.733869'),
  Decimal('26032.199219')),
 (datetime.date(2025, 12, 2),
  'tether',
  Decimal('1.000077'),
  Decimal('26032.199219')),
 (datetime.date(2025, 12, 3),
  'bitcoin',
  Decimal('91320.079425'),
  Decimal('25986.000000')),
 (datetime.date(2025, 12, 3),
  'ethereum',
  Decimal('2997.602427'),
  Decimal('25986.000000')),
 (datetime.date(2025, 12, 3),
  'tether',
  Decimal('1.000359'),
  Decimal('25986.000000')),
 (datetime.date(2025, 12, 4),
  'bitcoin',
  Decimal('93428.594515'),
  Decimal('26033.750000')),
 (datetime.date(2025, 12, 4),
  'ethereum',
  Decimal('3188.881945'),
  Decimal('26033.750000')),
 (datetime.date(2025, 12, 4),
  'tether',
  Decimal('1.000287'),
  Decimal('26033.750000')),
 (datetime.date(2025, 12, 5),
  'bitcoin',
  Decimal('92119.190478'),
  Decimal('26186.449219')),
 (datetime.date(2025, 12, 5),
  'ethereum',
  Decimal('3134.348641'),
  Decimal('26186.449219')),
 (datetime.date(2025, 12, 5),
  'tether',
  Decimal('1.000194'),
  Decimal('26186.449219')),
 (datetime.date(2025, 12, 8),
  'bitcoin',
  Decimal('90398.448757'),
  Decimal('25960.550781')),
 (datetime.date(2025, 12, 8),
  'ethereum',
  Decimal('3060.994832'),
  Decimal('25960.550781')),
 (datetime.date(2025, 12, 8),
  'tether',
  Decimal('1.000217'),
  Decimal('25960.550781')),
 (datetime.date(2025, 12, 9),
  'bitcoin',
  Decimal('90626.037343'),
  Decimal('25839.650391')),
 (datetime.date(2025, 12, 9),
  'ethereum',
  Decimal('3123.805252'),
  Decimal('25839.650391')),
 (datetime.date(2025, 12, 9),
  'tether',
  Decimal('1.000116'),
  Decimal('25839.650391')),
 (datetime.date(2025, 12, 10),
  'bitcoin',
  Decimal('92686.104020'),
  Decimal('25758.000000')),
 (datetime.date(2025, 12, 10),
  'ethereum',
  Decimal('3318.720945'),
  Decimal('25758.000000')),
 (datetime.date(2025, 12, 10),
  'tether',
  Decimal('1.000103'),
  Decimal('25758.000000')),
 (datetime.date(2025, 12, 11),
  'bitcoin',
  Decimal('91986.581072'),
  Decimal('25898.550781')),
 (datetime.date(2025, 12, 11),
  'ethereum',
  Decimal('3323.292013'),
  Decimal('25898.550781')),
 (datetime.date(2025, 12, 11),
  'tether',
  Decimal('1.000220'),
  Decimal('25898.550781')),
 (datetime.date(2025, 12, 12),
  'bitcoin',
  Decimal('92525.868003'),
  Decimal('26046.949219')),
 (datetime.date(2025, 12, 12),
  'ethereum',
  Decimal('3238.413615'),
  Decimal('26046.949219')),
 (datetime.date(2025, 12, 12),
  'tether',
  Decimal('1.000198'),
  Decimal('26046.949219')),
 (datetime.date(2025, 12, 15),
  'bitcoin',
  Decimal('88184.410931'),
  Decimal('26027.300781')),
 (datetime.date(2025, 12, 15),
  'ethereum',
  Decimal('3063.545453'),
  Decimal('26027.300781')),
 (datetime.date(2025, 12, 15),
  'tether',
  Decimal('1.000190'),
  Decimal('26027.300781')),
 (datetime.date(2025, 12, 16),
  'bitcoin',
  Decimal('86413.221381'),
  Decimal('25860.099609')),
 (datetime.date(2025, 12, 16),
  'ethereum',
  Decimal('2963.894557'),
  Decimal('25860.099609')),
 (datetime.date(2025, 12, 16),
  'tether',
  Decimal('1.000036'),
  Decimal('25860.099609')),
 (datetime.date(2025, 12, 17),
  'bitcoin',
  Decimal('87719.681398'),
  Decimal('25818.550781')),
 (datetime.date(2025, 12, 17),
  'ethereum',
  Decimal('2957.860249'),
  Decimal('25818.550781')),
 (datetime.date(2025, 12, 17),
  'tether',
  Decimal('0.999913'),
  Decimal('25818.550781')),
 (datetime.date(2025, 12, 18),
  'bitcoin',
  Decimal('86196.821373'),
  Decimal('25815.550781')),
 (datetime.date(2025, 12, 18),
  'ethereum',
  Decimal('2832.468327'),
  Decimal('25815.550781')),
 (datetime.date(2025, 12, 18),
  'tether',
  Decimal('0.999820'),
  Decimal('25815.550781')),
 (datetime.date(2025, 12, 19),
  'bitcoin',
  Decimal('85450.179648'),
  Decimal('25966.400391')),
 (datetime.date(2025, 12, 19),
  'ethereum',
  Decimal('2826.673248'),
  Decimal('25966.400391')),
 (datetime.date(2025, 12, 19),
  'tether',
  Decimal('0.999559'),
  Decimal('25966.400391')),
 (datetime.date(2025, 12, 22),
  'bitcoin',
  Decimal('88672.329679'),
  Decimal('26172.400391')),
 (datetime.date(2025, 12, 22),
  'ethereum',
  Decimal('3004.220492'),
  Decimal('26172.400391')),
 (datetime.date(2025, 12, 22),
  'tether',
  Decimal('0.999783'),
  Decimal('26172.400391')),
 (datetime.date(2025, 12, 23),
  'bitcoin',
  Decimal('88489.724042'),
  Decimal('26177.150391')),
 (datetime.date(2025, 12, 23),
  'ethereum',
  Decimal('3005.375558'),
  Decimal('26177.150391')),
 (datetime.date(2025, 12, 23),
  'tether',
  Decimal('0.999527'),
  Decimal('26177.150391')),
 (datetime.date(2025, 12, 24),
  'bitcoin',
  Decimal('87496.146692'),
  Decimal('26142.099609')),
 (datetime.date(2025, 12, 24),
  'ethereum',
  Decimal('2965.218785'),
  Decimal('26142.099609')),
 (datetime.date(2025, 12, 24),
  'tether',
  Decimal('0.999476'),
  Decimal('26142.099609')),
 (datetime.date(2025, 12, 26),
  'bitcoin',
  Decimal('87192.234737'),
  Decimal('26042.300781')),
 (datetime.date(2025, 12, 26),
  'ethereum',
  Decimal('2901.680790'),
  Decimal('26042.300781')),
 (datetime.date(2025, 12, 26),
  'tether',
  Decimal('0.999512'),
  Decimal('26042.300781')),
 (datetime.date(2025, 12, 29),
  'bitcoin',
  Decimal('87867.039434'),
  Decimal('25942.099609')),
 (datetime.date(2025, 12, 29),
  'ethereum',
  Decimal('2948.831769'),
  Decimal('25942.099609')),
 (datetime.date(2025, 12, 29),
  'tether',
  Decimal('0.999355'),
  Decimal('25942.099609')),
 (datetime.date(2025, 12, 30),
  'bitcoin',
  Decimal('87154.682406'),
  Decimal('25938.849609')),
 (datetime.date(2025, 12, 30),
  'ethereum',
  Decimal('2934.356281'),
  Decimal('25938.849609')),
 (datetime.date(2025, 12, 30),
  'tether',
  Decimal('0.998910'),
  Decimal('25938.849609')),
 (datetime.date(2025, 12, 31),
  'bitcoin',
  Decimal('88363.722236'),
  Decimal('26129.599609')),
 (datetime.date(2025, 12, 31),
  'ethereum',
  Decimal('2967.980414'),
  Decimal('26129.599609')),
 (datetime.date(2025, 12, 31),
  'tether',
  Decimal('0.999032'),
  Decimal('26129.599609'))]

In [56]:
cursor.execute("""
SELECT
    s.date,
    s.close AS sp500_close,
    o.price_usd AS oil_price
FROM stock_prices s
JOIN oil_prices o
ON s.date = o.date
WHERE s.ticker = '^GSPC'
ORDER BY s.date
""")

result = cursor.fetchall()
result

[(datetime.date(2020, 1, 2), Decimal('3257.850098'), Decimal('61.170000')),
 (datetime.date(2020, 1, 3), Decimal('3234.850098'), Decimal('63.000000')),
 (datetime.date(2020, 1, 6), Decimal('3246.280029'), Decimal('63.270000')),
 (datetime.date(2020, 1, 7), Decimal('3237.179932'), Decimal('62.700000')),
 (datetime.date(2020, 1, 8), Decimal('3253.050049'), Decimal('59.650000')),
 (datetime.date(2020, 1, 9), Decimal('3274.699951'), Decimal('59.560000')),
 (datetime.date(2020, 1, 10), Decimal('3265.350098'), Decimal('59.020000')),
 (datetime.date(2020, 1, 13), Decimal('3288.129883'), Decimal('58.170000')),
 (datetime.date(2020, 1, 14), Decimal('3283.149902'), Decimal('58.340000')),
 (datetime.date(2020, 1, 15), Decimal('3289.290039'), Decimal('57.860000')),
 (datetime.date(2020, 1, 16), Decimal('3316.810059'), Decimal('58.520000')),
 (datetime.date(2020, 1, 17), Decimal('3329.620117'), Decimal('58.550000')),
 (datetime.date(2020, 1, 21), Decimal('3320.790039'), Decimal('58.250000')),
 (datetime.date(2020, 1, 22), Decimal('3321.750000'), Decimal('56.760000')),
 (datetime.date(2020, 1, 23), Decimal('3325.540039'), Decimal('55.510000')),
 (datetime.date(2020, 1, 24), Decimal('3295.469971'), Decimal('54.090000')),
 (datetime.date(2020, 1, 27), Decimal('3243.629883'), Decimal('53.090000')),
 (datetime.date(2020, 1, 28), Decimal('3276.239990'), Decimal('53.330000')),
 (datetime.date(2020, 1, 29), Decimal('3273.399902'), Decimal('53.290000')),
 (datetime.date(2020, 1, 30), Decimal('3283.659912'), Decimal('52.190000')),
 (datetime.date(2020, 1, 31), Decimal('3225.520020'), Decimal('51.580000')),
 (datetime.date(2020, 2, 3), Decimal('3248.919922'), Decimal('50.060000')),
 (datetime.date(2020, 2, 4), Decimal('3297.590088'), Decimal('49.590000')),
 (datetime.date(2020, 2, 5), Decimal('3334.689941'), Decimal('50.870000')),
 (datetime.date(2020, 2, 6), Decimal('3345.780029'), Decimal('50.940000')),
 (datetime.date(2020, 2, 7), Decimal('3327.709961'), Decimal('50.340000')),
 (datetime.date(2020, 2, 10), Decimal('3352.090088'), Decimal('49.590000')),
 (datetime.date(2020, 2, 11), Decimal('3357.750000'), Decimal('50.000000')),
 (datetime.date(2020, 2, 12), Decimal('3379.449951'), Decimal('51.130000')),
 (datetime.date(2020, 2, 13), Decimal('3373.939941'), Decimal('51.410000')),
 (datetime.date(2020, 2, 14), Decimal('3380.159912'), Decimal('52.030000')),
 (datetime.date(2020, 2, 18), Decimal('3370.290039'), Decimal('52.100000')),
 (datetime.date(2020, 2, 19), Decimal('3386.149902'), Decimal('53.310000')),
 (datetime.date(2020, 2, 20), Decimal('3373.229980'), Decimal('53.770000')),
 (datetime.date(2020, 2, 21), Decimal('3337.750000'), Decimal('53.360000')),
 (datetime.date(2020, 2, 24), Decimal('3225.889893'), Decimal('51.360000')),
 (datetime.date(2020, 2, 25), Decimal('3128.209961'), Decimal('49.780000')),
 (datetime.date(2020, 2, 26), Decimal('3116.389893'), Decimal('48.670000')),
 (datetime.date(2020, 2, 27), Decimal('2978.760010'), Decimal('47.170000')),
 (datetime.date(2020, 2, 28), Decimal('2954.219971'), Decimal('44.830000')),
 (datetime.date(2020, 3, 2), Decimal('3090.229980'), Decimal('46.780000')),
 (datetime.date(2020, 3, 3), Decimal('3003.370117'), Decimal('47.270000')),
 (datetime.date(2020, 3, 4), Decimal('3130.120117'), Decimal('46.780000')),
 (datetime.date(2020, 3, 5), Decimal('3023.939941'), Decimal('45.900000')),
 (datetime.date(2020, 3, 6), Decimal('2972.370117'), Decimal('41.140000')),
 (datetime.date(2020, 3, 9), Decimal('2746.560059'), Decimal('31.050000')),
 (datetime.date(2020, 3, 10), Decimal('2882.229980'), Decimal('34.470000')),
 (datetime.date(2020, 3, 11), Decimal('2741.379883'), Decimal('33.130000')),
 (datetime.date(2020, 3, 12), Decimal('2480.639893'), Decimal('31.560000')),
 (datetime.date(2020, 3, 13), Decimal('2711.020020'), Decimal('31.720000')),
 (datetime.date(2020, 3, 16), Decimal('2386.129883'), Decimal('28.960000')),
 (datetime.date(2020, 3, 17), Decimal('2529.189941'), Decimal('26.960000')),
 (datetime.date(2020, 3, 18), Decimal('2398.100098'), Decimal('20.480000')),
 (datetime.date(2020, 3, 19), Decimal('2409.389893'), Decimal('25.090000')),
 (datetime.date(2020, 3, 20), Decimal('2304.919922'), Decimal('19.480000')),
 (datetime.date(2020, 3, 23), Decimal('2237.399902'), Decimal('23.330000')),
 (datetime.date(2020, 3, 24), Decimal('2447.330078'), Decimal('21.030000')),
 (datetime.date(2020, 3, 25), Decimal('2475.560059'), Decimal('20.750000')),
 (datetime.date(2020, 3, 26), Decimal('2630.070068'), Decimal('16.600000')),
 (datetime.date(2020, 3, 27), Decimal('2541.469971'), Decimal('15.480000')),
 (datetime.date(2020, 3, 30), Decimal('2626.649902'), Decimal('14.100000')),
 (datetime.date(2020, 3, 31), Decimal('2584.590088'), Decimal('20.510000')),
 (datetime.date(2020, 4, 1), Decimal('2470.500000'), Decimal('20.280000')),
 (datetime.date(2020, 4, 2), Decimal('2526.899902'), Decimal('25.180000')),
 (datetime.date(2020, 4, 3), Decimal('2488.649902'), Decimal('28.360000')),
 (datetime.date(2020, 4, 6), Decimal('2663.679932'), Decimal('26.210000')),
 (datetime.date(2020, 4, 7), Decimal('2659.409912'), Decimal('23.540000')),
 (datetime.date(2020, 4, 8), Decimal('2749.979980'), Decimal('24.970000')),
 (datetime.date(2020, 4, 9), Decimal('2789.820068'), Decimal('22.900000')),
 (datetime.date(2020, 4, 13), Decimal('2761.629883'), Decimal('22.360000')),
 (datetime.date(2020, 4, 14), Decimal('2846.060059'), Decimal('20.150000')),
 (datetime.date(2020, 4, 15), Decimal('2783.360107'), Decimal('19.960000')),
 (datetime.date(2020, 4, 16), Decimal('2799.550049'), Decimal('19.820000')),
 (datetime.date(2020, 4, 17), Decimal('2874.560059'), Decimal('18.310000')),
 (datetime.date(2020, 4, 20), Decimal('2823.159912'), Decimal('-36.980000')),
 (datetime.date(2020, 4, 21), Decimal('2736.560059'), Decimal('8.910000')),
 (datetime.date(2020, 4, 22), Decimal('2799.310059'), Decimal('13.640000')),
 (datetime.date(2020, 4, 23), Decimal('2797.800049'), Decimal('15.060000')),
 (datetime.date(2020, 4, 24), Decimal('2836.739990'), Decimal('15.990000')),
 (datetime.date(2020, 4, 27), Decimal('2878.479980'), Decimal('12.170000')),
 (datetime.date(2020, 4, 28), Decimal('2863.389893'), Decimal('12.400000')),
 (datetime.date(2020, 4, 29), Decimal('2939.510010'), Decimal('15.040000')),
 (datetime.date(2020, 4, 30), Decimal('2912.429932'), Decimal('19.230000')),
 (datetime.date(2020, 5, 1), Decimal('2830.709961'), Decimal('19.720000')),
 (datetime.date(2020, 5, 4), Decimal('2842.739990'), Decimal('20.470000')),
 (datetime.date(2020, 5, 5), Decimal('2868.439941'), Decimal('24.560000')),
 (datetime.date(2020, 5, 6), Decimal('2848.419922'), Decimal('23.880000')),
 (datetime.date(2020, 5, 7), Decimal('2881.189941'), Decimal('23.680000')),
 (datetime.date(2020, 5, 8), Decimal('2929.800049'), Decimal('24.730000')),
 (datetime.date(2020, 5, 11), Decimal('2930.189941'), Decimal('24.020000')),
 (datetime.date(2020, 5, 12), Decimal('2870.120117'), Decimal('25.760000')),
 (datetime.date(2020, 5, 13), Decimal('2820.000000'), Decimal('25.370000')),
 (datetime.date(2020, 5, 14), Decimal('2852.500000'), Decimal('27.400000')),
 (datetime.date(2020, 5, 15), Decimal('2863.699951'), Decimal('29.440000')),
 (datetime.date(2020, 5, 18), Decimal('2953.909912'), Decimal('31.830000')),
 (datetime.date(2020, 5, 19), Decimal('2922.939941'), Decimal('32.300000')),
 (datetime.date(2020, 5, 20), Decimal('2971.610107'), Decimal('33.560000')),
 (datetime.date(2020, 5, 21), Decimal('2948.510010'), Decimal('34.300000')),
 (datetime.date(2020, 5, 22), Decimal('2955.449951'), Decimal('33.490000')),
 (datetime.date(2020, 5, 26), Decimal('2991.770020'), Decimal('34.700000')),
 (datetime.date(2020, 5, 27), Decimal('3036.129883'), Decimal('32.800000')),
 (datetime.date(2020, 5, 28), Decimal('3029.729980'), Decimal('33.670000')),
 (datetime.date(2020, 5, 29), Decimal('3044.310059'), Decimal('35.570000')),
 (datetime.date(2020, 6, 1), Decimal('3055.729980'), Decimal('35.490000')),
 (datetime.date(2020, 6, 2), Decimal('3080.820068'), Decimal('36.880000')),
 (datetime.date(2020, 6, 3), Decimal('3122.870117'), Decimal('37.330000')),
 (datetime.date(2020, 6, 4), Decimal('3112.350098'), Decimal('37.420000')),
 (datetime.date(2020, 6, 5), Decimal('3193.929932'), Decimal('39.490000')),
 (datetime.date(2020, 6, 8), Decimal('3232.389893'), Decimal('38.170000')),
 (datetime.date(2020, 6, 9), Decimal('3207.179932'), Decimal('38.980000')),
 (datetime.date(2020, 6, 10), Decimal('3190.139893'), Decimal('39.540000')),
 (datetime.date(2020, 6, 11), Decimal('3002.100098'), Decimal('36.430000')),
 (datetime.date(2020, 6, 12), Decimal('3041.310059'), Decimal('36.240000')),
 (datetime.date(2020, 6, 15), Decimal('3066.590088'), Decimal('37.070000')),
 (datetime.date(2020, 6, 16), Decimal('3124.739990'), Decimal('38.260000')),
 (datetime.date(2020, 6, 17), Decimal('3113.489990'), Decimal('37.910000')),
 (datetime.date(2020, 6, 18), Decimal('3115.340088'), Decimal('38.790000')),
 (datetime.date(2020, 6, 19), Decimal('3097.739990'), Decimal('39.720000')),
 (datetime.date(2020, 6, 22), Decimal('3117.860107'), Decimal('40.600000')),
 (datetime.date(2020, 6, 23), Decimal('3131.290039'), Decimal('40.400000')),
 (datetime.date(2020, 6, 24), Decimal('3050.330078'), Decimal('37.910000')),
 (datetime.date(2020, 6, 25), Decimal('3083.760010'), Decimal('38.660000')),
 (datetime.date(2020, 6, 26), Decimal('3009.050049'), Decimal('38.530000')),
 (datetime.date(2020, 6, 29), Decimal('3053.239990'), Decimal('39.670000')),
 (datetime.date(2020, 6, 30), Decimal('3100.290039'), Decimal('39.270000')),
 (datetime.date(2020, 7, 1), Decimal('3115.860107'), Decimal('39.880000')),
 (datetime.date(2020, 7, 2), Decimal('3130.010010'), Decimal('40.570000')),
 (datetime.date(2020, 7, 6), Decimal('3179.719971'), Decimal('40.510000')),
 (datetime.date(2020, 7, 7), Decimal('3145.320068'), Decimal('40.590000')),
 (datetime.date(2020, 7, 8), Decimal('3169.939941'), Decimal('40.910000')),
 (datetime.date(2020, 7, 9), Decimal('3152.050049'), Decimal('39.640000')),
 (datetime.date(2020, 7, 10), Decimal('3185.040039'), Decimal('40.560000')),
 (datetime.date(2020, 7, 13), Decimal('3155.219971'), Decimal('40.060000')),
 (datetime.date(2020, 7, 14), Decimal('3197.520020'), Decimal('40.300000')),
 (datetime.date(2020, 7, 15), Decimal('3226.560059'), Decimal('41.200000')),
 (datetime.date(2020, 7, 16), Decimal('3215.570068'), Decimal('40.740000')),
 (datetime.date(2020, 7, 17), Decimal('3224.729980'), Decimal('40.550000')),
 (datetime.date(2020, 7, 20), Decimal('3251.840088'), Decimal('40.830000')),
 (datetime.date(2020, 7, 21), Decimal('3257.300049'), Decimal('41.760000')),
 (datetime.date(2020, 7, 22), Decimal('3276.020020'), Decimal('41.880000')),
 (datetime.date(2020, 7, 23), Decimal('3235.659912'), Decimal('40.990000')),
 (datetime.date(2020, 7, 24), Decimal('3215.629883'), Decimal('41.230000')),
 (datetime.date(2020, 7, 27), Decimal('3239.409912'), Decimal('41.460000')),
 (datetime.date(2020, 7, 28), Decimal('3218.439941'), Decimal('40.890000')),
 (datetime.date(2020, 7, 29), Decimal('3258.439941'), Decimal('41.130000')),
 (datetime.date(2020, 7, 30), Decimal('3246.219971'), Decimal('39.850000')),
 (datetime.date(2020, 7, 31), Decimal('3271.120117'), Decimal('40.100000')),
 (datetime.date(2020, 8, 3), Decimal('3294.610107'), Decimal('40.830000')),
 (datetime.date(2020, 8, 4), Decimal('3306.510010'), Decimal('41.670000')),
 (datetime.date(2020, 8, 5), Decimal('3327.770020'), Decimal('42.250000')),
 (datetime.date(2020, 8, 6), Decimal('3349.159912'), Decimal('41.930000')),
 (datetime.date(2020, 8, 7), Decimal('3351.280029'), Decimal('41.160000')),
 (datetime.date(2020, 8, 10), Decimal('3360.469971'), Decimal('41.940000')),
 (datetime.date(2020, 8, 11), Decimal('3333.689941'), Decimal('41.530000')),
 (datetime.date(2020, 8, 12), Decimal('3380.350098'), Decimal('42.600000')),
 (datetime.date(2020, 8, 13), Decimal('3373.429932'), Decimal('42.260000')),
 (datetime.date(2020, 8, 14), Decimal('3372.850098'), Decimal('42.050000')),
 (datetime.date(2020, 8, 17), Decimal('3381.989990'), Decimal('42.890000')),
 (datetime.date(2020, 8, 18), Decimal('3389.780029'), Decimal('42.890000')),
 (datetime.date(2020, 8, 19), Decimal('3374.850098'), Decimal('42.910000')),
 (datetime.date(2020, 8, 20), Decimal('3385.510010'), Decimal('42.620000')),
 (datetime.date(2020, 8, 21), Decimal('3397.159912'), Decimal('42.320000')),
 (datetime.date(2020, 8, 24), Decimal('3431.280029'), Decimal('42.440000')),
 (datetime.date(2020, 8, 25), Decimal('3443.620117'), Decimal('43.170000')),
 (datetime.date(2020, 8, 26), Decimal('3478.729980'), Decimal('43.210000')),
 (datetime.date(2020, 8, 27), Decimal('3484.550049'), Decimal('42.880000')),
 (datetime.date(2020, 8, 28), Decimal('3508.010010'), Decimal('42.960000')),
 (datetime.date(2020, 8, 31), Decimal('3500.310059'), Decimal('42.610000')),
 (datetime.date(2020, 9, 1), Decimal('3526.649902'), Decimal('42.760000')),
 (datetime.date(2020, 9, 2), Decimal('3580.840088'), Decimal('42.760000')),
 (datetime.date(2020, 9, 3), Decimal('3455.060059'), Decimal('41.390000')),
 (datetime.date(2020, 9, 4), Decimal('3426.959961'), Decimal('39.690000')),
 (datetime.date(2020, 9, 8), Decimal('3331.840088'), Decimal('36.870000')),
 (datetime.date(2020, 9, 9), Decimal('3398.959961'), Decimal('38.050000')),
 (datetime.date(2020, 9, 10), Decimal('3339.189941'), Decimal('37.250000')),
 (datetime.date(2020, 9, 11), Decimal('3340.969971'), Decimal('37.330000')),
 (datetime.date(2020, 9, 14), Decimal('3383.540039'), Decimal('37.230000')),
 (datetime.date(2020, 9, 15), Decimal('3401.199951'), Decimal('38.290000')),
 (datetime.date(2020, 9, 16), Decimal('3385.489990'), Decimal('40.170000')),
 (datetime.date(2020, 9, 17), Decimal('3357.010010'), Decimal('40.990000')),
 (datetime.date(2020, 9, 18), Decimal('3319.469971'), Decimal('41.090000')),
 (datetime.date(2020, 9, 21), Decimal('3281.060059'), Decimal('39.260000')),
 (datetime.date(2020, 9, 22), Decimal('3315.570068'), Decimal('39.550000')),
 (datetime.date(2020, 9, 23), Decimal('3236.919922'), Decimal('39.920000')),
 (datetime.date(2020, 9, 24), Decimal('3246.590088'), Decimal('40.110000')),
 (datetime.date(2020, 9, 25), Decimal('3298.459961'), Decimal('40.060000')),
 (datetime.date(2020, 9, 28), Decimal('3351.600098'), Decimal('40.470000')),
 (datetime.date(2020, 9, 29), Decimal('3335.469971'), Decimal('39.030000')),
 (datetime.date(2020, 9, 30), Decimal('3363.000000'), Decimal('40.050000')),
 (datetime.date(2020, 10, 1), Decimal('3380.800049'), Decimal('38.510000')),
 (datetime.date(2020, 10, 2), Decimal('3348.419922'), Decimal('36.900000')),
 (datetime.date(2020, 10, 5), Decimal('3408.600098'), Decimal('39.120000')),
 (datetime.date(2020, 10, 6), Decimal('3360.969971'), Decimal('40.520000')),
 (datetime.date(2020, 10, 7), Decimal('3419.439941'), Decimal('39.820000')),
 (datetime.date(2020, 10, 8), Decimal('3446.830078'), Decimal('41.040000')),
 (datetime.date(2020, 10, 9), Decimal('3477.139893'), Decimal('40.440000')),
 (datetime.date(2020, 10, 12), Decimal('3534.219971'), Decimal('39.220000')),
 (datetime.date(2020, 10, 13), Decimal('3511.929932'), Decimal('40.030000')),
 (datetime.date(2020, 10, 14), Decimal('3488.669922'), Decimal('40.860000')),
 (datetime.date(2020, 10, 15), Decimal('3483.340088'), Decimal('40.840000')),
 (datetime.date(2020, 10, 16), Decimal('3483.810059'), Decimal('40.700000')),
 (datetime.date(2020, 10, 19), Decimal('3426.919922'), Decimal('40.690000')),
 (datetime.date(2020, 10, 20), Decimal('3443.120117'), Decimal('41.370000')),
 (datetime.date(2020, 10, 21), Decimal('3435.560059'), Decimal('39.880000')),
 (datetime.date(2020, 10, 22), Decimal('3453.489990'), Decimal('40.460000')),
 (datetime.date(2020, 10, 23), Decimal('3465.389893'), Decimal('39.730000')),
 (datetime.date(2020, 10, 26), Decimal('3400.969971'), Decimal('38.390000')),
 (datetime.date(2020, 10, 27), Decimal('3390.679932'), Decimal('39.340000')),
 (datetime.date(2020, 10, 28), Decimal('3271.030029'), Decimal('37.270000')),
 (datetime.date(2020, 10, 29), Decimal('3310.110107'), Decimal('35.940000')),
 (datetime.date(2020, 10, 30), Decimal('3269.959961'), Decimal('35.640000')),
 (datetime.date(2020, 11, 2), Decimal('3310.239990'), Decimal('36.600000')),
 (datetime.date(2020, 11, 3), Decimal('3369.159912'), Decimal('37.440000')),
 (datetime.date(2020, 11, 4), Decimal('3443.439941'), Decimal('38.970000')),
 (datetime.date(2020, 11, 5), Decimal('3510.449951'), Decimal('38.560000')),
 (datetime.date(2020, 11, 6), Decimal('3509.439941'), Decimal('36.970000')),
 (datetime.date(2020, 11, 9), Decimal('3550.500000'), Decimal('40.050000')),
 (datetime.date(2020, 11, 10), Decimal('3545.530029'), Decimal('41.180000')),
 (datetime.date(2020, 11, 11), Decimal('3572.659912'), Decimal('41.230000')),
 (datetime.date(2020, 11, 12), Decimal('3537.010010'), Decimal('40.900000')),
 (datetime.date(2020, 11, 13), Decimal('3585.149902'), Decimal('39.930000')),
 (datetime.date(2020, 11, 16), Decimal('3626.909912'), Decimal('41.140000')),
 (datetime.date(2020, 11, 17), Decimal('3609.530029'), Decimal('41.240000')),
 (datetime.date(2020, 11, 18), Decimal('3567.790039'), Decimal('41.640000')),
 (datetime.date(2020, 11, 19), Decimal('3581.870117'), Decimal('41.570000')),
 (datetime.date(2020, 11, 20), Decimal('3557.540039'), Decimal('41.990000')),
 (datetime.date(2020, 11, 23), Decimal('3577.590088'), Decimal('42.910000')),
 (datetime.date(2020, 11, 24), Decimal('3635.409912'), Decimal('44.710000')),
 (datetime.date(2020, 11, 25), Decimal('3629.649902'), Decimal('45.580000')),
 (datetime.date(2020, 11, 30), Decimal('3621.629883'), Decimal('45.200000')),
 (datetime.date(2020, 12, 1), Decimal('3662.449951'), Decimal('44.540000')),
 (datetime.date(2020, 12, 2), Decimal('3669.010010'), Decimal('45.230000')),
 (datetime.date(2020, 12, 3), Decimal('3666.719971'), Decimal('45.650000')),
 (datetime.date(2020, 12, 4), Decimal('3699.120117'), Decimal('46.230000')),
 (datetime.date(2020, 12, 7), Decimal('3691.959961'), Decimal('45.720000')),
 (datetime.date(2020, 12, 8), Decimal('3702.250000'), Decimal('45.640000')),
 (datetime.date(2020, 12, 9), Decimal('3672.820068'), Decimal('45.480000')),
 (datetime.date(2020, 12, 10), Decimal('3668.100098'), Decimal('46.760000')),
 (datetime.date(2020, 12, 11), Decimal('3663.459961'), Decimal('46.590000')),
 (datetime.date(2020, 12, 14), Decimal('3647.489990'), Decimal('47.020000')),
 (datetime.date(2020, 12, 15), Decimal('3694.620117'), Decimal('47.580000')),
 (datetime.date(2020, 12, 16), Decimal('3701.169922'), Decimal('47.860000')),
 (datetime.date(2020, 12, 17), Decimal('3722.479980'), Decimal('48.340000')),
 (datetime.date(2020, 12, 18), Decimal('3709.409912'), Decimal('49.040000')),
 (datetime.date(2020, 12, 21), Decimal('3694.919922'), Decimal('47.790000')),
 (datetime.date(2020, 12, 22), Decimal('3687.260010'), Decimal('47.020000')),
 (datetime.date(2020, 12, 23), Decimal('3690.010010'), Decimal('47.940000')),
 (datetime.date(2020, 12, 24), Decimal('3703.060059'), Decimal('48.180000')),
 (datetime.date(2020, 12, 28), Decimal('3735.360107'), Decimal('47.500000')),
 (datetime.date(2020, 12, 29), Decimal('3727.040039'), Decimal('47.850000')),
 (datetime.date(2020, 12, 30), Decimal('3732.040039'), Decimal('48.240000')),
 (datetime.date(2020, 12, 31), Decimal('3756.070068'), Decimal('48.350000')),
 (datetime.date(2021, 1, 4), Decimal('3700.649902'), Decimal('47.470000')),
 (datetime.date(2021, 1, 5), Decimal('3726.860107'), Decimal('49.780000')),
 (datetime.date(2021, 1, 6), Decimal('3748.139893'), Decimal('50.450000')),
 (datetime.date(2021, 1, 7), Decimal('3803.790039'), Decimal('50.630000')),
 (datetime.date(2021, 1, 8), Decimal('3824.679932'), Decimal('52.140000')),
 (datetime.date(2021, 1, 11), Decimal('3799.610107'), Decimal('52.150000')),
 (datetime.date(2021, 1, 12), Decimal('3801.189941'), Decimal('53.080000')),

In [57]:
cursor.execute("""
SELECT
    (
        COUNT(*) * SUM(c.price_usd * o.price_usd)
        - SUM(c.price_usd) * SUM(o.price_usd)
    )
    /
    SQRT(
        (
            COUNT(*) * SUM(c.price_usd * c.price_usd)
            - POW(SUM(c.price_usd), 2)
        )
        *
        (
            COUNT(*) * SUM(o.price_usd * o.price_usd)
            - POW(SUM(o.price_usd), 2)
        )
    ) AS correlation
FROM crypto_prices c
JOIN oil_prices o
ON c.date = o.date
WHERE c.coin_id = 'bitcoin'
""")

result = cursor.fetchall()
result

[(-0.5100186799054723,)]

In [58]:
cursor.execute("""
SELECT
    c.date,
    c.price_usd AS ethereum_price,
    s.close AS nasdaq_close
FROM crypto_prices c
JOIN stock_prices s
ON c.date = s.date
WHERE c.coin_id = 'ethereum'
AND s.ticker = '^IXIC'
ORDER BY c.date
""")

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3), Decimal('4484.180377'), Decimal('22780.509766')),
 (datetime.date(2025, 10, 6), Decimal('4513.310148'), Decimal('22941.669922')),
 (datetime.date(2025, 10, 7), Decimal('4690.837856'), Decimal('22788.359375')),
 (datetime.date(2025, 10, 8), Decimal('4453.781266'), Decimal('23043.380859')),
 (datetime.date(2025, 10, 9), Decimal('4526.062095'), Decimal('23024.630859')),
 (datetime.date(2025, 10, 10),
  Decimal('4368.419617'),
  Decimal('22204.429688')),
 (datetime.date(2025, 10, 13),
  Decimal('4151.918863'),
  Decimal('22694.609375')),
 (datetime.date(2025, 10, 14),
  Decimal('4245.447077'),
  Decimal('22521.699219')),
 (datetime.date(2025, 10, 15),
  Decimal('4126.235353'),
  Decimal('22670.080078')),
 (datetime.date(2025, 10, 16),
  Decimal('3991.544236'),
  Decimal('22562.539063')),
 (datetime.date(2025, 10, 17),
  Decimal('3893.756038'),
  Decimal('22679.970703')),
 (datetime.date(2025, 10, 20),
  Decimal('3982.355861'),
  Decimal('22990.539063')),
 (datetime.date(2025, 10, 21),
  Decimal('3980.073280'),
  Decimal('22953.669922')),
 (datetime.date(2025, 10, 22),
  Decimal('3866.151783'),
  Decimal('22740.400391')),
 (datetime.date(2025, 10, 23),
  Decimal('3805.881864'),
  Decimal('22941.800781')),
 (datetime.date(2025, 10, 24),
  Decimal('3857.590009'),
  Decimal('23204.869141')),
 (datetime.date(2025, 10, 27),
  Decimal('4158.567622'),
  Decimal('23637.460938')),
 (datetime.date(2025, 10, 28),
  Decimal('4117.287078'),
  Decimal('23827.490234')),
 (datetime.date(2025, 10, 29),
  Decimal('3978.812010'),
  Decimal('23958.470703')),
 (datetime.date(2025, 10, 30),
  Decimal('3902.801947'),
  Decimal('23581.140625')),
 (datetime.date(2025, 10, 31),
  Decimal('3801.551505'),
  Decimal('23724.960938')),
 (datetime.date(2025, 11, 3), Decimal('3905.342930'), Decimal('23834.720703')),
 (datetime.date(2025, 11, 4), Decimal('3600.363768'), Decimal('23348.640625')),
 (datetime.date(2025, 11, 5), Decimal('3285.231840'), Decimal('23499.800781')),
 (datetime.date(2025, 11, 6), Decimal('3425.969806'), Decimal('23053.990234')),
 (datetime.date(2025, 11, 7), Decimal('3312.450307'), Decimal('23004.539063')),
 (datetime.date(2025, 11, 10),
  Decimal('3578.802306'),
  Decimal('23527.169922')),
 (datetime.date(2025, 11, 11),
  Decimal('3566.049867'),
  Decimal('23468.300781')),
 (datetime.date(2025, 11, 12),
  Decimal('3416.071509'),
  Decimal('23406.460938')),
 (datetime.date(2025, 11, 13),
  Decimal('3412.543237'),
  Decimal('22870.359375')),
 (datetime.date(2025, 11, 14),
  Decimal('3223.175779'),
  Decimal('22900.589844')),
 (datetime.date(2025, 11, 17),
  Decimal('3091.905046'),
  Decimal('22708.070313')),
 (datetime.date(2025, 11, 18),
  Decimal('3026.218255'),
  Decimal('22432.849609')),
 (datetime.date(2025, 11, 19),
  Decimal('3121.513848'),
  Decimal('22564.230469')),
 (datetime.date(2025, 11, 20),
  Decimal('3020.935788'),
  Decimal('22078.050781')),
 (datetime.date(2025, 11, 21),
  Decimal('2832.530798'),
  Decimal('22273.080078')),
 (datetime.date(2025, 11, 24),
  Decimal('2798.913101'),
  Decimal('22872.009766')),
 (datetime.date(2025, 11, 25),
  Decimal('2952.334907'),
  Decimal('23025.589844')),
 (datetime.date(2025, 11, 26),
  Decimal('2958.573218'),
  Decimal('23214.689453')),
 (datetime.date(2025, 11, 27), Decimal('3026.421535'), None),
 (datetime.date(2025, 11, 28),
  Decimal('3014.819850'),
  Decimal('23365.689453')),
 (datetime.date(2025, 12, 1), Decimal('2990.797383'), Decimal('23275.919922')),
 (datetime.date(2025, 12, 2), Decimal('2796.733869'), Decimal('23413.669922')),
 (datetime.date(2025, 12, 3), Decimal('2997.602427'), Decimal('23454.089844')),
 (datetime.date(2025, 12, 4), Decimal('3188.881945'), Decimal('23505.140625')),
 (datetime.date(2025, 12, 5), Decimal('3134.348641'), Decimal('23578.130859')),
 (datetime.date(2025, 12, 8), Decimal('3060.994832'), Decimal('23545.900391')),
 (datetime.date(2025, 12, 9), Decimal('3123.805252'), Decimal('23576.490234')),
 (datetime.date(2025, 12, 10),
  Decimal('3318.720945'),
  Decimal('23654.150391')),
 (datetime.date(2025, 12, 11),
  Decimal('3323.292013'),
  Decimal('23593.859375')),
 (datetime.date(2025, 12, 12),
  Decimal('3238.413615'),
  Decimal('23195.169922')),
 (datetime.date(2025, 12, 15),
  Decimal('3063.545453'),
  Decimal('23057.410156')),
 (datetime.date(2025, 12, 16),
  Decimal('2963.894557'),
  Decimal('23111.460938')),
 (datetime.date(2025, 12, 17),
  Decimal('2957.860249'),
  Decimal('22693.320313')),
 (datetime.date(2025, 12, 18),
  Decimal('2832.468327'),
  Decimal('23006.359375')),
 (datetime.date(2025, 12, 19),
  Decimal('2826.673248'),
  Decimal('23307.619141')),
 (datetime.date(2025, 12, 22),
  Decimal('3004.220492'),
  Decimal('23428.830078')),
 (datetime.date(2025, 12, 23),
  Decimal('3005.375558'),
  Decimal('23561.839844')),
 (datetime.date(2025, 12, 24),
  Decimal('2965.218785'),
  Decimal('23613.310547')),
 (datetime.date(2025, 12, 26),
  Decimal('2901.680790'),
  Decimal('23593.099609')),
 (datetime.date(2025, 12, 29),
  Decimal('2948.831769'),
  Decimal('23474.349609')),
 (datetime.date(2025, 12, 30),
  Decimal('2934.356281'),
  Decimal('23419.080078')),
 (datetime.date(2025, 12, 31),
  Decimal('2967.980414'),
  Decimal('23241.990234')),
 (datetime.date(2026, 1, 1), Decimal('2970.028682'), None),
 (datetime.date(2026, 1, 2), Decimal('3003.854808'), Decimal('23235.630859')),
 (datetime.date(2026, 1, 5), Decimal('3153.103396'), Decimal('23395.820313')),
 (datetime.date(2026, 1, 6), Decimal('3227.393319'), Decimal('23547.169922')),
 (datetime.date(2026, 1, 7), Decimal('3291.912961'), Decimal('23584.279297')),
 (datetime.date(2026, 1, 8), Decimal('3167.412775'), Decimal('23480.019531')),
 (datetime.date(2026, 1, 9), Decimal('3106.059128'), Decimal('23671.349609')),
 (datetime.date(2026, 1, 12), Decimal('3120.173389'), Decimal('23733.900391')),
 (datetime.date(2026, 1, 13), Decimal('3091.684735'), Decimal('23709.869141')),
 (datetime.date(2026, 1, 14), Decimal('3330.504429'), Decimal('23471.750000')),
 (datetime.date(2026, 1, 15), Decimal('3351.816082'), Decimal('23530.019531')),
 (datetime.date(2026, 1, 16), Decimal('3319.223166'), Decimal('23515.390625')),
 (datetime.date(2026, 1, 19), Decimal('3277.768641'), None),
 (datetime.date(2026, 1, 20), Decimal('3186.780740'), Decimal('22954.320313')),
 (datetime.date(2026, 1, 21), Decimal('2941.883256'), Decimal('23224.820313')),
 (datetime.date(2026, 1, 22), Decimal('2984.174966'), Decimal('23436.019531')),
 (datetime.date(2026, 1, 23), Decimal('2951.387076'), Decimal('23501.240234')),
 (datetime.date(2026, 1, 26), Decimal('2812.935404'), Decimal('23601.359375')),
 (datetime.date(2026, 1, 27), Decimal('2925.763833'), Decimal('23817.099609')),
 (datetime.date(2026, 1, 28), Decimal('3020.015731'), Decimal('23857.449219')),
 (datetime.date(2026, 1, 29), Decimal('3011.815000'), Decimal('23685.119141')),
 (datetime.date(2026, 1, 30), Decimal('2822.633841'), Decimal('23461.820313')),
 (datetime.date(2026, 2, 2), Decimal('2264.345388'), Decimal('23592.109375')),
 (datetime.date(2026, 2, 3), Decimal('2343.458544'), Decimal('23255.189453')),
 (datetime.date(2026, 2, 4), Decimal('2226.413118'), Decimal('22904.580078')),
 (datetime.date(2026, 2, 5), Decimal('2143.293399'), Decimal('22540.589844')),
 (datetime.date(2026, 2, 6), Decimal('1823.805331'), Decimal('23031.210938')),
 (datetime.date(2026, 2, 9), Decimal('2092.427459'), Decimal('23238.669922')),
 (datetime.date(2026, 2, 10), Decimal('2106.785644'), Decimal('23102.470703')),
 (datetime.date(2026, 2, 11), Decimal('2021.441591'), Decimal('23066.470703')),
 (datetime.date(2026, 2, 12), Decimal('1944.681901'), Decimal('22597.150391')),
 (datetime.date(2026, 2, 13), Decimal('1947.839922'), Decimal('22546.669922')),
 (datetime.date(2026, 2, 16), Decimal('1967.549922'), None),
 (datetime.date(2026, 2, 17), Decimal('1998.175987'), Decimal('22578.380859')),
 (datetime.date(2026, 2, 18), Decimal('1994.352712'), Decimal('22753.630859')),
 (datetime.date(2026, 2, 19), Decimal('1954.653115'), Decimal('22682.730469')),
 (datetime.date(2026, 2, 20), Decimal('1949.606837'), Decimal('22886.070313')),
 (datetime.date(2026, 2, 23), Decimal('1886.450367'), Decimal('22627.269531')),
 (datetime.date(2026, 2, 24), Decimal('1859.219911'), Decimal('22863.679688')),
 (datetime.date(2026, 2, 25), Decimal('1852.082162'), Decimal('23152.080078')),
 (datetime.date(2026, 2, 26), Decimal('2053.097733'), Decimal('22878.380859')),
 (datetime.date(2026, 2, 27), Decimal('2027.505076'), Decimal('22668.210938')),
 (datetime.date(2026, 3, 2), Decimal('1939.795719'), Decimal('22748.859375')),
 (datetime.date(2026, 3, 3), Decimal('2028.799011'), Decimal('22516.689453')),
 (datetime.date(2026, 3, 4), Decimal('1982.951413'), Decimal('22807.480469')),
 (datetime.date(2026, 3, 5), Decimal('2127.579178'), Decimal('22748.990234')),
 (datetime.date(2026, 3, 6), Decimal('2073.358947'), Decimal('22387.679688')),
 (datetime.date(2026, 3, 9), Decimal('1939.391759'), Decimal('22695.949219')),
 (datetime.date(2026, 3, 10), Decimal('1992.982027'), Decimal('22697.099609')),
 (datetime.date(2026, 3, 11), Decimal('2035.174154'), Decimal('22716.130859')),
 (datetime.date(2026, 3, 12), Decimal('2051.934114'), Decimal('22311.980469')),
 (datetime.date(2026, 3, 13), Decimal('2071.919731'), Decimal('22105.359375')),
 (datetime.date(2026, 3, 16), Decimal('2182.072658'), Decimal('22374.179688')),
 (datetime.date(2026, 3, 17), Decimal('2343.531088'), Decimal('22479.529297')),
 (datetime.date(2026, 3, 18), Decimal('2320.950927'), Decimal('22152.419922')),
 (datetime.date(2026, 3, 19), Decimal('2203.134944'), Decimal('22090.689453')),
 (datetime.date(2026, 3, 20), Decimal('2139.514195'), Decimal('21647.609375')),
 (datetime.date(2026, 3, 23), Decimal('2055.681839'), Decimal('21946.759766')),
 (datetime.date(2026, 3, 24), Decimal('2152.471302'), Decimal('21761.890625')),
 (datetime.date(2026, 3, 25), Decimal('2156.393878'), Decimal('21929.820313')),
 (datetime.date(2026, 3, 26), Decimal('2172.416333'), Decimal('21408.080078')),
 (datetime.date(2026, 3, 27), Decimal('2059.589104'), Decimal('20948.359375')),
 (datetime.date(2026, 3, 30), Decimal('1981.742370'), Decimal('20794.640625')),
 (datetime.date(2026, 3, 31), Decimal('2024.014647'), Decimal('21590.630859')),
 (datetime.date(2026, 4, 1), Decimal('2095.415993'), Decimal('21840.949219')),
 (datetime.date(2026, 4, 2), Decimal('2131.539277'), Decimal('21879.179688')),
 (datetime.date(2026, 4, 6), Decimal('2066.198125'), Decimal('21996.339844')),
 (datetime.date(2026, 4, 7), Decimal('2100.806140'), Decimal('22017.849609')),
 (datetime.date(2026, 4, 8), Decimal('2235.822206'), Decimal('22634.990234')),
 (datetime.date(2026, 4, 9), Decimal('2179.791570'), Decimal('22822.419922')),
 (datetime.date(2026, 4, 10), Decimal('2177.972587'), Decimal('22902.890625')),
 (datetime.date(2026, 4, 13), Decimal('2189.221444'), Decimal('23183.740234')),
 (datetime.date(2026, 4, 14), Decimal('2374.016205'), Decimal('23639.080078')),
 (datetime.date(2026, 4, 15), Decimal('2326.445177'), Decimal('24016.019531')),
 (datetime.date(2026, 4, 16), Decimal('2360.576147'), Decimal('24102.699219')),
 (datetime.date(2026, 4, 17), Decimal('2348.987492'), Decimal('24468.480469')),
 (datetime.date(2026, 4, 20), Decimal('2264.194198'), Decimal('24404.390625')),
 (datetime.date(2026, 4, 21), Decimal('2314.638607'), Decimal('24259.960938')),
 (datetime.date(2026, 4, 22), Decimal('2326.664013'), Decimal('24657.570313')),
 (datetime.date(2026, 4, 23), Decimal('2375.714453'), Decimal('24438.500000')),
 (datetime.date(2026, 4, 24), Decimal('2331.095309'), Decimal('24836.599609')),
 (datetime.date(2026, 4, 27), Decimal('2369.154029'), Decimal('24887.099609')),
 (datetime.date(2026, 4, 28), Decimal('2303.884250'), Decimal('24663.800781')),
 (datetime.date(2026, 4, 29), Decimal('2292.765874'), Decimal('24673.240234')),
 (datetime.date(2026, 4, 30), Decimal('2253.620049'), Decimal('24892.310547')),
 (datetime.date(2026, 5, 1), Decimal('2256.949112'), Decimal('25114.439453')),
 (datetime.date(2026, 5, 4), Decimal('2322.587864'), Decimal('25067.800781')),
 (datetime.date(2026, 5, 5), Decimal('2346.171303'), Decimal('25326.130859')),
 (datetime.date(2026, 5, 6), Decimal('2360.644366'), Decimal('25838.939453')),
 (datetime.date(2026, 5, 7), Decimal('2351.013748'), Decimal('25806.199219')),
 (datetime.date(2026, 5, 8), Decimal('2291.302591'), Decimal('26247.080078')),
 (datetime.date(2026, 5, 11), Decimal('2369.964871'), Decimal('26274.130859')),
 (datetime.date(2026, 5, 12), Decimal('2338.594468'), Decimal('26088.199219')),
 (datetime.date(2026, 5, 13), Decimal('2275.747323'), Decimal('26402.339844')),
 (datetime.date(2026, 5, 14), Decimal('2258.483909'), Decimal('26635.220703')),
 (datetime.date(2026, 5, 15), Decimal('2282.595746'), Decimal('26225.140625')),
 (datetime.date(2026, 5, 18), Decimal('2130.749230'), Decimal('26090.730469')),
 (datetime.date(2026, 5, 19), Decimal('2128.892762'), Decimal('25870.710938')),
 (datetime.date(2026, 5, 20), Decimal('2109.342138'), Decimal('26270.359375')),
 (datetime.date(2026, 5, 21), Decimal('2127.468932'), Decimal('26293.099609')),
 (datetime.date(2026, 5, 22), Decimal('2132.144370'), Decimal('26343.970703')),
 (datetime.date(2026, 5, 25), Decimal('2097.658257'), None),
 (datetime.date(2026, 5, 26), Decimal('2110.592972'), Decimal('26656.179688')),
 (datetime.date(2026, 5, 27), Decimal('2072.349216'), Decimal('26674.730469')),
 (datetime.date(2026, 5, 28), Decimal('2022.465974'), Decimal('26917.470703')),
 (datetime.date(2026, 5, 29), Decimal('2008.114463'), Decimal('26972.619141')),
 (datetime.date(2026, 6, 1), Decimal('2005.052057'), Decimal('27086.810547')),
 (datetime.date(2026, 6, 2), Decimal('2003.579447'), Decimal('27093.900391')),
 (datetime.date(2026, 6, 3), Decimal('1858.364048'), Decimal('26853.980469')),
 (datetime.date(2026, 6, 4), Decimal('1811.714991'), Decimal('26830.960938')),
 (datetime.date(2026, 6, 5), Decimal('1769.031733'), Decimal('25709.429688')),
 (datetime.date(2026, 6, 8), Decimal('1687.882685'), Decimal('25929.660156')),
 (datetime.date(2026, 6, 9), Decimal('1690.495085'), Decimal('25678.820313')),
 (datetime.date(2026, 6, 10), Decimal('1638.750414'), Decimal('25169.500000')),
 (datetime.date(2026, 6, 11), Decimal('1620.917391'), Decimal('25809.660156')),
 (datetime.date(2026, 6, 12), Decimal('1671.869047'), Decimal('25888.839844')),
 (datetime.date(2026, 6, 15), Decimal('1725.448928'), Decimal('26683.939453')),
 (datetime.date(2026, 6, 16), Decimal('1794.957660'), Decimal('26376.339844')),
 (datetime.date(2026, 6, 17), Decimal('1791.388678'), Decimal('26021.660156')),
 (datetime.date(2026, 6, 18), Decimal('1748.754974'), Decimal('26517.929688')),
 (datetime.date(2026, 6, 19), Decimal('1710.079111'), None),
 (datetime.date(2026, 6, 22), Decimal('1704.913014'), Decimal('26166.599609')),
 (datetime.date(2026, 6, 23), Decimal('1725.162021'), Decimal('25587.039063')),
 (datetime.date(2026, 6, 24), Decimal('1665.716241'), Decimal('25476.640625')),
 (datetime.date(2026, 6, 25), Decimal('1620.643408'), Decimal('25358.599609')),
 (datetime.date(2026, 6, 26), Decimal('1566.008130'), Decimal('25297.619141')),
 (datetime.date(2026, 6, 29), Decimal('1570.080552'), Decimal('25820.140625')),
 (datetime.date(2026, 6, 30), Decimal('1609.751186'), Decimal('26213.720703')),
 (datetime.date(2026, 7, 1), Decimal('1569.827175'), Decimal('26040.029297')),
 (datetime.date(2026, 7, 2), Decimal('1608.254387'), Decimal('25832.669922')),
 (datetime.date(2026, 7, 3), Decimal('1698.561052'), None),
 (datetime.date(2026, 7, 6), Decimal('1784.262299'), Decimal('26121.160156')),
 (datetime.date(2026, 7, 7), Decimal('1798.557105'), Decimal('25818.689453')),
 (datetime.date(2026, 7, 8), Decimal('1771.222395'), Decimal('25870.650391')),
 (datetime.date(2026, 7, 9), Decimal('1742.249454'), Decimal('26206.890625')),
 (datetime.date(2026, 7, 10), Decimal('1744.695388'), Decimal('26281.609375')),
 (datetime.date(2026, 7, 13), Decimal('1805.486285'), Decimal('25873.179688')),
 (datetime.date(2026, 7, 14), Decimal('1774.090925'), Decimal('26107.009766')),
 (datetime.date(2026, 7, 15), Decimal('1890.309392'), Decimal('26269.230469')),
 (datetime.date(2026, 7, 16), Decimal('1916.758646'), Decimal('25881.949219')),
 (datetime.date(2026, 7, 17), Decimal('1863.006501'), Decimal('25520.240234')),
 (datetime.date(2026, 7, 20), Decimal('1870.817035'), Decimal('25508.070313')),
 (datetime.date(2026, 7, 21), Decimal('1901.773515'), Decimal('25837.210938')),
 (datetime.date(2026, 7, 22), Decimal('1928.655896'), Decimal('25690.900391')),
 (datetime.date(2026, 7, 23), Decimal('1933.413258'), Decimal('25137.689453')),
 (datetime.date(2026, 7, 24), Decimal('1877.460608'), Decimal('24975.820313')),
 (datetime.date(2026, 7, 27), Decimal('1952.902007'), Decimal('24932.080078')),
 (datetime.date(2026, 7, 28), Decimal('1890.452321'), Decimal('24876.910156')),
 (datetime.date(2026, 7, 29), Decimal('1920.488866'), Decimal('24442.939453')),
 (datetime.date(2026, 7, 30), Decimal('1908.741733'), Decimal('25122.179688')),
 (datetime.date(2026, 7, 31), Decimal('1917.571364'), Decimal('25373.849609')),
 (datetime.date(2026, 8, 3), Decimal('1882.930559'), Decimal('25913.900391')),
 (datetime.date(2026, 8, 4), Decimal('1858.537697'), Decimal('26584.990234')),
 (datetime.date(2026, 8, 5), Decimal('1868.621382'), Decimal('26363.439453')),
 (datetime.date(2026, 8, 6), Decimal('1907.436044'), Decimal('26348.349609')),
 (datetime.date(2026, 8, 7), Decimal('1902.162272'), Decimal('26690.619141')),
 (datetime.date(2026, 8, 10), Decimal('1908.940734'), Decimal('26605.359375')),
 (datetime.date(2026, 8, 11), Decimal('1871.397655'), Decimal('26445.449219')),
 (datetime.date(2026, 8, 12), Decimal('1880.486201'), Decimal('26588.490234')),
 (datetime.date(2026, 8, 13), Decimal('1877.743530'), Decimal('26803.029297')),
 (datetime.date(2026, 8, 14), Decimal('1884.394158'), Decimal('26729.160156')),
 (datetime.date(2026, 8, 17), Decimal('1874.401898'), Decimal('26644.910156')),
 (datetime.date(2026, 8, 18), Decimal('1912.273469'), Decimal('26289.710938')),
 (datetime.date(2026, 8, 19), Decimal('1916.399890'), Decimal('26331.089844')),
 (datetime.date(2026, 8, 20), Decimal('2251.734614'), Decimal('26067.169922')),
 (datetime.date(2026, 8, 21), Decimal('2326.528233'), Decimal('26180.460938')),
 (datetime.date(2026, 8, 24), Decimal('2462.403925'), Decimal('25980.189453'))]

In [60]:
cursor.execute("""
SELECT id, symbol, name, market_cap_rank
FROM cryptocurrencies
ORDER BY market_cap_rank
LIMIT 3
""")

top3 = cursor.fetchall()
top3

[('bitcoin', 'btc', 'Bitcoin', 1),
 ('ethereum', 'eth', 'Ethereum', 2),
 ('tether', 'usdt', 'Tether', 3)]

In [61]:
top3_ids = [row[0] for row in top3]

placeholders = ', '.join(['%s'] * len(top3_ids))

query29 = f"""
SELECT
    c.date,
    c.coin_id,
    c.price_usd AS crypto_price,
    s.ticker,
    s.close AS stock_close
FROM crypto_prices c
JOIN stock_prices s
    ON c.date = s.date
WHERE c.coin_id IN ({placeholders})
AND s.ticker IN ('^GSPC', '^IXIC', '^NSEI')
AND c.date BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY c.date, c.coin_id, s.ticker
"""

cursor.execute(query29, top3_ids)

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3),
  'bitcoin',
  Decimal('120514.577856'),
  '^GSPC',
  Decimal('6715.790039')),
 (datetime.date(2025, 10, 3),
  'bitcoin',
  Decimal('120514.577856'),
  '^IXIC',
  Decimal('22780.509766')),
 (datetime.date(2025, 10, 3),
  'bitcoin',
  Decimal('120514.577856'),
  '^NSEI',
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 3),
  'ethereum',
  Decimal('4484.180377'),
  '^GSPC',
  Decimal('6715.790039')),
 (datetime.date(2025, 10, 3),
  'ethereum',
  Decimal('4484.180377'),
  '^IXIC',
  Decimal('22780.509766')),
 (datetime.date(2025, 10, 3),
  'ethereum',
  Decimal('4484.180377'),
  '^NSEI',
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 3),
  'tether',
  Decimal('1.000469'),
  '^GSPC',
  Decimal('6715.790039')),
 (datetime.date(2025, 10, 3),
  'tether',
  Decimal('1.000469'),
  '^IXIC',
  Decimal('22780.509766')),
 (datetime.date(2025, 10, 3),
  'tether',
  Decimal('1.000469'),
  '^NSEI',
  Decimal('24894.250000')),
 (datetime.date(2025, 10, 6),
  'bitcoin',
  Decimal('123488.730597'),
  '^GSPC',
  Decimal('6740.279785')),
 (datetime.date(2025, 10, 6),
  'bitcoin',
  Decimal('123488.730597'),
  '^IXIC',
  Decimal('22941.669922')),
 (datetime.date(2025, 10, 6),
  'bitcoin',
  Decimal('123488.730597'),
  '^NSEI',
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 6),
  'ethereum',
  Decimal('4513.310148'),
  '^GSPC',
  Decimal('6740.279785')),
 (datetime.date(2025, 10, 6),
  'ethereum',
  Decimal('4513.310148'),
  '^IXIC',
  Decimal('22941.669922')),
 (datetime.date(2025, 10, 6),
  'ethereum',
  Decimal('4513.310148'),
  '^NSEI',
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 6),
  'tether',
  Decimal('1.000227'),
  '^GSPC',
  Decimal('6740.279785')),
 (datetime.date(2025, 10, 6),
  'tether',
  Decimal('1.000227'),
  '^IXIC',
  Decimal('22941.669922')),
 (datetime.date(2025, 10, 6),
  'tether',
  Decimal('1.000227'),
  '^NSEI',
  Decimal('25077.650391')),
 (datetime.date(2025, 10, 7),
  'bitcoin',
  Decimal('124739.810888'),
  '^GSPC',
  Decimal('6714.589844')),
 (datetime.date(2025, 10, 7),
  'bitcoin',
  Decimal('124739.810888'),
  '^IXIC',
  Decimal('22788.359375')),
 (datetime.date(2025, 10, 7),
  'bitcoin',
  Decimal('124739.810888'),
  '^NSEI',
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 7),
  'ethereum',
  Decimal('4690.837856'),
  '^GSPC',
  Decimal('6714.589844')),
 (datetime.date(2025, 10, 7),
  'ethereum',
  Decimal('4690.837856'),
  '^IXIC',
  Decimal('22788.359375')),
 (datetime.date(2025, 10, 7),
  'ethereum',
  Decimal('4690.837856'),
  '^NSEI',
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 7),
  'tether',
  Decimal('1.000319'),
  '^GSPC',
  Decimal('6714.589844')),
 (datetime.date(2025, 10, 7),
  'tether',
  Decimal('1.000319'),
  '^IXIC',
  Decimal('22788.359375')),
 (datetime.date(2025, 10, 7),
  'tether',
  Decimal('1.000319'),
  '^NSEI',
  Decimal('25108.300781')),
 (datetime.date(2025, 10, 8),
  'bitcoin',
  Decimal('121463.118082'),
  '^GSPC',
  Decimal('6753.720215')),
 (datetime.date(2025, 10, 8),
  'bitcoin',
  Decimal('121463.118082'),
  '^IXIC',
  Decimal('23043.380859')),
 (datetime.date(2025, 10, 8),
  'bitcoin',
  Decimal('121463.118082'),
  '^NSEI',
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 8),
  'ethereum',
  Decimal('4453.781266'),
  '^GSPC',
  Decimal('6753.720215')),
 (datetime.date(2025, 10, 8),
  'ethereum',
  Decimal('4453.781266'),
  '^IXIC',
  Decimal('23043.380859')),
 (datetime.date(2025, 10, 8),
  'ethereum',
  Decimal('4453.781266'),
  '^NSEI',
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 8),
  'tether',
  Decimal('1.000349'),
  '^GSPC',
  Decimal('6753.720215')),
 (datetime.date(2025, 10, 8),
  'tether',
  Decimal('1.000349'),
  '^IXIC',
  Decimal('23043.380859')),
 (datetime.date(2025, 10, 8),
  'tether',
  Decimal('1.000349'),
  '^NSEI',
  Decimal('25046.150391')),
 (datetime.date(2025, 10, 9),
  'bitcoin',
  Decimal('123342.984698'),
  '^GSPC',
  Decimal('6735.109863')),
 (datetime.date(2025, 10, 9),
  'bitcoin',
  Decimal('123342.984698'),
  '^IXIC',
  Decimal('23024.630859')),
 (datetime.date(2025, 10, 9),
  'bitcoin',
  Decimal('123342.984698'),
  '^NSEI',
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 9),
  'ethereum',
  Decimal('4526.062095'),
  '^GSPC',
  Decimal('6735.109863')),
 (datetime.date(2025, 10, 9),
  'ethereum',
  Decimal('4526.062095'),
  '^IXIC',
  Decimal('23024.630859')),
 (datetime.date(2025, 10, 9),
  'ethereum',
  Decimal('4526.062095'),
  '^NSEI',
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 9),
  'tether',
  Decimal('1.000249'),
  '^GSPC',
  Decimal('6735.109863')),
 (datetime.date(2025, 10, 9),
  'tether',
  Decimal('1.000249'),
  '^IXIC',
  Decimal('23024.630859')),
 (datetime.date(2025, 10, 9),
  'tether',
  Decimal('1.000249'),
  '^NSEI',
  Decimal('25181.800781')),
 (datetime.date(2025, 10, 10),
  'bitcoin',
  Decimal('121718.667577'),
  '^GSPC',
  Decimal('6552.509766')),
 (datetime.date(2025, 10, 10),
  'bitcoin',
  Decimal('121718.667577'),
  '^IXIC',
  Decimal('22204.429688')),
 (datetime.date(2025, 10, 10),
  'bitcoin',
  Decimal('121718.667577'),
  '^NSEI',
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 10),
  'ethereum',
  Decimal('4368.419617'),
  '^GSPC',
  Decimal('6552.509766')),
 (datetime.date(2025, 10, 10),
  'ethereum',
  Decimal('4368.419617'),
  '^IXIC',
  Decimal('22204.429688')),
 (datetime.date(2025, 10, 10),
  'ethereum',
  Decimal('4368.419617'),
  '^NSEI',
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 10),
  'tether',
  Decimal('1.000497'),
  '^GSPC',
  Decimal('6552.509766')),
 (datetime.date(2025, 10, 10),
  'tether',
  Decimal('1.000497'),
  '^IXIC',
  Decimal('22204.429688')),
 (datetime.date(2025, 10, 10),
  'tether',
  Decimal('1.000497'),
  '^NSEI',
  Decimal('25285.349609')),
 (datetime.date(2025, 10, 13),
  'bitcoin',
  Decimal('115060.884178'),
  '^GSPC',
  Decimal('6654.720215')),
 (datetime.date(2025, 10, 13),
  'bitcoin',
  Decimal('115060.884178'),
  '^IXIC',
  Decimal('22694.609375')),
 (datetime.date(2025, 10, 13),
  'bitcoin',
  Decimal('115060.884178'),
  '^NSEI',
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 13),
  'ethereum',
  Decimal('4151.918863'),
  '^GSPC',
  Decimal('6654.720215')),
 (datetime.date(2025, 10, 13),
  'ethereum',
  Decimal('4151.918863'),
  '^IXIC',
  Decimal('22694.609375')),
 (datetime.date(2025, 10, 13),
  'ethereum',
  Decimal('4151.918863'),
  '^NSEI',
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 13),
  'tether',
  Decimal('1.001209'),
  '^GSPC',
  Decimal('6654.720215')),
 (datetime.date(2025, 10, 13),
  'tether',
  Decimal('1.001209'),
  '^IXIC',
  Decimal('22694.609375')),
 (datetime.date(2025, 10, 13),
  'tether',
  Decimal('1.001209'),
  '^NSEI',
  Decimal('25227.349609')),
 (datetime.date(2025, 10, 14),
  'bitcoin',
  Decimal('115226.584290'),
  '^GSPC',
  Decimal('6644.310059')),
 (datetime.date(2025, 10, 14),
  'bitcoin',
  Decimal('115226.584290'),
  '^IXIC',
  Decimal('22521.699219')),
 (datetime.date(2025, 10, 14),
  'bitcoin',
  Decimal('115226.584290'),
  '^NSEI',
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 14),
  'ethereum',
  Decimal('4245.447077'),
  '^GSPC',
  Decimal('6644.310059')),
 (datetime.date(2025, 10, 14),
  'ethereum',
  Decimal('4245.447077'),
  '^IXIC',
  Decimal('22521.699219')),
 (datetime.date(2025, 10, 14),
  'ethereum',
  Decimal('4245.447077'),
  '^NSEI',
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 14),
  'tether',
  Decimal('1.001022'),
  '^GSPC',
  Decimal('6644.310059')),
 (datetime.date(2025, 10, 14),
  'tether',
  Decimal('1.001022'),
  '^IXIC',
  Decimal('22521.699219')),
 (datetime.date(2025, 10, 14),
  'tether',
  Decimal('1.001022'),
  '^NSEI',
  Decimal('25145.500000')),
 (datetime.date(2025, 10, 15),
  'bitcoin',
  Decimal('113066.350785'),
  '^GSPC',
  Decimal('6671.060059')),
 (datetime.date(2025, 10, 15),
  'bitcoin',
  Decimal('113066.350785'),
  '^IXIC',
  Decimal('22670.080078')),
 (datetime.date(2025, 10, 15),
  'bitcoin',
  Decimal('113066.350785'),
  '^NSEI',
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 15),
  'ethereum',
  Decimal('4126.235353'),
  '^GSPC',
  Decimal('6671.060059')),
 (datetime.date(2025, 10, 15),
  'ethereum',
  Decimal('4126.235353'),
  '^IXIC',
  Decimal('22670.080078')),
 (datetime.date(2025, 10, 15),
  'ethereum',
  Decimal('4126.235353'),
  '^NSEI',
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 15),
  'tether',
  Decimal('1.000663'),
  '^GSPC',
  Decimal('6671.060059')),
 (datetime.date(2025, 10, 15),
  'tether',
  Decimal('1.000663'),
  '^IXIC',
  Decimal('22670.080078')),
 (datetime.date(2025, 10, 15),
  'tether',
  Decimal('1.000663'),
  '^NSEI',
  Decimal('25323.550781')),
 (datetime.date(2025, 10, 16),
  'bitcoin',
  Decimal('110844.404172'),
  '^GSPC',
  Decimal('6629.069824')),
 (datetime.date(2025, 10, 16),
  'bitcoin',
  Decimal('110844.404172'),
  '^IXIC',
  Decimal('22562.539063')),
 (datetime.date(2025, 10, 16),
  'bitcoin',
  Decimal('110844.404172'),
  '^NSEI',
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 16),
  'ethereum',
  Decimal('3991.544236'),
  '^GSPC',
  Decimal('6629.069824')),
 (datetime.date(2025, 10, 16),
  'ethereum',
  Decimal('3991.544236'),
  '^IXIC',
  Decimal('22562.539063')),
 (datetime.date(2025, 10, 16),
  'ethereum',
  Decimal('3991.544236'),
  '^NSEI',
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 16),
  'tether',
  Decimal('1.000762'),
  '^GSPC',
  Decimal('6629.069824')),
 (datetime.date(2025, 10, 16),
  'tether',
  Decimal('1.000762'),
  '^IXIC',
  Decimal('22562.539063')),
 (datetime.date(2025, 10, 16),
  'tether',
  Decimal('1.000762'),
  '^NSEI',
  Decimal('25585.300781')),
 (datetime.date(2025, 10, 17),
  'bitcoin',
  Decimal('108168.173534'),
  '^GSPC',
  Decimal('6664.009766')),
 (datetime.date(2025, 10, 17),
  'bitcoin',
  Decimal('108168.173534'),
  '^IXIC',
  Decimal('22679.970703')),
 (datetime.date(2025, 10, 17),
  'bitcoin',
  Decimal('108168.173534'),
  '^NSEI',
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 17),
  'ethereum',
  Decimal('3893.756038'),
  '^GSPC',
  Decimal('6664.009766')),
 (datetime.date(2025, 10, 17),
  'ethereum',
  Decimal('3893.756038'),
  '^IXIC',
  Decimal('22679.970703')),
 (datetime.date(2025, 10, 17),
  'ethereum',
  Decimal('3893.756038'),
  '^NSEI',
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 17),
  'tether',
  Decimal('1.000505'),
  '^GSPC',
  Decimal('6664.009766')),
 (datetime.date(2025, 10, 17),
  'tether',
  Decimal('1.000505'),
  '^IXIC',
  Decimal('22679.970703')),
 (datetime.date(2025, 10, 17),
  'tether',
  Decimal('1.000505'),
  '^NSEI',
  Decimal('25709.849609')),
 (datetime.date(2025, 10, 20),
  'bitcoin',
  Decimal('108655.505250'),
  '^GSPC',
  Decimal('6735.129883')),
 (datetime.date(2025, 10, 20),
  'bitcoin',
  Decimal('108655.505250'),
  '^IXIC',
  Decimal('22990.539063')),
 (datetime.date(2025, 10, 20),
  'bitcoin',
  Decimal('108655.505250'),
  '^NSEI',
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 20),
  'ethereum',
  Decimal('3982.355861'),
  '^GSPC',
  Decimal('6735.129883')),
 (datetime.date(2025, 10, 20),
  'ethereum',
  Decimal('3982.355861'),
  '^IXIC',
  Decimal('22990.539063')),
 (datetime.date(2025, 10, 20),
  'ethereum',
  Decimal('3982.355861'),
  '^NSEI',
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 20),
  'tether',
  Decimal('1.000593'),
  '^GSPC',
  Decimal('6735.129883')),
 (datetime.date(2025, 10, 20),
  'tether',
  Decimal('1.000593'),
  '^IXIC',
  Decimal('22990.539063')),
 (datetime.date(2025, 10, 20),
  'tether',
  Decimal('1.000593'),
  '^NSEI',
  Decimal('25843.150391')),
 (datetime.date(2025, 10, 21),
  'bitcoin',
  Decimal('110535.863014'),
  '^GSPC',
  Decimal('6735.350098')),
 (datetime.date(2025, 10, 21),
  'bitcoin',
  Decimal('110535.863014'),
  '^IXIC',
  Decimal('22953.669922')),
 (datetime.date(2025, 10, 21),
  'bitcoin',
  Decimal('110535.863014'),
  '^NSEI',
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 21),
  'ethereum',
  Decimal('3980.073280'),
  '^GSPC',
  Decimal('6735.350098')),
 (datetime.date(2025, 10, 21),
  'ethereum',
  Decimal('3980.073280'),
  '^IXIC',
  Decimal('22953.669922')),
 (datetime.date(2025, 10, 21),
  'ethereum',
  Decimal('3980.073280'),
  '^NSEI',
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 21),
  'tether',
  Decimal('1.000533'),
  '^GSPC',
  Decimal('6735.350098')),
 (datetime.date(2025, 10, 21),
  'tether',
  Decimal('1.000533'),
  '^IXIC',
  Decimal('22953.669922')),
 (datetime.date(2025, 10, 21),
  'tether',
  Decimal('1.000533'),
  '^NSEI',
  Decimal('25868.599609')),
 (datetime.date(2025, 10, 22),
  'bitcoin',
  Decimal('108301.754625'),
  '^GSPC',
  Decimal('6699.399902')),
 (datetime.date(2025, 10, 22),
  'bitcoin',
  Decimal('108301.754625'),
  '^IXIC',
  Decimal('22740.400391')),
 (datetime.date(2025, 10, 22),
  'bitcoin',
  Decimal('108301.754625'),
  '^NSEI',
  None),
 (datetime.date(2025, 10, 22),
  'ethereum',
  Decimal('3866.151783'),
  '^GSPC',
  Decimal('6699.399902')),
 (datetime.date(2025, 10, 22),
  'ethereum',
  Decimal('3866.151783'),
  '^IXIC',
  Decimal('22740.400391')),
 (datetime.date(2025, 10, 22),
  'ethereum',
  Decimal('3866.151783'),
  '^NSEI',
  None),
 (datetime.date(2025, 10, 22),
  'tether',
  Decimal('1.000546'),
  '^GSPC',
  Decimal('6699.399902')),
 (datetime.date(2025, 10, 22),
  'tether',
  Decimal('1.000546'),
  '^IXIC',
  Decimal('22740.400391')),
 (datetime.date(2025, 10, 22), 'tether', Decimal('1.000546'), '^NSEI', None),
 (datetime.date(2025, 10, 23),
  'bitcoin',
  Decimal('107591.460509'),
  '^GSPC',
  Decimal('6738.439941')),
 (datetime.date(2025, 10, 23),
  'bitcoin',
  Decimal('107591.460509'),
  '^IXIC',
  Decimal('22941.800781')),
 (datetime.date(2025, 10, 23),
  'bitcoin',
  Decimal('107591.460509'),
  '^NSEI',
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 23),
  'ethereum',
  Decimal('3805.881864'),
  '^GSPC',
  Decimal('6738.439941')),
 (datetime.date(2025, 10, 23),
  'ethereum',
  Decimal('3805.881864'),
  '^IXIC',
  Decimal('22941.800781')),
 (datetime.date(2025, 10, 23),
  'ethereum',
  Decimal('3805.881864'),
  '^NSEI',
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 23),
  'tether',
  Decimal('1.000383'),
  '^GSPC',
  Decimal('6738.439941')),
 (datetime.date(2025, 10, 23),
  'tether',
  Decimal('1.000383'),
  '^IXIC',
  Decimal('22941.800781')),
 (datetime.date(2025, 10, 23),
  'tether',
  Decimal('1.000383'),
  '^NSEI',
  Decimal('25891.400391')),
 (datetime.date(2025, 10, 24),
  'bitcoin',
  Decimal('110109.305225'),
  '^GSPC',
  Decimal('6791.689941')),
 (datetime.date(2025, 10, 24),
  'bitcoin',
  Decimal('110109.305225'),
  '^IXIC',
  Decimal('23204.869141')),
 (datetime.date(2025, 10, 24),
  'bitcoin',
  Decimal('110109.305225'),
  '^NSEI',
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 24),
  'ethereum',
  Decimal('3857.590009'),
  '^GSPC',
  Decimal('6791.689941')),
 (datetime.date(2025, 10, 24),
  'ethereum',
  Decimal('3857.590009'),
  '^IXIC',
  Decimal('23204.869141')),
 (datetime.date(2025, 10, 24),
  'ethereum',
  Decimal('3857.590009'),
  '^NSEI',
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 24),
  'tether',
  Decimal('1.000449'),
  '^GSPC',
  Decimal('6791.689941')),
 (datetime.date(2025, 10, 24),
  'tether',
  Decimal('1.000449'),
  '^IXIC',
  Decimal('23204.869141')),
 (datetime.date(2025, 10, 24),
  'tether',
  Decimal('1.000449'),
  '^NSEI',
  Decimal('25795.150391')),
 (datetime.date(2025, 10, 27),
  'bitcoin',
  Decimal('114419.221697'),
  '^GSPC',
  Decimal('6875.160156')),
 (datetime.date(2025, 10, 27),
  'bitcoin',
  Decimal('114419.221697'),
  '^IXIC',
  Decimal('23637.460938')),
 (datetime.date(2025, 10, 27),
  'bitcoin',
  Decimal('114419.221697'),
  '^NSEI',
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 27),
  'ethereum',
  Decimal('4158.567622'),
  '^GSPC',
  Decimal('6875.160156')),
 (datetime.date(2025, 10, 27),
  'ethereum',
  Decimal('4158.567622'),
  '^IXIC',
  Decimal('23637.460938')),
 (datetime.date(2025, 10, 27),
  'ethereum',
  Decimal('4158.567622'),
  '^NSEI',
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 27),
  'tether',
  Decimal('1.000095'),
  '^GSPC',
  Decimal('6875.160156')),
 (datetime.date(2025, 10, 27),
  'tether',
  Decimal('1.000095'),
  '^IXIC',
  Decimal('23637.460938')),
 (datetime.date(2025, 10, 27),
  'tether',
  Decimal('1.000095'),
  '^NSEI',
  Decimal('25966.050781')),
 (datetime.date(2025, 10, 28),
  'bitcoin',
  Decimal('114085.331238'),
  '^GSPC',
  Decimal('6890.890137')),
 (datetime.date(2025, 10, 28),
  'bitcoin',
  Decimal('114085.331238'),
  '^IXIC',
  Decimal('23827.490234')),
 (datetime.date(2025, 10, 28),
  'bitcoin',
  Decimal('114085.331238'),
  '^NSEI',
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 28),
  'ethereum',
  Decimal('4117.287078'),
  '^GSPC',
  Decimal('6890.890137')),
 (datetime.date(2025, 10, 28),
  'ethereum',
  Decimal('4117.287078'),
  '^IXIC',
  Decimal('23827.490234')),
 (datetime.date(2025, 10, 28),
  'ethereum',
  Decimal('4117.287078'),
  '^NSEI',
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 28),
  'tether',
  Decimal('1.000133'),
  '^GSPC',
  Decimal('6890.890137')),
 (datetime.date(2025, 10, 28),
  'tether',
  Decimal('1.000133'),
  '^IXIC',
  Decimal('23827.490234')),
 (datetime.date(2025, 10, 28),
  'tether',
  Decimal('1.000133'),
  '^NSEI',
  Decimal('25936.199219')),
 (datetime.date(2025, 10, 29),
  'bitcoin',
  Decimal('112893.852036'),
  '^GSPC',
  Decimal('6890.589844')),
 (datetime.date(2025, 10, 29),
  'bitcoin',
  Decimal('112893.852036'),
  '^IXIC',
  Decimal('23958.470703')),
 (datetime.date(2025, 10, 29),
  'bitcoin',
  Decimal('112893.852036'),
  '^NSEI',
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 29),
  'ethereum',
  Decimal('3978.812010'),
  '^GSPC',
  Decimal('6890.589844')),
 (datetime.date(2025, 10, 29),
  'ethereum',
  Decimal('3978.812010'),
  '^IXIC',
  Decimal('23958.470703')),
 (datetime.date(2025, 10, 29),
  'ethereum',
  Decimal('3978.812010'),
  '^NSEI',
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 29),
  'tether',
  Decimal('1.000317'),
  '^GSPC',
  Decimal('6890.589844')),
 (datetime.date(2025, 10, 29),
  'tether',
  Decimal('1.000317'),
  '^IXIC',
  Decimal('23958.470703')),
 (datetime.date(2025, 10, 29),
  'tether',
  Decimal('1.000317'),
  '^NSEI',
  Decimal('26053.900391')),
 (datetime.date(2025, 10, 30),
  'bitcoin',
  Decimal('110026.087620'),
  '^GSPC',
  Decimal('6822.339844')),
 (datetime.date(2025, 10, 30),
  'bitcoin',
  Decimal('110026.087620'),
  '^IXIC',
  Decimal('23581.140625')),
 (datetime.date(2025, 10, 30),
  'bitcoin',
  Decimal('110026.087620'),
  '^NSEI',
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 30),
  'ethereum',
  Decimal('3902.801947'),
  '^GSPC',
  Decimal('6822.339844')),
 (datetime.date(2025, 10, 30),
  'ethereum',
  Decimal('3902.801947'),
  '^IXIC',
  Decimal('23581.140625')),
 (datetime.date(2025, 10, 30),
  'ethereum',
  Decimal('3902.801947'),
  '^NSEI',
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 30),
  'tether',
  Decimal('1.000329'),
  '^GSPC',
  Decimal('6822.339844')),
 (datetime.date(2025, 10, 30),
  'tether',
  Decimal('1.000329'),
  '^IXIC',
  Decimal('23581.140625')),
 (datetime.date(2025, 10, 30),
  'tether',
  Decimal('1.000329'),
  '^NSEI',
  Decimal('25877.849609')),
 (datetime.date(2025, 10, 31),
  'bitcoin',
  Decimal('108409.379925'),
  '^GSPC',
  Decimal('6840.200195')),
 (datetime.date(2025, 10, 31),
  'bitcoin',
  Decimal('108409.379925'),
  '^IXIC',
  Decimal('23724.960938')),
 (datetime.date(2025, 10, 31),
  'bitcoin',
  Decimal('108409.379925'),
  '^NSEI',
  Decimal('25722.099609')),
 (datetime.date(2025, 10, 31),
  'ethereum',
  Decimal('3801.551505'),
  '^GSPC',
  Decimal('6840.200195')),
 (datetime.date(2025, 10, 31),
  'ethereum',
  Decimal('3801.551505'),
  '^IXIC',
  Decimal('23724.960938')),
 (datetime.date(2025, 10, 31),
  'ethereum',

In [62]:
cursor.execute("""
SELECT
    c.date,
    c.price_usd AS bitcoin_price,
    o.price_usd AS oil_price,
    s.close AS sp500_close
FROM crypto_prices c
JOIN oil_prices o
    ON c.date = o.date
JOIN stock_prices s
    ON c.date = s.date
WHERE c.coin_id = 'bitcoin'
AND s.ticker = '^GSPC'
ORDER BY c.date
""")

result = cursor.fetchall()
result

[(datetime.date(2025, 10, 3),
  Decimal('120514.577856'),
  Decimal('61.650000'),
  Decimal('6715.790039')),
 (datetime.date(2025, 10, 6),
  Decimal('123488.730597'),
  Decimal('62.490000'),
  Decimal('6740.279785')),
 (datetime.date(2025, 10, 7),
  Decimal('124739.810888'),
  Decimal('62.520000'),
  Decimal('6714.589844')),
 (datetime.date(2025, 10, 8),
  Decimal('121463.118082'),
  Decimal('63.370000'),
  Decimal('6753.720215')),
 (datetime.date(2025, 10, 9),
  Decimal('123342.984698'),
  Decimal('62.360000'),
  Decimal('6735.109863')),
 (datetime.date(2025, 10, 10),
  Decimal('121718.667577'),
  Decimal('59.750000'),
  Decimal('6552.509766')),
 (datetime.date(2025, 10, 14),
  Decimal('115226.584290'),
  Decimal('59.520000'),
  Decimal('6644.310059')),
 (datetime.date(2025, 10, 15),
  Decimal('113066.350785'),
  Decimal('59.080000'),
  Decimal('6671.060059')),
 (datetime.date(2025, 10, 16),
  Decimal('110844.404172'),
  Decimal('58.290000'),
  Decimal('6629.069824')),
 (datetime.date(2025, 10, 17),
  Decimal('108168.173534'),
  Decimal('58.300000'),
  Decimal('6664.009766')),
 (datetime.date(2025, 10, 20),
  Decimal('108655.505250'),
  Decimal('58.340000'),
  Decimal('6735.129883')),
 (datetime.date(2025, 10, 21),
  Decimal('110535.863014'),
  Decimal('58.660000'),
  Decimal('6735.350098')),
 (datetime.date(2025, 10, 22),
  Decimal('108301.754625'),
  Decimal('59.300000'),
  Decimal('6699.399902')),
 (datetime.date(2025, 10, 23),
  Decimal('107591.460509'),
  Decimal('62.440000'),
  Decimal('6738.439941')),
 (datetime.date(2025, 10, 24),
  Decimal('110109.305225'),
  Decimal('62.270000'),
  Decimal('6791.689941')),
 (datetime.date(2025, 10, 27),
  Decimal('114419.221697'),
  Decimal('62.130000'),
  Decimal('6875.160156')),
 (datetime.date(2025, 10, 28),
  Decimal('114085.331238'),
  Decimal('60.970000'),
  Decimal('6890.890137')),
 (datetime.date(2025, 10, 29),
  Decimal('112893.852036'),
  Decimal('61.260000'),
  Decimal('6890.589844')),
 (datetime.date(2025, 10, 30),
  Decimal('110026.087620'),
  Decimal('61.360000'),
  Decimal('6822.339844')),
 (datetime.date(2025, 10, 31),
  Decimal('108409.379925'),
  Decimal('61.750000'),
  Decimal('6840.200195')),
 (datetime.date(2025, 11, 3),
  Decimal('110499.522383'),
  Decimal('61.790000'),
  Decimal('6851.970215')),
 (datetime.date(2025, 11, 4),
  Decimal('106451.706533'),
  Decimal('61.380000'),
  Decimal('6771.549805')),
 (datetime.date(2025, 11, 5),
  Decimal('101480.766596'),
  Decimal('60.400000'),
  Decimal('6796.290039')),
 (datetime.date(2025, 11, 6),
  Decimal('103878.933600'),
  Decimal('60.240000'),
  Decimal('6720.319824')),
 (datetime.date(2025, 11, 7),
  Decimal('101261.645510'),
  Decimal('60.540000'),
  Decimal('6728.799805')),
 (datetime.date(2025, 11, 10),
  Decimal('104610.228536'),
  Decimal('60.940000'),
  Decimal('6832.430176')),
 (datetime.date(2025, 11, 12),
  Decimal('103112.210062'),
  Decimal('59.300000'),
  Decimal('6850.919922')),
 (datetime.date(2025, 11, 13),
  Decimal('101633.694316'),
  Decimal('59.540000'),
  Decimal('6737.490234')),
 (datetime.date(2025, 11, 14),
  Decimal('99480.307091'),
  Decimal('60.870000'),
  Decimal('6734.109863')),
 (datetime.date(2025, 11, 17),
  Decimal('94188.276689'),
  Decimal('60.660000'),
  Decimal('6672.410156')),
 (datetime.date(2025, 11, 18),
  Decimal('92100.364524'),
  Decimal('61.510000'),
  Decimal('6617.319824')),
 (datetime.date(2025, 11, 19),
  Decimal('92903.180085'),
  Decimal('60.270000'),
  Decimal('6642.160156')),
 (datetime.date(2025, 11, 20),
  Decimal('91408.357334'),
  Decimal('60.070000'),
  Decimal('6538.759766')),
 (datetime.date(2025, 11, 21),
  Decimal('86618.471559'),
  Decimal('58.860000'),
  Decimal('6602.990234')),
 (datetime.date(2025, 11, 24),
  Decimal('86740.117739'),
  Decimal('59.110000'),
  Decimal('6705.120117')),
 (datetime.date(2025, 11, 25),
  Decimal('88256.043956'),
  Decimal('58.250000'),
  Decimal('6765.879883')),
 (datetime.date(2025, 11, 26),
  Decimal('87317.004551'),
  Decimal('58.810000'),
  Decimal('6812.609863')),
 (datetime.date(2025, 11, 28),
  Decimal('91323.628276'),
  Decimal('58.580000'),
  Decimal('6849.089844')),
 (datetime.date(2025, 12, 1),
  Decimal('90359.868732'),
  Decimal('59.470000'),
  Decimal('6812.629883')),
 (datetime.date(2025, 12, 2),
  Decimal('86303.897664'),
  Decimal('58.810000'),
  Decimal('6829.370117')),
 (datetime.date(2025, 12, 3),
  Decimal('91320.079425'),
  Decimal('59.090000'),
  Decimal('6849.720215')),
 (datetime.date(2025, 12, 4),
  Decimal('93428.594515'),
  Decimal('59.820000'),
  Decimal('6857.120117')),
 (datetime.date(2025, 12, 5),
  Decimal('92119.190478'),
  Decimal('60.230000'),
  Decimal('6870.399902')),
 (datetime.date(2025, 12, 8),
  Decimal('90398.448757'),
  Decimal('59.040000'),
  Decimal('6846.509766')),
 (datetime.date(2025, 12, 9),
  Decimal('90626.037343'),
  Decimal('58.400000'),
  Decimal('6840.509766')),
 (datetime.date(2025, 12, 10),
  Decimal('92686.104020'),
  Decimal('58.670000'),
  Decimal('6886.680176')),
 (datetime.date(2025, 12, 11),
  Decimal('91986.581072'),
  Decimal('57.760000'),
  Decimal('6901.000000')),
 (datetime.date(2025, 12, 12),
  Decimal('92525.868003'),
  Decimal('57.610000'),
  Decimal('6827.410156')),
 (datetime.date(2025, 12, 15),
  Decimal('88184.410931'),
  Decimal('56.970000'),
  Decimal('6816.509766')),
 (datetime.date(2025, 12, 16),
  Decimal('86413.221381'),
  Decimal('55.440000'),
  Decimal('6800.259766')),
 (datetime.date(2025, 12, 17),
  Decimal('87719.681398'),
  Decimal('56.070000'),
  Decimal('6721.430176')),
 (datetime.date(2025, 12, 18),
  Decimal('86196.821373'),
  Decimal('56.220000'),
  Decimal('6774.759766')),
 (datetime.date(2025, 12, 19),
  Decimal('85450.179648'),
  Decimal('56.800000'),
  Decimal('6834.500000')),
 (datetime.date(2025, 12, 22),
  Decimal('88672.329679'),
  Decimal('58.180000'),
  Decimal('6878.490234')),
 (datetime.date(2025, 12, 23),
  Decimal('88489.724042'),
  Decimal('58.550000'),
  Decimal('6909.790039')),
 (datetime.date(2025, 12, 24),
  Decimal('87496.146692'),
  Decimal('58.720000'),
  Decimal('6932.049805')),
 (datetime.date(2025, 12, 26),
  Decimal('87192.234737'),
  Decimal('56.600000'),
  Decimal('6929.939941')),
 (datetime.date(2025, 12, 29),
  Decimal('87867.039434'),
  Decimal('57.890000'),
  Decimal('6905.740234')),
 (datetime.date(2025, 12, 30),
  Decimal('87154.682406'),
  Decimal('57.790000'),
  Decimal('6896.240234')),
 (datetime.date(2025, 12, 31),
  Decimal('88363.722236'),
  Decimal('57.260000'),
  Decimal('6845.500000')),
 (datetime.date(2026, 1, 2),
  Decimal('88764.126241'),
  Decimal('57.210000'),
  Decimal('6858.470215')),
 (datetime.date(2026, 1, 5),
  Decimal('91879.577226'),
  Decimal('58.100000'),
  Decimal('6902.049805')),
 (datetime.date(2026, 1, 6),
  Decimal('93879.947973'),
  Decimal('56.970000'),
  Decimal('6944.819824')),
 (datetime.date(2026, 1, 7),
  Decimal('93649.631976'),
  Decimal('56.010000'),
  Decimal('6920.930176')),
 (datetime.date(2026, 1, 8),
  Decimal('91286.033144'),
  Decimal('57.740000'),
  Decimal('6921.459961')),
 (datetime.date(2026, 1, 9),
  Decimal('91027.666170'),
  Decimal('58.960000'),
  Decimal('6966.279785')),
 (datetime.date(2026, 1, 12),
  Decimal('90856.559102'),
  Decimal('59.390000'),
  Decimal('6977.270020')),
 (datetime.date(2026, 1, 13),
  Decimal('91200.627615'),
  Decimal('60.850000'),
  Decimal('6963.740234')),
 (datetime.date(2026, 1, 14),
  Decimal('95429.157322'),
  Decimal('61.840000'),
  Decimal('6926.600098')),
 (datetime.date(2026, 1, 15),
  Decimal('96898.760711'),
  Decimal('59.130000'),
  Decimal('6944.470215')),
 (datetime.date(2026, 1, 16),
  Decimal('95593.307837'),
  Decimal('59.400000'),
  Decimal('6940.009766')),
 (datetime.date(2026, 1, 20),
  Decimal('92566.012780'),
  Decimal('60.300000'),
  Decimal('6796.859863')),
 (datetime.date(2026, 1, 21),
  Decimal('88416.886862'),
  Decimal('60.380000'),
  Decimal('6875.620117')),
 (datetime.date(2026, 1, 22),
  Decimal('89453.904737'),
  Decimal('59.240000'),
  Decimal('6913.350098')),
 (datetime.date(2026, 1, 23),
  Decimal('89483.651630'),
  Decimal('60.700000'),
  Decimal('6915.609863')),
 (datetime.date(2026, 1, 26),
  Decimal('86625.331281'),
  Decimal('60.460000'),
  Decimal('6950.229980')),
 (datetime.date(2026, 1, 27),
  Decimal('88249.901418'),
  Decimal('62.040000'),
  Decimal('6978.600098')),
 (datetime.date(2026, 1, 28),
  Decimal('89141.650360'),
  Decimal('62.750000'),
  Decimal('6978.029785')),
 (datetime.date(2026, 1, 29),
  Decimal('89212.208242'),
  Decimal('64.770000'),
  Decimal('6969.009766')),
 (datetime.date(2026, 1, 30),
  Decimal('84630.420667'),
  Decimal('64.500000'),
  Decimal('6939.029785')),
 (datetime.date(2026, 2, 2),
  Decimal('76895.586656'),
  Decimal('61.600000'),
  Decimal('6976.439941')),
 (datetime.date(2026, 2, 3),
  Decimal('78670.589228'),
  Decimal('62.620000'),
  Decimal('6917.810059')),
 (datetime.date(2026, 2, 4),
  Decimal('75628.041733'),
  Decimal('64.560000'),
  Decimal('6882.720215')),
 (datetime.date(2026, 2, 5),
  Decimal('73059.179867'),
  Decimal('62.900000'),
  Decimal('6798.399902')),
 (datetime.date(2026, 2, 6),
  Decimal('62778.217566'),
  Decimal('63.770000'),
  Decimal('6932.299805')),
 (datetime.date(2026, 2, 9),
  Decimal('70398.085033'),
  Decimal('64.530000'),
  Decimal('6964.819824')),
 (datetime.date(2026, 2, 10),
  Decimal('70175.147492'),
  Decimal('64.200000'),
  Decimal('6941.810059')),
 (datetime.date(2026, 2, 11),
  Decimal('68841.872376'),
  Decimal('64.800000'),
  Decimal('6941.470215')),
 (datetime.date(2026, 2, 12),
  Decimal('67090.579340'),
  Decimal('63.080000'),
  Decimal('6832.759766')),
 (datetime.date(2026, 2, 13),
  Decimal('66258.529549'),
  Decimal('63.050000'),
  Decimal('6836.169922')),
 (datetime.date(2026, 2, 17),
  Decimal('68859.776187'),
  Decimal('62.530000'),
  Decimal('6843.220215')),
 (datetime.date(2026, 2, 18),
  Decimal('67559.295733'),
  Decimal('65.330000'),
  Decimal('6881.310059')),
 (datetime.date(2026, 2, 19),
  Decimal('66426.619535'),
  Decimal('66.660000'),
  Decimal('6861.890137')),
 (datetime.date(2026, 2, 20),
  Decimal('66976.029364'),
  Decimal('66.690000'),
  Decimal('6909.509766')),
 (datetime.date(2026, 2, 23),
  Decimal('65192.188701'),
  Decimal('66.360000'),
  Decimal('6837.750000')),
 (datetime.date(2026, 2, 24),
  Decimal('64737.901970'),
  Decimal('65.620000'),
  Decimal('6890.069824')),
 (datetime.date(2026, 2, 25),
  Decimal('64073.548946'),
  Decimal('65.300000'),
  Decimal('6946.129883')),
 (datetime.date(2026, 2, 26),
  Decimal('67850.105213'),
  Decimal('65.100000'),
  Decimal('6908.859863')),
 (datetime.date(2026, 2, 27),
  Decimal('67496.841640'),
  Decimal('66.960000'),
  Decimal('6878.879883')),
 (datetime.date(2026, 3, 2),
  Decimal('65824.421669'),
  Decimal('71.130000'),
  Decimal('6881.620117')),
 (datetime.date(2026, 3, 3),
  Decimal('68815.936339'),
  Decimal('74.480000'),
  Decimal('6816.629883')),
 (datetime.date(2026, 3, 4),
  Decimal('68287.463034'),
  Decimal('74.580000'),
  Decimal('6869.500000')),
 (datetime.date(2026, 3, 5),
  Decimal('72752.301567'),
  Decimal('80.880000'),
  Decimal('6830.709961')),
 (datetime.date(2026, 3, 6),
  Decimal('70868.218196'),
  Decimal('90.770000'),
  Decimal('6740.020020')),
 (datetime.date(2026, 3, 9),
  Decimal('66042.751079'),
  Decimal('94.650000'),
  Decimal('6795.990234')),
 (datetime.date(2026, 3, 10),
  Decimal('68430.609260'),
  Decimal('83.710000'),
  Decimal('6781.479980')),
 (datetime.date(2026, 3, 11),
  Decimal('69849.203531'),
  Decimal('86.800000'),
  Decimal('6775.799805')),
 (datetime.date(2026, 3, 12),
  Decimal('70028.959876'),
  Decimal('95.610000'),
  Decimal('6672.620117')),
 (datetime.date(2026, 3, 13),
  Decimal('70417.193886'),
  Decimal('98.480000'),
  Decimal('6632.189941')),
 (datetime.date(2026, 3, 16),
  Decimal('72934.294072'),
  Decimal('93.390000'),
  Decimal('6699.379883')),
 (datetime.date(2026, 3, 17),
  Decimal('74679.370908'),
  Decimal('96.010000'),
  Decimal('6716.089844')),
 (datetime.date(2026, 3, 18),
  Decimal('74004.690809'),
  Decimal('96.120000'),
  Decimal('6624.700195')),
 (datetime.date(2026, 3, 19),
  Decimal('71220.047303'),
  Decimal('96.110000'),
  Decimal('6606.490234')),
 (datetime.date(2026, 3, 20),
  Decimal('69936.199321'),
  Decimal('98.710000'),
  Decimal('6506.479980')),
 (datetime.date(2026, 3, 23),
  Decimal('67933.429481'),
  Decimal('89.330000'),
  Decimal('6581.000000')),
 (datetime.date(2026, 3, 24),
  Decimal('70987.251854'),
  Decimal('93.180000'),
  Decimal('6556.370117')),
 (datetime.date(2026, 3, 25),
  Decimal('70528.863456'),
  Decimal('91.510000'),
  Decimal('6591.899902')),
 (datetime.date(2026, 3, 26),
  Decimal('71303.585451'),
  Decimal('96.180000'),
  Decimal('6477.160156')),
 (datetime.date(2026, 3, 27),
  Decimal('68727.212290'),
  Decimal('101.260000'),
  Decimal('6368.850098')),
 (datetime.date(2026, 3, 30),
  Decimal('65947.031926'),
  Decimal('104.690000'),
  Decimal('6343.720215')),
 (datetime.date(2026, 3, 31),
  Decimal('66691.271478'),
  Decimal('102.860000'),
  Decimal('6528.520020')),
 (datetime.date(2026, 4, 1),
  Decimal('68107.474564'),
  Decimal('101.900000'),
  Decimal('6575.319824')),
 (datetime.date(2026, 4, 2),
  Decimal('67959.875247'),
  Decimal('113.230000'),
  Decimal('6582.689941')),
 (datetime.date(2026, 4, 6),
  Decimal('69002.038479'),
  Decimal('114.010000'),
  Decimal('6611.830078')),
 (datetime.date(2026, 4, 7),
  Decimal('68672.246575'),
  Decimal('114.580000'),
  Decimal('6616.850098')),
 (datetime.date(2026, 4, 8),
  Decimal('71661.763724'),
  Decimal('96.170000'),
  Decimal('6782.810059')),
 (datetime.date(2026, 4, 9),
  Decimal('70644.794162'),
  Decimal('99.620000'),
  Decimal('6824.660156')),
 (datetime.date(2026, 4, 10),
  Decimal('71367.802917'),
  Decimal('98.340000'),
  Decimal('6816.890137')),
 (datetime.date(2026, 4, 13),
  Decimal('70660.639612'),
  Decimal('100.720000'),
  Decimal('6886.240234')),
 (datetime.date(2026, 4, 14),
  Decimal('74481.641429'),
  Decimal('93.070000'),
  Decimal('6967.379883')),
 (datetime.date(2026, 4, 15),
  Decimal('74297.347595'),
  Decimal('93.040000'),
  Decimal('7022.950195')),
 (datetime.date(2026, 4, 16),
  Decimal('74826.313088'),
  Decimal('96.460000'),
  Decimal('7041.279785')),
 (datetime.date(2026, 4, 17),
  Decimal('75111.956745'),
  Decimal('85.910000'),
  Decimal('7126.060059')),
 (datetime.date(2026, 4, 20),
  Decimal('73841.021738'),
  Decimal('91.060000'),
  Decimal('7109.140137')),
 (datetime.date(2026, 4, 21),
  Decimal('75858.035468'),
  Decimal('93.640000'),
  Decimal('7064.009766')),
 (datetime.date(2026, 4, 22),
  Decimal('76326.191702'),
  Decimal('94.760000'),
  Decimal('7137.899902')),
 (datetime.date(2026, 4, 23),
  Decimal('78238.816750'),
  Decimal('99.270000'),
  Decimal('7108.399902')),
 (datetime.date(2026, 4, 24),
  Decimal('78275.325827'),
  Decimal('98.420000'),
  Decimal('7165.080078')),
 (datetime.date(2026, 4, 27),
  Decimal('78637.743562'),
  Decimal('99.890000'),
  Decimal('7173.910156')),
 (datetime.date(2026, 4, 28),
  Decimal('77366.784422'),
  Decimal('103.450000'),
  Decimal('7138.799805')),
 (datetime.date(2026, 4, 29),
  Decimal('76331.864435'),
  Decimal('110.470000'),
  Decimal('7135.950195')),
 (datetime.date(2026, 4, 30),
  Decimal('75784.957436'),
  Decimal('108.640000'),
  Decimal('7209.009766')),
 (datetime.date(2026, 5, 1),
  Decimal('76296.796484'),
  Decimal('105.380000'),
  Decimal('7230.120117')),
 (datetime.date(2026, 5, 4),
  Decimal('78512.092465'),
  Decimal('109.760000'),
  Decimal('7200.750000')),
 (datetime.date(2026, 5, 5),
  Decimal('79825.875113'),
  Decimal('105.660000'),
  Decimal('7259.220215')),
 (datetime.date(2026, 5, 6),
  Decimal('80913.961375'),
  Decimal('98.750000'),
  Decimal('7365.120117')),
 (datetime.date(2026, 5, 7),
  Decimal('81436.859368'),
  Decimal('98.380000'),
  Decimal('7337.109863')),
 (datetime.date(2026, 5, 8),
  Decimal('80024.907672'),
  Decimal('98.870000'),
  Decimal('7398.930176')),
 (datetime.date(2026, 5, 11),
  Decimal('82018.371124'),
  Decimal('101.560000'),
  Decimal('7412.839844')),
 (datetime.date(2026, 5, 12),
  Decimal('81627.566050'),
  Decimal('105.780000'),
  Decimal('7400.959961')),
 (datetime.date(2026, 5, 13),
  Decimal('80482.143778'),
  Decimal('104.520000'),
  Decimal('7444.250000')),
 (datetime.date(2026, 5, 14),
  Decimal('79288.842087'),
  Decimal('104.660000'),
  Decimal('7501.240234')),
 (datetime.date(2026, 5, 15),
  Decimal('81059.115954'),
  Decimal('108.990000'),
  Decimal('7408.500000')),
 (datetime.date(2026, 5, 18),
  Decimal('77428.518661'),
  Decimal('112.250000'),
  Decimal('7403.049805')),
 (datetime.date(2026, 5, 19),
  Decimal('76959.405715'),
  Decimal('112.090000'),
  Decimal('7353.609863')),
 (datetime.date(2026, 5, 20),
  Decimal('76758.731559'),
  Decimal('101.690000'),
  Decimal('7432.970215')),
 (datetime.date(2026, 5, 21),
  Decimal('77470.396149'),
  Decimal('100.200000'),
  Decimal('7445.720215')),
 (datetime.date(2026, 5, 22),
  Decimal('77550.383083'),
  Decimal('100.350000'),
  Decimal('7473.470215')),
 (datetime.date(2026, 5, 26),
  Decimal('77258.399124'),
  Decimal('97.630000'),
  Decimal('7519.120117')),
 (datetime.date(2026, 5, 27),
  Decimal('75851.104096'),
  Decimal('92.350000'),
  Decimal('7520.359863')),
 (datetime.date(2026, 5, 28),
  Decimal('74339.616947'),
  Decimal('92.650000'),
  Decimal('7563.629883')),
 (datetime.date(2026, 5, 29),
  Decimal('73651.642551'),
  Decimal('91.160000'),
  Decimal('7580.060059')),
 (datetime.date(2026, 6, 1),
  Decimal('73598.668124'),
  Decimal('95.960000'),
  Decimal('7599.959961')),
 (datetime.date(2026, 6, 2),
  Decimal('71320.293065'),
  Decimal('97.470000'),
  Decimal('7609.779785')),
 (datetime.date(2026, 6, 3),
  Decimal('66727.264155'),
  Decimal('99.760000'),
  Decimal('7553.680176')),
 (datetime.date(2026, 6, 4),
  Decimal('64046.610646'),
  Decimal('96.830000'),
  Decimal('7584.310059')),
 (datetime.date(2026, 6, 5),
  Decimal('63810.659238'),
  Decimal('94.320000'),
  Decimal('7383.740234')),
 (datetime.date(2026, 6, 8),
  Decimal('63273.537431'),
  Decimal('95.000000'),
  Decimal('7405.729980')),
 (datetime.date(2026, 6, 9),
  Decimal('63069.147793'),
  Decimal('91.900000'),
  Decimal('7386.649902')),
 (datetime.date(2026, 6, 10),
  Decimal('61669.763842'),
  Decimal('93.680000'),
  Decimal('7266.990234')),
 (datetime.date(2026, 6, 11),
  Decimal('61480.144433'),
  Decimal('91.580000'),
  Decimal('7394.299805')),
 (datetime.date(2026, 6, 12),
  Decimal('63555.661811'),
  Decimal('88.620000'),
  Decimal('7431.459961')),
 (datetime.date(2026, 6, 15),
  Decimal('65709.310946'),
  Decimal('84.650000'),
  Decimal('7554.290039')),
 (datetime.date(2026, 6, 16),
  Decimal('66292.501179'),
  Decimal('79.800000'),
  Decimal('7511.350098')),
 (datetime.date(2026, 6, 17),
  Decimal('65619.280800'),
  Decimal('80.650000'),
  Decimal('7420.100098')),
 (datetime.date(2026, 6, 18),
  Decimal('64444.545330'),
  Decimal('80.350000'),
  Decimal('7500.580078')),
 (datetime.date(2026, 6, 22),
  Decimal('63255.485253'),
  Decimal('78.940000'),
  Decimal('7472.790039')),
 (datetime.date(2026, 6, 23),
  Decimal('63937.285264'),
  Decimal('74.620000'),
  Decimal('7365.459961')),
 (datetime.date(2026, 6, 24),
  Decimal('62662.292019'),
  Decimal('71.420000'),
  Decimal('7358.220215')),
 (datetime.date(2026, 6, 25),
  Decimal('60989.573522'),
  Decimal('72.670000'),
  Decimal('7357.490234')),
 (datetime.date(2026, 6, 26),
  Decimal('59726.736535'),
  Decimal('70.300000'),
  Decimal('7354.020020')),
 (datetime.date(2026, 6, 29),
  Decimal('59494.606386'),
  Decimal('71.870000'),
  Decimal('7440.430176')),
 (datetime.date(2026, 6, 30),
  Decimal('60152.358721'),
  Decimal('70.560000'),
  Decimal('7499.359863')),
 (datetime.date(2026, 7, 1),
  Decimal('58566.091992'),
  Decimal('69.740000'),
  Decimal('7483.229980')),
 (datetime.date(2026, 7, 2),
  Decimal('59967.685042'),